github: [croessner]
custom:
  - "https://www.paypal.com/donate/?hosted_button_id=3XLD5KEJD7AQ8"
  - "https://nauthilus.org/docs/intro/#commercial-support"

# The PayPal donation page can offer one-time or recurring donations when enabled in PayPal.
