// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server/grpcapi/common/v1/common.proto

package commonv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// OperationResult describes the domain result of an authority-side operation.
type OperationResult int32

const (
	OperationResult_OPERATION_RESULT_UNSPECIFIED OperationResult = 0
	OperationResult_OPERATION_RESULT_OK          OperationResult = 1
	OperationResult_OPERATION_RESULT_FAIL        OperationResult = 2
	OperationResult_OPERATION_RESULT_TEMPFAIL    OperationResult = 3
	OperationResult_OPERATION_RESULT_DENIED      OperationResult = 4
	OperationResult_OPERATION_RESULT_NOT_FOUND   OperationResult = 5
	OperationResult_OPERATION_RESULT_CONFLICT    OperationResult = 6
)

// Enum value maps for OperationResult.
var (
	OperationResult_name = map[int32]string{
		0: "OPERATION_RESULT_UNSPECIFIED",
		1: "OPERATION_RESULT_OK",
		2: "OPERATION_RESULT_FAIL",
		3: "OPERATION_RESULT_TEMPFAIL",
		4: "OPERATION_RESULT_DENIED",
		5: "OPERATION_RESULT_NOT_FOUND",
		6: "OPERATION_RESULT_CONFLICT",
	}
	OperationResult_value = map[string]int32{
		"OPERATION_RESULT_UNSPECIFIED": 0,
		"OPERATION_RESULT_OK":          1,
		"OPERATION_RESULT_FAIL":        2,
		"OPERATION_RESULT_TEMPFAIL":    3,
		"OPERATION_RESULT_DENIED":      4,
		"OPERATION_RESULT_NOT_FOUND":   5,
		"OPERATION_RESULT_CONFLICT":    6,
	}
)

func (x OperationResult) Enum() *OperationResult {
	p := new(OperationResult)
	*p = x
	return p
}

func (x OperationResult) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationResult) Descriptor() protoreflect.EnumDescriptor {
	return file_server_grpcapi_common_v1_common_proto_enumTypes[0].Descriptor()
}

func (OperationResult) Type() protoreflect.EnumType {
	return &file_server_grpcapi_common_v1_common_proto_enumTypes[0]
}

func (x OperationResult) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationResult.Descriptor instead.
func (OperationResult) EnumDescriptor() ([]byte, []int) {
	return file_server_grpcapi_common_v1_common_proto_rawDescGZIP(), []int{0}
}

// ErrorDetail describes a single safe validation or operation error detail.
type ErrorDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ErrorDetail) Reset() {
	*x = ErrorDetail{}
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorDetail) ProtoMessage() {}

func (x *ErrorDetail) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorDetail.ProtoReflect.Descriptor instead.
func (*ErrorDetail) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_common_v1_common_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ErrorDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// OperationStatus carries a safe, transport-neutral operation outcome.
type OperationStatus struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Result             OperationResult        `protobuf:"varint,1,opt,name=result,proto3,enum=nauthilus.common.v1.OperationResult" json:"result,omitempty"`
	ErrorCode          string                 `protobuf:"bytes,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	SafeMessage        string                 `protobuf:"bytes,3,opt,name=safe_message,json=safeMessage,proto3" json:"safe_message,omitempty"`
	EdgeRequestId      string                 `protobuf:"bytes,4,opt,name=edge_request_id,json=edgeRequestId,proto3" json:"edge_request_id,omitempty"`
	AuthorityRequestId string                 `protobuf:"bytes,5,opt,name=authority_request_id,json=authorityRequestId,proto3" json:"authority_request_id,omitempty"`
	Details            []*ErrorDetail         `protobuf:"bytes,6,rep,name=details,proto3" json:"details,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *OperationStatus) Reset() {
	*x = OperationStatus{}
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStatus) ProtoMessage() {}

func (x *OperationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStatus.ProtoReflect.Descriptor instead.
func (*OperationStatus) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_common_v1_common_proto_rawDescGZIP(), []int{1}
}

func (x *OperationStatus) GetResult() OperationResult {
	if x != nil {
		return x.Result
	}
	return OperationResult_OPERATION_RESULT_UNSPECIFIED
}

func (x *OperationStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *OperationStatus) GetSafeMessage() string {
	if x != nil {
		return x.SafeMessage
	}
	return ""
}

func (x *OperationStatus) GetEdgeRequestId() string {
	if x != nil {
		return x.EdgeRequestId
	}
	return ""
}

func (x *OperationStatus) GetAuthorityRequestId() string {
	if x != nil {
		return x.AuthorityRequestId
	}
	return ""
}

func (x *OperationStatus) GetDetails() []*ErrorDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

// AttributeValues stores released string attribute values under one attribute name.
type AttributeValues struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AttributeValues) Reset() {
	*x = AttributeValues{}
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeValues) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeValues) ProtoMessage() {}

func (x *AttributeValues) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeValues.ProtoReflect.Descriptor instead.
func (*AttributeValues) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_common_v1_common_proto_rawDescGZIP(), []int{2}
}

func (x *AttributeValues) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// BackendRef identifies an authority-side backend selection without exposing backend credentials.
type BackendRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Authority     string                 `protobuf:"bytes,4,opt,name=authority,proto3" json:"authority,omitempty"`
	OpaqueToken   string                 `protobuf:"bytes,5,opt,name=opaque_token,json=opaqueToken,proto3" json:"opaque_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackendRef) Reset() {
	*x = BackendRef{}
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackendRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackendRef) ProtoMessage() {}

func (x *BackendRef) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_common_v1_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackendRef.ProtoReflect.Descriptor instead.
func (*BackendRef) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_common_v1_common_proto_rawDescGZIP(), []int{3}
}

func (x *BackendRef) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *BackendRef) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackendRef) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *BackendRef) GetAuthority() string {
	if x != nil {
		return x.Authority
	}
	return ""
}

func (x *BackendRef) GetOpaqueToken() string {
	if x != nil {
		return x.OpaqueToken
	}
	return ""
}

var File_server_grpcapi_common_v1_common_proto protoreflect.FileDescriptor

const file_server_grpcapi_common_v1_common_proto_rawDesc = "" +
	"\n" +
	"%server/grpcapi/common/v1/common.proto\x12\x13nauthilus.common.v1\";\n" +
	"\vErrorDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xa7\x02\n" +
	"\x0fOperationStatus\x12<\n" +
	"\x06result\x18\x01 \x01(\x0e2$.nauthilus.common.v1.OperationResultR\x06result\x12\x1d\n" +
	"\n" +
	"error_code\x18\x02 \x01(\tR\terrorCode\x12!\n" +
	"\fsafe_message\x18\x03 \x01(\tR\vsafeMessage\x12&\n" +
	"\x0fedge_request_id\x18\x04 \x01(\tR\redgeRequestId\x120\n" +
	"\x14authority_request_id\x18\x05 \x01(\tR\x12authorityRequestId\x12:\n" +
	"\adetails\x18\x06 \x03(\v2 .nauthilus.common.v1.ErrorDetailR\adetails\")\n" +
	"\x0fAttributeValues\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"\x91\x01\n" +
	"\n" +
	"BackendRef\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12\x1c\n" +
	"\tauthority\x18\x04 \x01(\tR\tauthority\x12!\n" +
	"\fopaque_token\x18\x05 \x01(\tR\vopaqueToken*\xe2\x01\n" +
	"\x0fOperationResult\x12 \n" +
	"\x1cOPERATION_RESULT_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OPERATION_RESULT_OK\x10\x01\x12\x19\n" +
	"\x15OPERATION_RESULT_FAIL\x10\x02\x12\x1d\n" +
	"\x19OPERATION_RESULT_TEMPFAIL\x10\x03\x12\x1b\n" +
	"\x17OPERATION_RESULT_DENIED\x10\x04\x12\x1e\n" +
	"\x1aOPERATION_RESULT_NOT_FOUND\x10\x05\x12\x1d\n" +
	"\x19OPERATION_RESULT_CONFLICT\x10\x06BBZ@github.com/croessner/nauthilus/server/grpcapi/common/v1;commonv1b\x06proto3"

var (
	file_server_grpcapi_common_v1_common_proto_rawDescOnce sync.Once
	file_server_grpcapi_common_v1_common_proto_rawDescData []byte
)

func file_server_grpcapi_common_v1_common_proto_rawDescGZIP() []byte {
	file_server_grpcapi_common_v1_common_proto_rawDescOnce.Do(func() {
		file_server_grpcapi_common_v1_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpcapi_common_v1_common_proto_rawDesc), len(file_server_grpcapi_common_v1_common_proto_rawDesc)))
	})
	return file_server_grpcapi_common_v1_common_proto_rawDescData
}

var file_server_grpcapi_common_v1_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_grpcapi_common_v1_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_server_grpcapi_common_v1_common_proto_goTypes = []any{
	(OperationResult)(0),    // 0: nauthilus.common.v1.OperationResult
	(*ErrorDetail)(nil),     // 1: nauthilus.common.v1.ErrorDetail
	(*OperationStatus)(nil), // 2: nauthilus.common.v1.OperationStatus
	(*AttributeValues)(nil), // 3: nauthilus.common.v1.AttributeValues
	(*BackendRef)(nil),      // 4: nauthilus.common.v1.BackendRef
}
var file_server_grpcapi_common_v1_common_proto_depIdxs = []int32{
	0, // 0: nauthilus.common.v1.OperationStatus.result:type_name -> nauthilus.common.v1.OperationResult
	1, // 1: nauthilus.common.v1.OperationStatus.details:type_name -> nauthilus.common.v1.ErrorDetail
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_server_grpcapi_common_v1_common_proto_init() }
func file_server_grpcapi_common_v1_common_proto_init() {
	if File_server_grpcapi_common_v1_common_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpcapi_common_v1_common_proto_rawDesc), len(file_server_grpcapi_common_v1_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_grpcapi_common_v1_common_proto_goTypes,
		DependencyIndexes: file_server_grpcapi_common_v1_common_proto_depIdxs,
		EnumInfos:         file_server_grpcapi_common_v1_common_proto_enumTypes,
		MessageInfos:      file_server_grpcapi_common_v1_common_proto_msgTypes,
	}.Build()
	File_server_grpcapi_common_v1_common_proto = out.File
	file_server_grpcapi_common_v1_common_proto_goTypes = nil
	file_server_grpcapi_common_v1_common_proto_depIdxs = nil
}
