package main

const (
	componentObservation = "observation_context"
	directionRisk        = "risk"
	directionTrust       = "trust"
	magnitudeForbidden   = "forbidden"
	magnitudeOptional    = "optional"
	magnitudeRequired    = "required"
	normalizeLowercase   = "lowercase"
	normalizeExact       = "exact"
	kindIP               = "ip"
	kindNetwork          = "network"
	kindASN              = "asn"
	kindDomain           = "dns_domain"
	kindAccount          = "account"
	kindService          = "service"
	profileFast          = "fast"
	profileOperational   = "operational"
	profileBaseline      = "baseline"
	fieldEventID         = "event_id"
	fieldObservedAt      = "observed_at"
	fieldSignal          = "signal"
	fieldSubjects        = "subjects"
	fieldMagnitude       = "magnitude"
	fieldCorrelationID   = "correlation_id"
	fieldRole            = "role"
	fieldKind            = "kind"
	fieldValue           = "value"
	fieldSubjectTag      = "subject_tag"
	fieldWeight          = "weight"
	summaryUnbound       = "unbound"
	outputValid          = "observation_valid"
	outputEligible       = "observation_learning_eligible"
	outputReason         = "observation_reason"
	outputSourceClass    = "observation_source_class"
	outputOrigin         = "observation_evidence_origin"
	outputKinds          = "observation_subject_kinds"
	outputSubjects       = "admitted_subjects"
)
