{
 "title": "Nauthilus",
 "description": "Nginx authserv IMAP and SMTP authentication service",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   {
    "name": "instance",
    "label": "instance",
    "query": {
     "query": "label_values(up{job=\"nauthilus\"},instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Misc", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(cpu_user_usage_percent{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "User"
    },
    {
     "expr": "avg(cpu_system_usage_percent{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "System"
    },
    {
     "expr": "avg(cpu_iowait_usage_percent{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "IOWait"
    },
    {
     "expr": "avg(cpu_nice_usage_percent{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Nice"
    },
    {
     "expr": "avg(cpu_idle_usage_percent{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "LDAP pools",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 14, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (pool) (ldap_pool_connections_total{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "active {{pool}}"
    },
    {
     "expr": "sum by (pool) (ldap_pool_open_connections_total{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "open {{pool}}"
    },
    {
     "expr": "sum by (pool) (ldap_pool_stale_connections_total{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "stale {{pool}}"
    },
    {
     "expr": "sum by (pool) (ldap_idle_pool_size{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "size idle {{pool}}"
    },
    {
     "expr": "sum by (pool) (ldap_pool_size{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "size {{pool}}"
    }
   ]
  },
  {
   "title": "HTTP server connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(generic_connections{job=\"nauthilus\",instance=~\"$instance\",direction=\"local\"})",
     "legendFormat": "Connections"
    }
   ]
  },
  {
   "title": "HTTP client established connections",
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 2, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (target,direction,description) (generic_connections{job=\"nauthilus\",instance=~\"$instance\",direction=\"remote\"})",
     "legendFormat": "{{description}}"
    }
   ]
  },
  {
   "title": "HTTP server concurrent requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 8, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(server_concurrent_requests{job=\"nauthilus\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "HTTP client concourrent requests",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 10, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (service) (http_client_concurrent_requests_total{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "OS threads",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 2, "x": 17, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(avg_over_time(go_threads{job=\"nauthilus\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "Threads"
    }
   ]
  },
  {
   "title": "Backend servers",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 19, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (server_status) (backend_servers_status{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "{{server_status}}"
    }
   ]
  },
  {
   "title": "Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(1, nauthilus_version_info{job=\"nauthilus\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(start_timestamp{job=\"nauthilus\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Last reloaded",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(last_reload_timestamp{job=\"nauthilus\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "Account status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Login stats",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n    logins_total{job=\"nauthilus\", instance=~\"$instance\", logins=\"success\"}\n    - logins_total{job=\"nauthilus\", instance=~\"$instance\", logins=\"success\"} offset $__range\n)",
     "legendFormat": "success"
    },
    {
     "expr": "sum(\n    logins_total{job=\"nauthilus\", instance=~\"$instance\", logins=\"failure\"}\n    - logins_total{job=\"nauthilus\", instance=~\"$instance\", logins=\"failure\"} offset $__range\n)",
     "legendFormat": "failure"
    }
   ]
  },
  { "title": "Security $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Accepted protocols",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(accepted_protocols_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "Rejected protocols",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 34 },
   "targets": [
    {
     "expr": "sum by (protocol) (rate(rejected_protocols_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{protocol}}"
    }
   ]
  },
  {
   "title": "GeoIP country overview",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "sum by (country) (rate(geoippolicyd_count{job=\"nauthilus\",instance=~\"$instance\",country!=\"\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{country}} {{status}}"
    }
   ]
  },
  {
   "title": "Environment efficiency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 48 },
   "targets": [
    {
     "expr": "sum by (environment) (rate(analytics_count{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{environment}}"
    }
   ]
  },
  {
   "title": "Reject reasons",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 55 },
   "targets": [
    {
     "expr": "sum by (reason,protocol) (rate(ldap_filter_reject_reason_count{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "{{reason}}: {{protocol}}"
    }
   ]
  },
  {
   "title": "RBL rejects",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 62 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (rbl) (increase(rbl_rejected_total{job=\"nauthilus\",instance=~\"$instance\"}[$__range]))",
     "legendFormat": "{{rbl}}"
    }
   ]
  },
  {
   "title": "RBL hits over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 5, "y": 62 },
   "targets": [
    {
     "expr": "sum by (rbl) (rate(rbl_rejected_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{rbl}}"
    }
   ]
  },
  {
   "title": "Bruteforce bucket counters",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 9, "x": 13, "y": 62 },
   "targets": [
    {
     "expr": "sum by (bucket) (rate(bruteforce_rejected_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "Reject {{bucket}}"
    },
    {
     "expr": "sum by (bucket) (rate(bruteforce_hits_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]) > 0)",
     "legendFormat": "Hits {{bucket}}"
    }
   ]
  },
  { "title": "Activity", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 } },
  {
   "title": "HTTP server requests History",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by (path) (irate(http_requests_total{job=\"nauthilus\", instance=~\"$instance\",path!=\"\"}[1m]))",
     "legendFormat": "{{path}}"
    }
   ]
  },
  {
   "title": "Network traffic",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(irate(process_network_receive_bytes_total{job=~\"nauthilus\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "Received"
    },
    {
     "expr": "sum(irate(process_network_transmit_bytes_total{job=\"nauthilus\", instance=~\"$instance\"}[1m]))",
     "legendFormat": "Transmitted"
    }
   ]
  },
  {
   "title": "Local Cache",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 82 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(irate(cache_hits_total{job=\"nauthilus\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Hits"
    },
    {
     "expr": "avg(irate(cache_misses_total{job=\"nauthilus\",instance=~\"$instance\"}[1m]))",
     "legendFormat": "Misses"
    }
   ]
  },
  {
   "title": "Redis reads/writes per minute",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 88 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg(rate(redis_read_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Reads"
    },
    {
     "expr": "avg(rate(redis_write_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Writes"
    }
   ]
  },
  {
   "title": "Redis connections stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 94 },
   "fieldConfig": { "defaults": { "unit": "conns/s" } },
   "targets": [
    {
     "expr": "avg by (pool_name) (rate(redis_connection_hits_total{job=\"nauthilus\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Hits {{pool_name}}"
    },
    {
     "expr": "avg by (pool_name) (rate(redis_connection_misses_total{job=\"nauthilus\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Misses {{pool_name}}"
    },
    {
     "expr": "avg by (pool_name) (rate(redis_connection_timeouts_total{job=\"nauthilus\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Timeouts {{pool_name}}"
    }
   ]
  },
  {
   "title": "Redis pool stats",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "conns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (pool_name) (redis_pool_total_connections{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Open {{pool_name}}"
    },
    {
     "expr": "avg by (pool_name) (redis_pool_idle_connections{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Idle {{pool_name}}"
    },
    {
     "expr": "avg by (pool_name) (redis_pool_stale_connections{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Stale {{pool_name}}"
    }
   ]
  },
  { "title": "Redis Server", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 111 } },
  {
   "title": "Redis Command Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 112 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "redis_latency_milliseconds{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "{{command}} ({{instance}})"
    }
   ]
  },
  {
   "title": "Redis Operations and Network",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 112 },
   "targets": [
    {
     "expr": "redis_instantaneous_ops_per_sec{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Commands/sec ({{instance}})"
    },
    {
     "expr": "redis_instantaneous_input_kbps{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Network In KB/s ({{instance}})"
    },
    {
     "expr": "redis_instantaneous_output_kbps{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Network Out KB/s ({{instance}})"
    },
    {
     "expr": "redis_connected_clients{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Connected Clients ({{instance}})"
    }
   ]
  },
  {
   "title": "Redis Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 120 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "redis_used_memory_bytes{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Used Memory ({{instance}})"
    },
    {
     "expr": "redis_used_memory_rss_bytes{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Used Memory RSS ({{instance}})"
    },
    {
     "expr": "redis_mem_fragmentation_ratio{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Fragmentation Ratio ({{instance}})"
    }
   ]
  },
  {
   "title": "Redis Keyspace Stats",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 11, "y": 120 },
   "targets": [
    {
     "expr": "redis_keyspace_hits_total{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Keyspace Hits ({{instance}})"
    },
    {
     "expr": "redis_keyspace_misses_total{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Keyspace Misses ({{instance}})"
    },
    {
     "expr": "redis_keyspace_hit_rate{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Hit Rate ({{instance}})"
    },
    {
     "expr": "redis_expired_keys_total{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Expired Keys ({{instance}})"
    },
    {
     "expr": "redis_evicted_keys_total{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Evicted Keys ({{instance}})"
    }
   ]
  },
  {
   "title": "Redis Error Metrics",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 128 },
   "targets": [
    {
     "expr": "redis_rejected_connections_total{job=\"nauthilus\", instance=~\"$instance\"}",
     "legendFormat": "Rejected Connections ({{instance}})"
    }
   ]
  },
  { "title": "Latency", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 136 } },
  {
   "title": "Request timings custom Lua",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 137 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (search) (irate(ldap_filter_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\"}[1m]) / irate(ldap_filter_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\"}[1m]) > 0)",
     "legendFormat": "ldap filter {{search}}"
    },
    {
     "expr": "avg by (http) (irate(blocklist_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\"}[1m]) / irate(blocklist_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\"}[1m]) > 0)",
     "legendFormat": "blocklist http {{http}}"
    },
    {
     "expr": "avg by (http) (irate(geoippolicyd_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\"}[1m]) / irate(geoippolicyd_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\"}[1m]) > 0)",
     "legendFormat": "geoippolicyd http {{http}}"
    },
    {
     "expr": "avg by (http) (irate(haveibeenpwnd_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\"}[1m]) / irate(haveibeenpwnd_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\"}[1m]) > 0)",
     "legendFormat": "haveibeenpwnd http {{http}}"
    },
    {
     "expr": "avg by (bot) (irate(telegram_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\"}[1m]) / irate(telegram_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\"}[1m]) > 0)",
     "legendFormat": "telegram bot {{bot}}"
    }
   ]
  },
  {
   "title": "LDAP searches",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(ldap_filter_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "Filter"
    },
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",task=\"ldap_backend_lookup_request_total\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "Lookup"
    }
   ]
  },
  {
   "title": "LDAP binds",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 146 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",task=\"ldap_backend_auth_request_total\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "Auth"
    }
   ]
  },
  {
   "title": "HTTP response times",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(http_response_time_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval])) by (le)))",
     "legendFormat": "Responses"
    }
   ]
  },
  {
   "title": "External HTTP requests",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 152 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",task=\"post:Check haveibeenpwnd network\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "haveibeenpwnd"
    }
   ]
  },
  {
   "title": "DNS lookups",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",service=\"dns\",task=\"ptr\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "PTR"
    },
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",service=\"dns\",task=\"rbl\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "RBL"
    }
   ]
  },
  {
   "title": "HTTP mesh services",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 11, "y": 158 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",service=\"environment\",task=\"Check blocklist.de\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "blocklist"
    },
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(function_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",service=\"subject\",task=\"Check GeoIP policy\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "geoip-policyd"
    }
   ]
  },
  {
   "title": "RBL DNS lookup timings",
   "type": "histogram",
   "gridPos": { "h": 6, "w": 11, "x": 0, "y": 164 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(rbl_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",rbl=\"AbusiX AuthBL\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "AbusiX"
    },
    {
     "expr": "avg(histogram_quantile(0.95, sum(rate(rbl_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",rbl=\"SpamRats AuthBL\"}[$__rate_interval])) by (le)) > 0)",
     "legendFormat": "SpamRats"
    }
   ]
  },
  {
   "title": "Request timings auth (builtin)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 22, "x": 0, "y": 170 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service,task) (irate(function_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\",service!=\"action\",service!=\"post_action\",task!=\"request_no_auth_total\",task!=\"request_list_accounts_total\"}[1m]) / irate(function_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\",service!=\"action\",service!=\"post_action\",task!=\"request_no_auth_total\",task!=\"request_list_accounts_total\"}[1m]) > 0)",
     "legendFormat": "{{service}} {{task}}"
    }
   ]
  },
  {
   "title": "Request timings no-auth/list-accounts (builtin)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 0, "y": 181 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg by (service,task) (irate(function_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\",task=\"request_list_accounts_total\"}[1m]) / irate(function_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\",task=\"request_list_accounts_total\"}[1m]) > 0)",
     "legendFormat": "{{service}} {{task}}"
    },
    {
     "expr": "avg by (service,task) (irate(function_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\",task=\"request_no_auth_total\"}[1m]) / irate(function_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\",task=\"request_no_auth_total\"}[1m]) > 0)",
     "legendFormat": "{{service}} {{task}}"
    }
   ]
  },
  {
   "title": "Complete detached post-processing duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 22, "x": 0, "y": 189 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(post_action_plan_duration_seconds_sum{job=\"nauthilus\",instance=~\"$instance\",result=\"ok\"}[$__rate_interval])) / clamp_min(sum(rate(post_action_plan_duration_seconds_count{job=\"nauthilus\",instance=~\"$instance\",result=\"ok\"}[$__rate_interval])), 1e-9)",
     "legendFormat": "average"
    },
    {
     "expr": "histogram_quantile(0.95, sum by (le) (rate(post_action_plan_duration_seconds_bucket{job=\"nauthilus\",instance=~\"$instance\",result=\"ok\"}[$__rate_interval])))",
     "legendFormat": "p95"
    }
   ]
  },
  { "title": "Debugging", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 198 } },
  {
   "title": "Goroutines",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 199 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_goroutines{job=\"nauthilus\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Profiling bucket hash table (changes)",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 4, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(delta(go_memstats_buck_hash_sys_bytes{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Hash map"
    }
   ]
  },
  {
   "title": "Garbage collection system metadata",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(go_memstats_gc_sys_bytes{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Bytes GC"
    }
   ]
  },
  {
   "title": "Total number of mallocs",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 16, "y": 199 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(go_memstats_mallocs_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))"
    }
   ]
  },
  {
   "title": "Number of bytes obtained from system",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 203 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_sys_bytes{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Sys"
    }
   ]
  },
  {
   "title": "Number of heap bytes",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 209 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_alloc_bytes{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Heap alloc"
    },
    {
     "expr": "avg(go_memstats_heap_inuse_bytes{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Heap in use"
    },
    {
     "expr": "avg(go_memstats_heap_idle_bytes{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Heap idle"
    }
   ]
  },
  {
   "title": "Number of bytes obtained from system for stack allocator",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 215 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_stack_sys_bytes{job=\"nauthilus\", instance=~\"$instance\"})",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Total number of bytes allocated, even if freed",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 221 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(rate(go_memstats_alloc_bytes_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Number of heap bytes released to OS",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 227 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_released_bytes{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Bytes"
    }
   ]
  },
  {
   "title": "Total number of frees",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 233 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rate(go_memstats_frees_total{job=\"nauthilus\",instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "Frees"
    }
   ]
  },
  {
   "title": "Number of allocated objects",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 22, "x": 0, "y": 239 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(go_memstats_heap_objects{job=\"nauthilus\",instance=~\"$instance\"})",
     "legendFormat": "Objects"
    }
   ]
  }
 ]
}