// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server/grpcapi/auth/v1/auth.proto

package authv1

import (
	v1 "github.com/croessner/nauthilus/server/grpcapi/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthDecision int32

const (
	AuthDecision_AUTH_DECISION_UNSPECIFIED AuthDecision = 0
	AuthDecision_AUTH_DECISION_OK          AuthDecision = 1
	AuthDecision_AUTH_DECISION_FAIL        AuthDecision = 2
	AuthDecision_AUTH_DECISION_TEMPFAIL    AuthDecision = 3
)

// Enum value maps for AuthDecision.
var (
	AuthDecision_name = map[int32]string{
		0: "AUTH_DECISION_UNSPECIFIED",
		1: "AUTH_DECISION_OK",
		2: "AUTH_DECISION_FAIL",
		3: "AUTH_DECISION_TEMPFAIL",
	}
	AuthDecision_value = map[string]int32{
		"AUTH_DECISION_UNSPECIFIED": 0,
		"AUTH_DECISION_OK":          1,
		"AUTH_DECISION_FAIL":        2,
		"AUTH_DECISION_TEMPFAIL":    3,
	}
)

func (x AuthDecision) Enum() *AuthDecision {
	p := new(AuthDecision)
	*p = x
	return p
}

func (x AuthDecision) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthDecision) Descriptor() protoreflect.EnumDescriptor {
	return file_server_grpcapi_auth_v1_auth_proto_enumTypes[0].Descriptor()
}

func (AuthDecision) Type() protoreflect.EnumType {
	return &file_server_grpcapi_auth_v1_auth_proto_enumTypes[0]
}

func (x AuthDecision) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthDecision.Descriptor instead.
func (AuthDecision) EnumDescriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

type AuthRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Username           string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password           string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	ClientIp           string                 `protobuf:"bytes,3,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort         string                 `protobuf:"bytes,4,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ClientHostname     string                 `protobuf:"bytes,5,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	ClientId           string                 `protobuf:"bytes,6,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExternalSessionId  string                 `protobuf:"bytes,7,opt,name=external_session_id,json=externalSessionId,proto3" json:"external_session_id,omitempty"`
	UserAgent          string                 `protobuf:"bytes,8,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LocalIp            string                 `protobuf:"bytes,9,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort          string                 `protobuf:"bytes,10,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Protocol           string                 `protobuf:"bytes,11,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method             string                 `protobuf:"bytes,12,opt,name=method,proto3" json:"method,omitempty"`
	Ssl                string                 `protobuf:"bytes,13,opt,name=ssl,proto3" json:"ssl,omitempty"`
	SslSessionId       string                 `protobuf:"bytes,14,opt,name=ssl_session_id,json=sslSessionId,proto3" json:"ssl_session_id,omitempty"`
	SslClientVerify    string                 `protobuf:"bytes,15,opt,name=ssl_client_verify,json=sslClientVerify,proto3" json:"ssl_client_verify,omitempty"`
	SslClientDn        string                 `protobuf:"bytes,16,opt,name=ssl_client_dn,json=sslClientDn,proto3" json:"ssl_client_dn,omitempty"`
	SslClientCn        string                 `protobuf:"bytes,17,opt,name=ssl_client_cn,json=sslClientCn,proto3" json:"ssl_client_cn,omitempty"`
	SslIssuer          string                 `protobuf:"bytes,18,opt,name=ssl_issuer,json=sslIssuer,proto3" json:"ssl_issuer,omitempty"`
	SslClientNotbefore string                 `protobuf:"bytes,19,opt,name=ssl_client_notbefore,json=sslClientNotbefore,proto3" json:"ssl_client_notbefore,omitempty"`
	SslClientNotafter  string                 `protobuf:"bytes,20,opt,name=ssl_client_notafter,json=sslClientNotafter,proto3" json:"ssl_client_notafter,omitempty"`
	SslSubjectDn       string                 `protobuf:"bytes,21,opt,name=ssl_subject_dn,json=sslSubjectDn,proto3" json:"ssl_subject_dn,omitempty"`
	SslIssuerDn        string                 `protobuf:"bytes,22,opt,name=ssl_issuer_dn,json=sslIssuerDn,proto3" json:"ssl_issuer_dn,omitempty"`
	SslClientSubjectDn string                 `protobuf:"bytes,23,opt,name=ssl_client_subject_dn,json=sslClientSubjectDn,proto3" json:"ssl_client_subject_dn,omitempty"`
	SslClientIssuerDn  string                 `protobuf:"bytes,24,opt,name=ssl_client_issuer_dn,json=sslClientIssuerDn,proto3" json:"ssl_client_issuer_dn,omitempty"`
	SslProtocol        string                 `protobuf:"bytes,25,opt,name=ssl_protocol,json=sslProtocol,proto3" json:"ssl_protocol,omitempty"`
	SslCipher          string                 `protobuf:"bytes,26,opt,name=ssl_cipher,json=sslCipher,proto3" json:"ssl_cipher,omitempty"`
	SslSerial          string                 `protobuf:"bytes,27,opt,name=ssl_serial,json=sslSerial,proto3" json:"ssl_serial,omitempty"`
	SslFingerprint     string                 `protobuf:"bytes,28,opt,name=ssl_fingerprint,json=sslFingerprint,proto3" json:"ssl_fingerprint,omitempty"`
	OidcCid            string                 `protobuf:"bytes,29,opt,name=oidc_cid,json=oidcCid,proto3" json:"oidc_cid,omitempty"`
	AuthLoginAttempt   uint32                 `protobuf:"varint,30,opt,name=auth_login_attempt,json=authLoginAttempt,proto3" json:"auth_login_attempt,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *AuthRequest) Reset() {
	*x = AuthRequest{}
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthRequest) ProtoMessage() {}

func (x *AuthRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthRequest.ProtoReflect.Descriptor instead.
func (*AuthRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *AuthRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *AuthRequest) GetClientPort() string {
	if x != nil {
		return x.ClientPort
	}
	return ""
}

func (x *AuthRequest) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *AuthRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *AuthRequest) GetExternalSessionId() string {
	if x != nil {
		return x.ExternalSessionId
	}
	return ""
}

func (x *AuthRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *AuthRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *AuthRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *AuthRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *AuthRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *AuthRequest) GetSsl() string {
	if x != nil {
		return x.Ssl
	}
	return ""
}

func (x *AuthRequest) GetSslSessionId() string {
	if x != nil {
		return x.SslSessionId
	}
	return ""
}

func (x *AuthRequest) GetSslClientVerify() string {
	if x != nil {
		return x.SslClientVerify
	}
	return ""
}

func (x *AuthRequest) GetSslClientDn() string {
	if x != nil {
		return x.SslClientDn
	}
	return ""
}

func (x *AuthRequest) GetSslClientCn() string {
	if x != nil {
		return x.SslClientCn
	}
	return ""
}

func (x *AuthRequest) GetSslIssuer() string {
	if x != nil {
		return x.SslIssuer
	}
	return ""
}

func (x *AuthRequest) GetSslClientNotbefore() string {
	if x != nil {
		return x.SslClientNotbefore
	}
	return ""
}

func (x *AuthRequest) GetSslClientNotafter() string {
	if x != nil {
		return x.SslClientNotafter
	}
	return ""
}

func (x *AuthRequest) GetSslSubjectDn() string {
	if x != nil {
		return x.SslSubjectDn
	}
	return ""
}

func (x *AuthRequest) GetSslIssuerDn() string {
	if x != nil {
		return x.SslIssuerDn
	}
	return ""
}

func (x *AuthRequest) GetSslClientSubjectDn() string {
	if x != nil {
		return x.SslClientSubjectDn
	}
	return ""
}

func (x *AuthRequest) GetSslClientIssuerDn() string {
	if x != nil {
		return x.SslClientIssuerDn
	}
	return ""
}

func (x *AuthRequest) GetSslProtocol() string {
	if x != nil {
		return x.SslProtocol
	}
	return ""
}

func (x *AuthRequest) GetSslCipher() string {
	if x != nil {
		return x.SslCipher
	}
	return ""
}

func (x *AuthRequest) GetSslSerial() string {
	if x != nil {
		return x.SslSerial
	}
	return ""
}

func (x *AuthRequest) GetSslFingerprint() string {
	if x != nil {
		return x.SslFingerprint
	}
	return ""
}

func (x *AuthRequest) GetOidcCid() string {
	if x != nil {
		return x.OidcCid
	}
	return ""
}

func (x *AuthRequest) GetAuthLoginAttempt() uint32 {
	if x != nil {
		return x.AuthLoginAttempt
	}
	return 0
}

type ListAccountsRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Username          string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientIp          string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort        string                 `protobuf:"bytes,3,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ClientHostname    string                 `protobuf:"bytes,4,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	ClientId          string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExternalSessionId string                 `protobuf:"bytes,6,opt,name=external_session_id,json=externalSessionId,proto3" json:"external_session_id,omitempty"`
	UserAgent         string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LocalIp           string                 `protobuf:"bytes,8,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort         string                 `protobuf:"bytes,9,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Protocol          string                 `protobuf:"bytes,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method            string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	OidcCid           string                 `protobuf:"bytes,12,opt,name=oidc_cid,json=oidcCid,proto3" json:"oidc_cid,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListAccountsRequest) Reset() {
	*x = ListAccountsRequest{}
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsRequest) ProtoMessage() {}

func (x *ListAccountsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsRequest.ProtoReflect.Descriptor instead.
func (*ListAccountsRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *ListAccountsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ListAccountsRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *ListAccountsRequest) GetClientPort() string {
	if x != nil {
		return x.ClientPort
	}
	return ""
}

func (x *ListAccountsRequest) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *ListAccountsRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ListAccountsRequest) GetExternalSessionId() string {
	if x != nil {
		return x.ExternalSessionId
	}
	return ""
}

func (x *ListAccountsRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *ListAccountsRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *ListAccountsRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *ListAccountsRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *ListAccountsRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *ListAccountsRequest) GetOidcCid() string {
	if x != nil {
		return x.OidcCid
	}
	return ""
}

type LookupIdentityRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Username           string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientIp           string                 `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort         string                 `protobuf:"bytes,3,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ClientHostname     string                 `protobuf:"bytes,4,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	ClientId           string                 `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExternalSessionId  string                 `protobuf:"bytes,6,opt,name=external_session_id,json=externalSessionId,proto3" json:"external_session_id,omitempty"`
	UserAgent          string                 `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LocalIp            string                 `protobuf:"bytes,8,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort          string                 `protobuf:"bytes,9,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Protocol           string                 `protobuf:"bytes,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method             string                 `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	Ssl                string                 `protobuf:"bytes,12,opt,name=ssl,proto3" json:"ssl,omitempty"`
	SslSessionId       string                 `protobuf:"bytes,13,opt,name=ssl_session_id,json=sslSessionId,proto3" json:"ssl_session_id,omitempty"`
	SslClientVerify    string                 `protobuf:"bytes,14,opt,name=ssl_client_verify,json=sslClientVerify,proto3" json:"ssl_client_verify,omitempty"`
	SslClientDn        string                 `protobuf:"bytes,15,opt,name=ssl_client_dn,json=sslClientDn,proto3" json:"ssl_client_dn,omitempty"`
	SslClientCn        string                 `protobuf:"bytes,16,opt,name=ssl_client_cn,json=sslClientCn,proto3" json:"ssl_client_cn,omitempty"`
	SslIssuer          string                 `protobuf:"bytes,17,opt,name=ssl_issuer,json=sslIssuer,proto3" json:"ssl_issuer,omitempty"`
	SslClientNotbefore string                 `protobuf:"bytes,18,opt,name=ssl_client_notbefore,json=sslClientNotbefore,proto3" json:"ssl_client_notbefore,omitempty"`
	SslClientNotafter  string                 `protobuf:"bytes,19,opt,name=ssl_client_notafter,json=sslClientNotafter,proto3" json:"ssl_client_notafter,omitempty"`
	SslSubjectDn       string                 `protobuf:"bytes,20,opt,name=ssl_subject_dn,json=sslSubjectDn,proto3" json:"ssl_subject_dn,omitempty"`
	SslIssuerDn        string                 `protobuf:"bytes,21,opt,name=ssl_issuer_dn,json=sslIssuerDn,proto3" json:"ssl_issuer_dn,omitempty"`
	SslClientSubjectDn string                 `protobuf:"bytes,22,opt,name=ssl_client_subject_dn,json=sslClientSubjectDn,proto3" json:"ssl_client_subject_dn,omitempty"`
	SslClientIssuerDn  string                 `protobuf:"bytes,23,opt,name=ssl_client_issuer_dn,json=sslClientIssuerDn,proto3" json:"ssl_client_issuer_dn,omitempty"`
	SslProtocol        string                 `protobuf:"bytes,24,opt,name=ssl_protocol,json=sslProtocol,proto3" json:"ssl_protocol,omitempty"`
	SslCipher          string                 `protobuf:"bytes,25,opt,name=ssl_cipher,json=sslCipher,proto3" json:"ssl_cipher,omitempty"`
	SslSerial          string                 `protobuf:"bytes,26,opt,name=ssl_serial,json=sslSerial,proto3" json:"ssl_serial,omitempty"`
	SslFingerprint     string                 `protobuf:"bytes,27,opt,name=ssl_fingerprint,json=sslFingerprint,proto3" json:"ssl_fingerprint,omitempty"`
	OidcCid            string                 `protobuf:"bytes,28,opt,name=oidc_cid,json=oidcCid,proto3" json:"oidc_cid,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *LookupIdentityRequest) Reset() {
	*x = LookupIdentityRequest{}
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LookupIdentityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LookupIdentityRequest) ProtoMessage() {}

func (x *LookupIdentityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LookupIdentityRequest.ProtoReflect.Descriptor instead.
func (*LookupIdentityRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{2}
}

func (x *LookupIdentityRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *LookupIdentityRequest) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *LookupIdentityRequest) GetClientPort() string {
	if x != nil {
		return x.ClientPort
	}
	return ""
}

func (x *LookupIdentityRequest) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *LookupIdentityRequest) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *LookupIdentityRequest) GetExternalSessionId() string {
	if x != nil {
		return x.ExternalSessionId
	}
	return ""
}

func (x *LookupIdentityRequest) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *LookupIdentityRequest) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *LookupIdentityRequest) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *LookupIdentityRequest) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *LookupIdentityRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *LookupIdentityRequest) GetSsl() string {
	if x != nil {
		return x.Ssl
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslSessionId() string {
	if x != nil {
		return x.SslSessionId
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientVerify() string {
	if x != nil {
		return x.SslClientVerify
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientDn() string {
	if x != nil {
		return x.SslClientDn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientCn() string {
	if x != nil {
		return x.SslClientCn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslIssuer() string {
	if x != nil {
		return x.SslIssuer
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientNotbefore() string {
	if x != nil {
		return x.SslClientNotbefore
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientNotafter() string {
	if x != nil {
		return x.SslClientNotafter
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslSubjectDn() string {
	if x != nil {
		return x.SslSubjectDn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslIssuerDn() string {
	if x != nil {
		return x.SslIssuerDn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientSubjectDn() string {
	if x != nil {
		return x.SslClientSubjectDn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslClientIssuerDn() string {
	if x != nil {
		return x.SslClientIssuerDn
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslProtocol() string {
	if x != nil {
		return x.SslProtocol
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslCipher() string {
	if x != nil {
		return x.SslCipher
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslSerial() string {
	if x != nil {
		return x.SslSerial
	}
	return ""
}

func (x *LookupIdentityRequest) GetSslFingerprint() string {
	if x != nil {
		return x.SslFingerprint
	}
	return ""
}

func (x *LookupIdentityRequest) GetOidcCid() string {
	if x != nil {
		return x.OidcCid
	}
	return ""
}

type AuthResponse struct {
	state           protoimpl.MessageState         `protogen:"open.v1"`
	Ok              bool                           `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Decision        AuthDecision                   `protobuf:"varint,2,opt,name=decision,proto3,enum=nauthilus.auth.v1.AuthDecision" json:"decision,omitempty"`
	Session         string                         `protobuf:"bytes,3,opt,name=session,proto3" json:"session,omitempty"`
	AccountField    string                         `protobuf:"bytes,4,opt,name=account_field,json=accountField,proto3" json:"account_field,omitempty"`
	TotpSecretField string                         `protobuf:"bytes,5,opt,name=totp_secret_field,json=totpSecretField,proto3" json:"totp_secret_field,omitempty"`
	Backend         uint32                         `protobuf:"varint,6,opt,name=backend,proto3" json:"backend,omitempty"`
	Attributes      map[string]*v1.AttributeValues `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	StatusMessage   string                         `protobuf:"bytes,8,opt,name=status_message,json=statusMessage,proto3" json:"status_message,omitempty"`
	Error           string                         `protobuf:"bytes,9,opt,name=error,proto3" json:"error,omitempty"`
	BackendRef      *v1.BackendRef                 `protobuf:"bytes,10,opt,name=backend_ref,json=backendRef,proto3" json:"backend_ref,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *AuthResponse) Reset() {
	*x = AuthResponse{}
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthResponse) ProtoMessage() {}

func (x *AuthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthResponse.ProtoReflect.Descriptor instead.
func (*AuthResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{3}
}

func (x *AuthResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *AuthResponse) GetDecision() AuthDecision {
	if x != nil {
		return x.Decision
	}
	return AuthDecision_AUTH_DECISION_UNSPECIFIED
}

func (x *AuthResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

func (x *AuthResponse) GetAccountField() string {
	if x != nil {
		return x.AccountField
	}
	return ""
}

func (x *AuthResponse) GetTotpSecretField() string {
	if x != nil {
		return x.TotpSecretField
	}
	return ""
}

func (x *AuthResponse) GetBackend() uint32 {
	if x != nil {
		return x.Backend
	}
	return 0
}

func (x *AuthResponse) GetAttributes() map[string]*v1.AttributeValues {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *AuthResponse) GetStatusMessage() string {
	if x != nil {
		return x.StatusMessage
	}
	return ""
}

func (x *AuthResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *AuthResponse) GetBackendRef() *v1.BackendRef {
	if x != nil {
		return x.BackendRef
	}
	return nil
}

type ListAccountsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Accounts      []string               `protobuf:"bytes,1,rep,name=accounts,proto3" json:"accounts,omitempty"`
	Session       string                 `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListAccountsResponse) Reset() {
	*x = ListAccountsResponse{}
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListAccountsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAccountsResponse) ProtoMessage() {}

func (x *ListAccountsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_auth_v1_auth_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAccountsResponse.ProtoReflect.Descriptor instead.
func (*ListAccountsResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP(), []int{4}
}

func (x *ListAccountsResponse) GetAccounts() []string {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *ListAccountsResponse) GetSession() string {
	if x != nil {
		return x.Session
	}
	return ""
}

var File_server_grpcapi_auth_v1_auth_proto protoreflect.FileDescriptor

const file_server_grpcapi_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"!server/grpcapi/auth/v1/auth.proto\x12\x11nauthilus.auth.v1\x1a%server/grpcapi/common/v1/common.proto\"\xb4\b\n" +
	"\vAuthRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x1b\n" +
	"\tclient_ip\x18\x03 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x04 \x01(\tR\n" +
	"clientPort\x12'\n" +
	"\x0fclient_hostname\x18\x05 \x01(\tR\x0eclientHostname\x12\x1b\n" +
	"\tclient_id\x18\x06 \x01(\tR\bclientId\x12.\n" +
	"\x13external_session_id\x18\a \x01(\tR\x11externalSessionId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\b \x01(\tR\tuserAgent\x12\x19\n" +
	"\blocal_ip\x18\t \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\n" +
	" \x01(\tR\tlocalPort\x12\x1a\n" +
	"\bprotocol\x18\v \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\f \x01(\tR\x06method\x12\x10\n" +
	"\x03ssl\x18\r \x01(\tR\x03ssl\x12$\n" +
	"\x0essl_session_id\x18\x0e \x01(\tR\fsslSessionId\x12*\n" +
	"\x11ssl_client_verify\x18\x0f \x01(\tR\x0fsslClientVerify\x12\"\n" +
	"\rssl_client_dn\x18\x10 \x01(\tR\vsslClientDn\x12\"\n" +
	"\rssl_client_cn\x18\x11 \x01(\tR\vsslClientCn\x12\x1d\n" +
	"\n" +
	"ssl_issuer\x18\x12 \x01(\tR\tsslIssuer\x120\n" +
	"\x14ssl_client_notbefore\x18\x13 \x01(\tR\x12sslClientNotbefore\x12.\n" +
	"\x13ssl_client_notafter\x18\x14 \x01(\tR\x11sslClientNotafter\x12$\n" +
	"\x0essl_subject_dn\x18\x15 \x01(\tR\fsslSubjectDn\x12\"\n" +
	"\rssl_issuer_dn\x18\x16 \x01(\tR\vsslIssuerDn\x121\n" +
	"\x15ssl_client_subject_dn\x18\x17 \x01(\tR\x12sslClientSubjectDn\x12/\n" +
	"\x14ssl_client_issuer_dn\x18\x18 \x01(\tR\x11sslClientIssuerDn\x12!\n" +
	"\fssl_protocol\x18\x19 \x01(\tR\vsslProtocol\x12\x1d\n" +
	"\n" +
	"ssl_cipher\x18\x1a \x01(\tR\tsslCipher\x12\x1d\n" +
	"\n" +
	"ssl_serial\x18\x1b \x01(\tR\tsslSerial\x12'\n" +
	"\x0fssl_fingerprint\x18\x1c \x01(\tR\x0esslFingerprint\x12\x19\n" +
	"\boidc_cid\x18\x1d \x01(\tR\aoidcCid\x12,\n" +
	"\x12auth_login_attempt\x18\x1e \x01(\rR\x10authLoginAttempt\"\x8d\x03\n" +
	"\x13ListAccountsRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x03 \x01(\tR\n" +
	"clientPort\x12'\n" +
	"\x0fclient_hostname\x18\x04 \x01(\tR\x0eclientHostname\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12.\n" +
	"\x13external_session_id\x18\x06 \x01(\tR\x11externalSessionId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12\x19\n" +
	"\blocal_ip\x18\b \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\t \x01(\tR\tlocalPort\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x19\n" +
	"\boidc_cid\x18\f \x01(\tR\aoidcCid\"\xf4\a\n" +
	"\x15LookupIdentityRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x03 \x01(\tR\n" +
	"clientPort\x12'\n" +
	"\x0fclient_hostname\x18\x04 \x01(\tR\x0eclientHostname\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12.\n" +
	"\x13external_session_id\x18\x06 \x01(\tR\x11externalSessionId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12\x19\n" +
	"\blocal_ip\x18\b \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\t \x01(\tR\tlocalPort\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x10\n" +
	"\x03ssl\x18\f \x01(\tR\x03ssl\x12$\n" +
	"\x0essl_session_id\x18\r \x01(\tR\fsslSessionId\x12*\n" +
	"\x11ssl_client_verify\x18\x0e \x01(\tR\x0fsslClientVerify\x12\"\n" +
	"\rssl_client_dn\x18\x0f \x01(\tR\vsslClientDn\x12\"\n" +
	"\rssl_client_cn\x18\x10 \x01(\tR\vsslClientCn\x12\x1d\n" +
	"\n" +
	"ssl_issuer\x18\x11 \x01(\tR\tsslIssuer\x120\n" +
	"\x14ssl_client_notbefore\x18\x12 \x01(\tR\x12sslClientNotbefore\x12.\n" +
	"\x13ssl_client_notafter\x18\x13 \x01(\tR\x11sslClientNotafter\x12$\n" +
	"\x0essl_subject_dn\x18\x14 \x01(\tR\fsslSubjectDn\x12\"\n" +
	"\rssl_issuer_dn\x18\x15 \x01(\tR\vsslIssuerDn\x121\n" +
	"\x15ssl_client_subject_dn\x18\x16 \x01(\tR\x12sslClientSubjectDn\x12/\n" +
	"\x14ssl_client_issuer_dn\x18\x17 \x01(\tR\x11sslClientIssuerDn\x12!\n" +
	"\fssl_protocol\x18\x18 \x01(\tR\vsslProtocol\x12\x1d\n" +
	"\n" +
	"ssl_cipher\x18\x19 \x01(\tR\tsslCipher\x12\x1d\n" +
	"\n" +
	"ssl_serial\x18\x1a \x01(\tR\tsslSerial\x12'\n" +
	"\x0fssl_fingerprint\x18\x1b \x01(\tR\x0esslFingerprint\x12\x19\n" +
	"\boidc_cid\x18\x1c \x01(\tR\aoidcCid\"\x95\x04\n" +
	"\fAuthResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12;\n" +
	"\bdecision\x18\x02 \x01(\x0e2\x1f.nauthilus.auth.v1.AuthDecisionR\bdecision\x12\x18\n" +
	"\asession\x18\x03 \x01(\tR\asession\x12#\n" +
	"\raccount_field\x18\x04 \x01(\tR\faccountField\x12*\n" +
	"\x11totp_secret_field\x18\x05 \x01(\tR\x0ftotpSecretField\x12\x18\n" +
	"\abackend\x18\x06 \x01(\rR\abackend\x12O\n" +
	"\n" +
	"attributes\x18\a \x03(\v2/.nauthilus.auth.v1.AuthResponse.AttributesEntryR\n" +
	"attributes\x12%\n" +
	"\x0estatus_message\x18\b \x01(\tR\rstatusMessage\x12\x14\n" +
	"\x05error\x18\t \x01(\tR\x05error\x12@\n" +
	"\vbackend_ref\x18\n" +
	" \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\n" +
	"backendRef\x1ac\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.nauthilus.common.v1.AttributeValuesR\x05value:\x028\x01\"L\n" +
	"\x14ListAccountsResponse\x12\x1a\n" +
	"\baccounts\x18\x01 \x03(\tR\baccounts\x12\x18\n" +
	"\asession\x18\x02 \x01(\tR\asession*w\n" +
	"\fAuthDecision\x12\x1d\n" +
	"\x19AUTH_DECISION_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10AUTH_DECISION_OK\x10\x01\x12\x16\n" +
	"\x12AUTH_DECISION_FAIL\x10\x02\x12\x1a\n" +
	"\x16AUTH_DECISION_TEMPFAIL\x10\x032\x9c\x02\n" +
	"\vAuthService\x12O\n" +
	"\fAuthenticate\x12\x1e.nauthilus.auth.v1.AuthRequest\x1a\x1f.nauthilus.auth.v1.AuthResponse\x12[\n" +
	"\x0eLookupIdentity\x12(.nauthilus.auth.v1.LookupIdentityRequest\x1a\x1f.nauthilus.auth.v1.AuthResponse\x12_\n" +
	"\fListAccounts\x12&.nauthilus.auth.v1.ListAccountsRequest\x1a'.nauthilus.auth.v1.ListAccountsResponseB>Z<github.com/croessner/nauthilus/server/grpcapi/auth/v1;authv1b\x06proto3"

var (
	file_server_grpcapi_auth_v1_auth_proto_rawDescOnce sync.Once
	file_server_grpcapi_auth_v1_auth_proto_rawDescData []byte
)

func file_server_grpcapi_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_server_grpcapi_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_server_grpcapi_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpcapi_auth_v1_auth_proto_rawDesc), len(file_server_grpcapi_auth_v1_auth_proto_rawDesc)))
	})
	return file_server_grpcapi_auth_v1_auth_proto_rawDescData
}

var file_server_grpcapi_auth_v1_auth_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_server_grpcapi_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_server_grpcapi_auth_v1_auth_proto_goTypes = []any{
	(AuthDecision)(0),             // 0: nauthilus.auth.v1.AuthDecision
	(*AuthRequest)(nil),           // 1: nauthilus.auth.v1.AuthRequest
	(*ListAccountsRequest)(nil),   // 2: nauthilus.auth.v1.ListAccountsRequest
	(*LookupIdentityRequest)(nil), // 3: nauthilus.auth.v1.LookupIdentityRequest
	(*AuthResponse)(nil),          // 4: nauthilus.auth.v1.AuthResponse
	(*ListAccountsResponse)(nil),  // 5: nauthilus.auth.v1.ListAccountsResponse
	nil,                           // 6: nauthilus.auth.v1.AuthResponse.AttributesEntry
	(*v1.BackendRef)(nil),         // 7: nauthilus.common.v1.BackendRef
	(*v1.AttributeValues)(nil),    // 8: nauthilus.common.v1.AttributeValues
}
var file_server_grpcapi_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: nauthilus.auth.v1.AuthResponse.decision:type_name -> nauthilus.auth.v1.AuthDecision
	6, // 1: nauthilus.auth.v1.AuthResponse.attributes:type_name -> nauthilus.auth.v1.AuthResponse.AttributesEntry
	7, // 2: nauthilus.auth.v1.AuthResponse.backend_ref:type_name -> nauthilus.common.v1.BackendRef
	8, // 3: nauthilus.auth.v1.AuthResponse.AttributesEntry.value:type_name -> nauthilus.common.v1.AttributeValues
	1, // 4: nauthilus.auth.v1.AuthService.Authenticate:input_type -> nauthilus.auth.v1.AuthRequest
	3, // 5: nauthilus.auth.v1.AuthService.LookupIdentity:input_type -> nauthilus.auth.v1.LookupIdentityRequest
	2, // 6: nauthilus.auth.v1.AuthService.ListAccounts:input_type -> nauthilus.auth.v1.ListAccountsRequest
	4, // 7: nauthilus.auth.v1.AuthService.Authenticate:output_type -> nauthilus.auth.v1.AuthResponse
	4, // 8: nauthilus.auth.v1.AuthService.LookupIdentity:output_type -> nauthilus.auth.v1.AuthResponse
	5, // 9: nauthilus.auth.v1.AuthService.ListAccounts:output_type -> nauthilus.auth.v1.ListAccountsResponse
	7, // [7:10] is the sub-list for method output_type
	4, // [4:7] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_server_grpcapi_auth_v1_auth_proto_init() }
func file_server_grpcapi_auth_v1_auth_proto_init() {
	if File_server_grpcapi_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpcapi_auth_v1_auth_proto_rawDesc), len(file_server_grpcapi_auth_v1_auth_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpcapi_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_server_grpcapi_auth_v1_auth_proto_depIdxs,
		EnumInfos:         file_server_grpcapi_auth_v1_auth_proto_enumTypes,
		MessageInfos:      file_server_grpcapi_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_server_grpcapi_auth_v1_auth_proto = out.File
	file_server_grpcapi_auth_v1_auth_proto_goTypes = nil
	file_server_grpcapi_auth_v1_auth_proto_depIdxs = nil
}
