// Copyright (C) 2026 Christian Rößner
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package config

import (
	"encoding/json"
	"fmt"
	"reflect"
	"slices"
	"sort"
	"strconv"
	"strings"
	"sync/atomic"
	"time"

	"github.com/croessner/nauthilus/server/definitions"
	"github.com/croessner/nauthilus/server/secret"
	"github.com/pelletier/go-toml/v2"
	"gopkg.in/yaml.v3"
)

type configDumpValueProvider func() any

const (
	redactedConfigValue             = "***REDACTED***"
	configDumpNullValue             = "null"
	defaultWebAuthnResidentKey      = "discouraged"
	defaultWebAuthnUserVerification = "preferred"
	defaultSAMLSignatureMethod      = "http://www.w3.org/2001/04/xmldsig-more#rsa-sha256"
)

var printSensitiveConfigValues atomic.Bool
var configDumpVersion atomic.Pointer[string]

// SetConfigDumpPrintSensitiveValues controls whether sensitive configuration values
// are shown in config dump output.
func SetConfigDumpPrintSensitiveValues(enabled bool) {
	printSensitiveConfigValues.Store(enabled)
}

// SetConfigDumpVersion controls which version string is shown in config dump headers.
func SetConfigDumpVersion(version string) {
	version = strings.TrimSpace(version)
	if version == "" {
		configDumpVersion.Store(nil)

		return
	}

	versionCopy := version
	configDumpVersion.Store(&versionCopy)
}

// RenderDefaultConfigDump renders canonical default configuration values
// as stable `path = value` lines.
func RenderDefaultConfigDump() (string, error) {
	return RenderDefaultConfigDumpWithFormat(DumpFormatCanonical)
}

// RenderDefaultConfigDumpWithFormat renders default configuration values in the
// requested dump format.
func RenderDefaultConfigDumpWithFormat(format DumpFormat) (string, error) {
	schemaIndex, err := getConfigSchemaIndex()
	if err != nil {
		return "", err
	}

	defaultProviders := configDumpDefaultProviders()
	if format == DumpFormatCanonical {
		lines := make([]string, 0)

		collectDefaultConfigDumpLines(schemaIndex.root, "", defaultProviders, &lines)
		sort.Strings(lines)

		return renderConfigDumpWithHeader(
			DumpFormatCanonical,
			"Nauthilus canonical default configuration",
			"Generated by `nauthilus -d`.",
			lines,
		), nil
	}

	rootValue := buildDefaultConfigDumpValue(schemaIndex.root, "", defaultProviders)
	normalized, _ := pruneStructuredConfigDumpValue(rootValue)

	rootMap, ok := normalized.(map[string]any)
	if !ok {
		return "", fmt.Errorf("unable to render default configuration as %s", format)
	}

	return renderStructuredConfigDump(format, true, rootMap)
}

// RenderNonDefaultConfigDump renders canonical non-default configuration values
// from merged settings as stable `path = value` lines.
func RenderNonDefaultConfigDump(settings map[string]any) (string, error) {
	return RenderNonDefaultConfigDumpWithFormat(settings, DumpFormatCanonical)
}

// RenderNonDefaultConfigDumpWithFormat renders non-default configuration values
// from merged settings in the requested dump format.
func RenderNonDefaultConfigDumpWithFormat(settings map[string]any, format DumpFormat) (string, error) {
	schemaIndex, err := getConfigSchemaIndex()
	if err != nil {
		return "", err
	}

	defaults := make(map[string]string)
	for path, provider := range configDumpDefaultProviders() {
		defaults[path] = formatConfigDumpValue(path, provider())
	}

	if format == DumpFormatCanonical {
		explicit := make(map[string]string)
		collectConfiguredConfigDumpValues(schemaIndex.root, settings, "", explicit)

		lines := make([]string, 0, len(explicit))

		for path, value := range explicit {
			if defaultValue, ok := defaults[path]; ok && defaultValue == value {
				continue
			}

			lines = append(lines, path+" = "+value)
		}

		sort.Strings(lines)

		return renderConfigDumpWithHeader(
			DumpFormatCanonical,
			"Nauthilus canonical non-default configuration",
			"Generated by `nauthilus -n`.",
			lines,
		), nil
	}

	rootValue, keep := buildStructuredNonDefaultConfigDumpValue(schemaIndex.root, settings, "", defaults)
	if !keep {
		rootValue = map[string]any{}
	}

	rootMap, ok := rootValue.(map[string]any)
	if !ok {
		return "", fmt.Errorf("unable to render non-default configuration as %s", format)
	}

	return renderStructuredConfigDump(format, false, rootMap)
}

func renderConfigDumpWithHeader(format DumpFormat, title string, note string, lines []string) string {
	header := make([]string, 0, 4)

	if title != "" {
		header = append(header, "# "+title)
	}

	if note != "" {
		header = append(header, "# "+note)
	}

	if version := getConfigDumpVersion(); version != "" {
		header = append(header, "# Version: "+version)
	}

	if len(header) == 0 || !format.supportsCommentHeader() {
		return strings.Join(lines, "\n")
	}

	if len(lines) == 0 {
		return strings.Join(header, "\n")
	}

	return strings.Join(append(append(header, ""), lines...), "\n")
}

func getConfigDumpVersion() string {
	versionPtr := configDumpVersion.Load()
	if versionPtr == nil {
		return ""
	}

	return strings.TrimSpace(*versionPtr)
}

func renderStructuredConfigDump(format DumpFormat, defaultsMode bool, data map[string]any) (string, error) {
	var (
		output []byte
		err    error
	)

	switch format {
	case DumpFormatYAML:
		output, err = yaml.Marshal(data)
	case DumpFormatJSON:
		output, err = json.MarshalIndent(data, "", "  ")
	case DumpFormatTOML:
		output, err = toml.Marshal(data)
	default:
		return "", fmt.Errorf("unsupported structured dump format %q", format)
	}
	if err != nil {
		return "", err
	}

	rendered := strings.TrimRight(string(output), "\n")
	title := "Nauthilus default configuration"
	note := "Generated by `nauthilus -d --dump-format " + string(format) + "`."

	if !defaultsMode {
		title = "Nauthilus non-default configuration"
		note = "Generated by `nauthilus -n --dump-format " + string(format) + "`."
	}

	if rendered == "" {
		return renderConfigDumpWithHeader(format, title, note, nil), nil
	}

	lines := strings.Split(rendered, "\n")

	return renderConfigDumpWithHeader(format, title, note, lines), nil
}

func buildDefaultConfigDumpValue(
	node *configSchemaNode,
	prefix string,
	defaultProviders map[string]configDumpValueProvider,
) any {
	if node == nil {
		return nil
	}

	switch node.kind {
	case configSchemaObject:
		result := make(map[string]any, len(node.fieldByConfigName))
		for _, key := range slicesSortedKeys(node.fieldByConfigName) {
			childPath := joinConfigPath(prefix, key)
			result[key] = buildDefaultConfigDumpValue(node.fieldByConfigName[key], childPath, defaultProviders)
		}

		return result
	case configSchemaList, configSchemaMap, configSchemaScalar:
		value := emptyValueForNode(node)
		if node.kind == configSchemaScalar {
			value = zeroValueForType(node.typeInfo)
		}

		if provider, ok := defaultProviders[prefix]; ok {
			value = provider()
		}

		return normalizeStructuredConfigDumpValue(prefix, value)
	default:
		return nil
	}
}

func buildStructuredNonDefaultConfigDumpValue(
	node *configSchemaNode,
	value any,
	prefix string,
	defaults map[string]string,
) (any, bool) {
	if node == nil || value == nil {
		return nil, false
	}

	switch node.kind {
	case configSchemaObject:
		entries, ok := configMapEntries(value)
		if !ok {
			normalized := normalizeStructuredConfigDumpValue(prefix, value)

			return normalized, true
		}

		sort.Slice(entries, func(left int, right int) bool {
			return entries[left].key < entries[right].key
		})

		result := make(map[string]any)
		for _, entry := range entries {
			childPath := joinConfigPath(prefix, entry.key)
			childNode, ok := node.fieldByConfigName[entry.key]
			if ok {
				childValue, keep := buildStructuredNonDefaultConfigDumpValue(childNode, entry.value, childPath, defaults)
				if keep {
					result[entry.key] = childValue
				}

				continue
			}

			if node.matchExtraKey != nil && node.matchExtraKey(entry.key) {
				normalized := normalizeStructuredConfigDumpValue(childPath, entry.value)
				pruned, keep := pruneStructuredConfigDumpValue(normalized)
				if keep {
					result[entry.key] = pruned
				}
			}
		}

		if len(result) == 0 {
			return nil, false
		}

		return result, true
	default:
		normalized := normalizeStructuredConfigDumpValue(prefix, value)
		if defaultValue, ok := defaults[prefix]; ok && defaultValue == formatConfigDumpValue(prefix, normalized) {
			return nil, false
		}

		pruned, keep := pruneStructuredConfigDumpValue(normalized)

		return pruned, keep
	}
}

func normalizeStructuredConfigDumpValue(path string, value any) any {
	if normalized, ok := normalizeKnownStructuredDumpValue(path, value); ok {
		return normalized
	}

	reflected, dereferencedValue, ok := dereferenceDumpValue(value)
	if !ok {
		return nil
	}

	if normalized, ok := normalizeKnownStructuredDumpValue(path, dereferencedValue); ok {
		return normalized
	}

	return normalizeReflectedStructuredDumpValue(path, reflected, dereferencedValue)
}

func normalizeReflectedStructuredDumpValue(path string, reflected reflect.Value, value any) any {
	switch reflected.Kind() {
	case reflect.String:
		return normalizeReflectedStructuredString(path, reflected.String())
	case reflect.Bool:
		return reflected.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return reflected.Int()
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return reflected.Uint()
	case reflect.Float32, reflect.Float64:
		return reflected.Float()
	case reflect.Slice, reflect.Array:
		return normalizeStructuredSequence(path, reflected)
	case reflect.Map:
		return normalizeStructuredMap(path, reflected)
	default:
		return fmt.Sprintf("%v", value)
	}
}

func normalizeReflectedStructuredString(path string, value string) string {
	if shouldRedactConfigDumpValue(path, value) {
		return redactedConfigValue
	}

	return value
}

func normalizeStructuredSequence(path string, reflected reflect.Value) []any {
	items := make([]any, 0, reflected.Len())
	for index := 0; index < reflected.Len(); index++ {
		items = append(items, normalizeStructuredConfigDumpValue(path, reflected.Index(index).Interface()))
	}

	return items
}

func normalizeStructuredMap(path string, reflected reflect.Value) map[string]any {
	if reflected.Len() == 0 {
		return map[string]any{}
	}

	keys := reflected.MapKeys()
	sort.Slice(keys, func(left int, right int) bool {
		return fmt.Sprintf("%v", keys[left].Interface()) < fmt.Sprintf("%v", keys[right].Interface())
	})

	result := make(map[string]any, len(keys))
	for _, key := range keys {
		keyString := fmt.Sprintf("%v", key.Interface())
		result[keyString] = normalizeStructuredConfigDumpValue(joinConfigPath(path, keyString), reflected.MapIndex(key).Interface())
	}

	return result
}

func normalizeKnownStructuredDumpValue(path string, value any) (any, bool) {
	if normalized, ok := normalizeStructuredPrimitiveDumpValue(path, value); ok {
		return normalized, true
	}

	if normalized, ok := normalizeStructuredStringerDumpValue(value); ok {
		return normalized, true
	}

	return normalizeStructuredNamedDumpValue(value)
}

func normalizeStructuredSecretValue(path string, value secret.Value) string {
	if value.IsZero() {
		return ""
	}

	if shouldRedactConfigDumpValue(path, value) {
		return redactedConfigValue
	}

	return value.String()
}

func normalizeStructuredPrimitiveDumpValue(path string, value any) (any, bool) {
	switch typed := value.(type) {
	case nil:
		return nil, true
	case string:
		if shouldRedactConfigDumpValue(path, typed) {
			return redactedConfigValue, true
		}

		return typed, true
	case bool:
		return typed, true
	case time.Duration:
		return typed.String(), true
	case secret.Value:
		return normalizeStructuredSecretValue(path, typed), true
	default:
		return nil, false
	}
}

func normalizeStructuredStringerDumpValue(value any) (string, bool) {
	switch typed := value.(type) {
	case ContentSecurityPolicyValue:
		return typed.String(), true
	case PermissionsPolicyValue:
		return typed.String(), true
	case StrictTransportSecurityValue:
		return typed.String(), true
	case Backend:
		return typed.String(), true
	case LDAPScope:
		return typed.String(), true
	default:
		return "", false
	}
}

func normalizeStructuredNamedDumpValue(value any) (string, bool) {
	switch typed := value.(type) {
	case Verbosity:
		return typed.Get(), true
	case Control:
		return typed.Get(), true
	case Service:
		return typed.Get(), true
	case Protocol:
		return typed.Get(), true
	case Feature:
		return typed.Get(), true
	case DbgModule:
		return typed.Get(), true
	default:
		return "", false
	}
}

func pruneStructuredConfigDumpValue(value any) (any, bool) {
	switch typed := value.(type) {
	case nil:
		return nil, false
	case map[string]any:
		if len(typed) == 0 {
			return typed, true
		}

		result := make(map[string]any, len(typed))
		for _, key := range slicesSortedKeys(typed) {
			pruned, keep := pruneStructuredConfigDumpValue(typed[key])
			if keep {
				result[key] = pruned
			}
		}

		if len(result) == 0 {
			return nil, false
		}

		return result, true
	case []any:
		items := make([]any, 0, len(typed))
		for _, item := range typed {
			pruned, keep := pruneStructuredConfigDumpValue(item)
			if keep {
				items = append(items, pruned)
			}
		}

		return items, true
	default:
		return value, true
	}
}

func collectDefaultConfigDumpLines(
	node *configSchemaNode,
	prefix string,
	defaultProviders map[string]configDumpValueProvider,
	out *[]string,
) {
	if node == nil || out == nil {
		return
	}

	switch node.kind {
	case configSchemaObject:
		keys := slicesSortedKeys(node.fieldByConfigName)

		for _, key := range keys {
			collectDefaultConfigDumpLines(node.fieldByConfigName[key], joinConfigPath(prefix, key), defaultProviders, out)
		}
	case configSchemaList:
		value := emptyValueForNode(node)
		if provider, ok := defaultProviders[prefix]; ok {
			value = provider()
		}

		*out = append(*out, prefix+" = "+formatConfigDumpValue(prefix, value))
	case configSchemaMap:
		value := emptyValueForNode(node)
		if provider, ok := defaultProviders[prefix]; ok {
			value = provider()
		}

		*out = append(*out, prefix+" = "+formatConfigDumpValue(prefix, value))
	case configSchemaScalar:
		value := zeroValueForType(node.typeInfo)
		if provider, ok := defaultProviders[prefix]; ok {
			value = provider()
		}

		*out = append(*out, prefix+" = "+formatConfigDumpValue(prefix, value))
	}
}

func collectConfiguredConfigDumpValues(node *configSchemaNode, value any, prefix string, out map[string]string) {
	if node == nil || out == nil || value == nil {
		return
	}

	switch node.kind {
	case configSchemaObject:
		collectConfiguredObjectValues(node, value, prefix, out)
	case configSchemaList:
		collectConfiguredListValues(node, value, prefix, out)
	case configSchemaMap:
		collectConfiguredMapValues(node, value, prefix, out)
	case configSchemaScalar:
		out[prefix] = formatConfigDumpValue(prefix, value)
	}
}

func collectConfiguredObjectValues(node *configSchemaNode, value any, prefix string, out map[string]string) {
	entries, ok := configMapEntries(value)
	if !ok {
		return
	}

	sort.Slice(entries, func(left int, right int) bool {
		return entries[left].key < entries[right].key
	})

	for _, entry := range entries {
		childPath := joinConfigPath(prefix, entry.key)
		childNode, ok := node.fieldByConfigName[entry.key]
		if ok {
			collectConfiguredConfigDumpValues(childNode, entry.value, childPath, out)

			continue
		}

		if node.matchExtraKey != nil && node.matchExtraKey(entry.key) {
			collectDynamicConfigDumpValues(entry.value, childPath, out)
		}
	}
}

func collectConfiguredListValues(node *configSchemaNode, value any, prefix string, out map[string]string) {
	elements, ok := value.([]any)
	if !ok || node.element == nil || node.element.kind == configSchemaScalar {
		out[prefix] = formatConfigDumpValue(prefix, value)

		return
	}

	for index := range elements {
		collectConfiguredConfigDumpValues(node.element, elements[index], fmt.Sprintf("%s[%d]", prefix, index), out)
	}
}

func collectConfiguredMapValues(node *configSchemaNode, value any, prefix string, out map[string]string) {
	entries, ok := configMapEntries(value)
	if !ok || node.element == nil || node.element.kind == configSchemaScalar {
		out[prefix] = formatConfigDumpValue(prefix, value)

		return
	}

	sort.Slice(entries, func(left int, right int) bool {
		return entries[left].key < entries[right].key
	})

	for _, entry := range entries {
		collectConfiguredConfigDumpValues(node.element, entry.value, joinConfigPath(prefix, entry.key), out)
	}
}

func collectDynamicConfigDumpValues(value any, prefix string, out map[string]string) {
	if out == nil || value == nil {
		return
	}

	switch typed := value.(type) {
	case map[string]any:
		keys := make([]string, 0, len(typed))
		for key := range typed {
			keys = append(keys, key)
		}

		sort.Strings(keys)

		for _, key := range keys {
			collectDynamicConfigDumpValues(typed[key], joinConfigPath(prefix, key), out)
		}
	case map[any]any:
		keys := make([]string, 0, len(typed))
		values := make(map[string]any, len(typed))
		for key, nested := range typed {
			keyStr := fmt.Sprintf("%v", key)
			keys = append(keys, keyStr)
			values[keyStr] = nested
		}

		sort.Strings(keys)

		for _, key := range keys {
			collectDynamicConfigDumpValues(values[key], joinConfigPath(prefix, key), out)
		}
	default:
		out[prefix] = formatConfigDumpValue(prefix, value)
	}
}

func formatConfigDumpValue(path string, value any) string {
	if formatted, ok := formatKnownDumpValue(path, value); ok {
		return formatted
	}

	reflected, dereferencedValue, ok := dereferenceDumpValue(value)
	if !ok {
		return configDumpNullValue
	}

	if formatted, ok := formatKnownDumpValue(path, dereferencedValue); ok {
		return formatted
	}

	return formatReflectedDumpValue(path, reflected, dereferencedValue)
}

func formatKnownDumpValue(path string, value any) (string, bool) {
	if formatted, ok := formatPrimitiveDumpValue(path, value); ok {
		return formatted, true
	}

	if formatted, ok := formatStringerDumpValue(value); ok {
		return formatted, true
	}

	return formatNamedDumpValue(value)
}

func formatSecretDumpValue(path string, value secret.Value) string {
	if value.String() == "" {
		return `""`
	}

	if shouldRedactConfigDumpValue(path, value) {
		return strconv.Quote(redactedConfigValue)
	}

	return strconv.Quote(value.String())
}

func formatPrimitiveDumpValue(path string, value any) (string, bool) {
	switch typed := value.(type) {
	case nil:
		return configDumpNullValue, true
	case string:
		return strconv.Quote(normalizeReflectedStructuredString(path, typed)), true
	case bool:
		return formatConfigDumpBool(typed), true
	case time.Duration:
		return strconv.Quote(typed.String()), true
	case secret.Value:
		return formatSecretDumpValue(path, typed), true
	default:
		return "", false
	}
}

func formatStringerDumpValue(value any) (string, bool) {
	switch typed := value.(type) {
	case ContentSecurityPolicyValue:
		return strconv.Quote(typed.String()), true
	case PermissionsPolicyValue:
		return strconv.Quote(typed.String()), true
	case StrictTransportSecurityValue:
		return strconv.Quote(typed.String()), true
	case Backend:
		return strconv.Quote(typed.String()), true
	case LDAPScope:
		return strconv.Quote(typed.String()), true
	default:
		return "", false
	}
}

func formatNamedDumpValue(value any) (string, bool) {
	switch typed := value.(type) {
	case Verbosity:
		return strconv.Quote(typed.Get()), true
	case Control:
		return strconv.Quote(typed.Get()), true
	case Service:
		return strconv.Quote(typed.Get()), true
	case Protocol:
		return strconv.Quote(typed.Get()), true
	case Feature:
		return strconv.Quote(typed.Get()), true
	case DbgModule:
		return strconv.Quote(typed.Get()), true
	default:
		return "", false
	}
}

func formatReflectedDumpValue(path string, reflected reflect.Value, value any) string {
	switch reflected.Kind() {
	case reflect.String:
		return strconv.Quote(normalizeReflectedStructuredString(path, reflected.String()))
	case reflect.Bool:
		return formatConfigDumpBool(reflected.Bool())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return strconv.FormatInt(reflected.Int(), 10)
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return strconv.FormatUint(reflected.Uint(), 10)
	case reflect.Float32, reflect.Float64:
		return strconv.FormatFloat(reflected.Float(), 'f', -1, 64)
	case reflect.Slice, reflect.Array:
		return formatConfigDumpSequence(path, reflected)
	case reflect.Map:
		return formatConfigDumpMap(path, reflected)
	case reflect.Struct:
		return strconv.Quote(fmt.Sprintf("%v", value))
	default:
		return strconv.Quote(fmt.Sprintf("%v", value))
	}
}

func dereferenceDumpValue(value any) (reflect.Value, any, bool) {
	reflected := reflect.ValueOf(value)
	if !reflected.IsValid() {
		return reflect.Value{}, nil, false
	}

	for reflected.Kind() == reflect.Pointer {
		if reflected.IsNil() {
			return reflect.Value{}, nil, false
		}

		reflected = reflected.Elem()
		value = reflected.Interface()
	}

	return reflected, value, true
}

func formatConfigDumpBool(value bool) string {
	if value {
		return "true"
	}

	return "false"
}

func formatConfigDumpSequence(path string, reflected reflect.Value) string {
	items := make([]string, 0, reflected.Len())
	for index := 0; index < reflected.Len(); index++ {
		items = append(items, formatConfigDumpValue(path, reflected.Index(index).Interface()))
	}

	return "[" + strings.Join(items, ", ") + "]"
}

func formatConfigDumpMap(path string, reflected reflect.Value) string {
	if reflected.Len() == 0 {
		return "{}"
	}

	keys := reflected.MapKeys()
	sort.Slice(keys, func(left int, right int) bool {
		return fmt.Sprintf("%v", keys[left].Interface()) < fmt.Sprintf("%v", keys[right].Interface())
	})

	parts := make([]string, 0, len(keys))
	for _, key := range keys {
		keyString := fmt.Sprintf("%v", key.Interface())
		parts = append(parts, strconv.Quote(keyString)+": "+formatConfigDumpValue(joinConfigPath(path, keyString), reflected.MapIndex(key).Interface()))
	}

	return "{" + strings.Join(parts, ", ") + "}"
}

func shouldRedactConfigDumpValue(path string, value any) bool {
	if printSensitiveConfigValues.Load() {
		return false
	}

	switch typed := value.(type) {
	case secret.Value:
		return !typed.IsZero()
	case string:
		if typed == "" {
			return false
		}
	}

	if path == "identity.saml.key" {
		return true
	}

	switch configPathLeaf(path) {
	case "password", "password_encoded", "password_nonce", "encryption_secret", "bind_pw", "client_secret", "test_password":
		return true
	default:
		return false
	}
}

func configPathLeaf(path string) string {
	if path == "" {
		return ""
	}

	lastDot := strings.LastIndexByte(path, '.')
	if lastDot == -1 {
		return path
	}

	return path[lastDot+1:]
}

func emptyValueForNode(node *configSchemaNode) any {
	if node == nil {
		return nil
	}

	switch node.kind {
	case configSchemaList:
		return []any{}
	case configSchemaMap:
		return map[string]any{}
	default:
		return zeroValueForType(node.typeInfo)
	}
}

func zeroValueForType(typ reflect.Type) any {
	if typ == nil {
		return nil
	}

	baseType := typ
	for baseType.Kind() == reflect.Pointer {
		baseType = baseType.Elem()
	}

	return reflect.Zero(baseType).Interface()
}

func slicesSortedKeys[K ~string, V any](input map[K]V) []K {
	keys := make([]K, 0, len(input))
	for key := range input {
		keys = append(keys, key)
	}

	slices.Sort(keys)

	return keys
}

func configDumpDefaultProviders() map[string]configDumpValueProvider {
	providers := make(map[string]configDumpValueProvider)
	addConfigDumpDefaultProviders(providers, configDumpRuntimeDefaults())
	addConfigDumpDefaultProviders(providers, configDumpRedisDefaults())
	addConfigDumpDefaultProviders(providers, configDumpIdentityDefaults())
	addConfigDumpDefaultProviders(providers, configDumpBruteForceDefaults())
	addConfigDumpDefaultProviders(providers, configDumpLDAPDefaults())

	return providers
}

func addConfigDumpDefaultProviders(target map[string]configDumpValueProvider, providers map[string]configDumpValueProvider) {
	for key, provider := range providers {
		target[key] = provider
	}
}

func configDumpRuntimeDefaults() map[string]configDumpValueProvider {
	return map[string]configDumpValueProvider{
		"developer_mode":                                 func() any { return false },
		"runtime.http.middlewares.logging":               func() any { return true },
		"runtime.http.middlewares.limit":                 func() any { return true },
		"runtime.http.middlewares.recovery":              func() any { return true },
		"runtime.http.middlewares.trusted_proxies":       func() any { return true },
		"runtime.http.middlewares.request_decompression": func() any { return true },
		"runtime.http.middlewares.response_compression":  func() any { return true },
		"runtime.http.middlewares.metrics":               func() any { return true },
		"runtime.http.middlewares.rate":                  func() any { return true },
		"runtime.listen.tls.min_tls_version":             func() any { return "TLS1.2" },
		"runtime.http.timeouts.redis_read":               func() any { return 1 * time.Second },
		"runtime.http.timeouts.redis_write":              func() any { return 2 * time.Second },
		"runtime.http.timeouts.ldap_search":              func() any { return 3 * time.Second },
		"runtime.http.timeouts.ldap_bind":                func() any { return 3 * time.Second },
		"runtime.http.timeouts.ldap_modify":              func() any { return 5 * time.Second },
		"runtime.http.timeouts.lua_backend":              func() any { return 5 * time.Second },
		"runtime.http.timeouts.lua_script":               func() any { return 30 * time.Second },
	}
}

func configDumpRedisDefaults() map[string]configDumpValueProvider {
	return map[string]configDumpValueProvider{
		"storage.redis.pool_timeout":                         func() any { return 1 * time.Second },
		"storage.redis.dial_timeout":                         func() any { return 5 * time.Second },
		"storage.redis.read_timeout":                         func() any { return 1 * time.Second },
		"storage.redis.write_timeout":                        func() any { return 1 * time.Second },
		"storage.redis.pool_fifo":                            func() any { return true },
		"storage.redis.conn_max_idle_time":                   func() any { return 90 * time.Second },
		"storage.redis.max_retries":                          func() any { return 1 },
		"storage.redis.protocol":                             func() any { return 2 },
		"storage.redis.prefix":                               func() any { return "nt:" },
		"storage.redis.batching.max_batch_size":              func() any { return 16 },
		"storage.redis.batching.max_wait":                    func() any { return 2 * time.Millisecond },
		"storage.redis.batching.queue_capacity":              func() any { return 8192 },
		"storage.redis.batching.pipeline_timeout":            func() any { return 5 * time.Second },
		"storage.redis.account_local_cache.ttl":              func() any { return 60 * time.Second },
		"storage.redis.account_local_cache.shards":           func() any { return 32 },
		"storage.redis.account_local_cache.cleanup_interval": func() any { return 10 * time.Minute },
	}
}

func configDumpIdentityDefaults() map[string]configDumpValueProvider {
	return map[string]configDumpValueProvider{
		"identity.frontend.security_headers.enabled":          func() any { return true },
		"identity.mfa.webauthn.resident_key":                  func() any { return defaultWebAuthnResidentKey },
		"identity.mfa.webauthn.user_verification":             func() any { return defaultWebAuthnUserVerification },
		"identity.oidc.access_token_type":                     func() any { return "jwt" },
		"identity.oidc.key_rotation_interval":                 func() any { return 24 * time.Hour },
		"identity.oidc.key_max_age":                           func() any { return 7 * 24 * time.Hour },
		"identity.oidc.tokens.default_access_token_lifetime":  func() any { return 1 * time.Hour },
		"identity.oidc.tokens.default_refresh_token_lifetime": func() any { return 30 * 24 * time.Hour },
		"identity.oidc.tokens.revoke_refresh_token":           func() any { return true },
		"identity.oidc.consent.ttl":                           func() any { return definitions.OIDCConsentDefaultTTL },
		"identity.oidc.consent.mode":                          func() any { return OIDCConsentModeAllOrNothing },
		"identity.oidc.device_flow.code_expiry":               func() any { return definitions.OIDCDeviceCodeDefaultExpiry },
		"identity.oidc.device_flow.polling_interval":          func() any { return definitions.OIDCDeviceCodeDefaultInterval },
		"identity.oidc.device_flow.user_code_length":          func() any { return definitions.OIDCDeviceCodeDefaultUserCodeLength },
		"identity.saml.signature_method":                      func() any { return defaultSAMLSignatureMethod },
		"identity.saml.default_expire_time":                   func() any { return 1 * time.Hour },
		"identity.saml.name_id_format":                        func() any { return "urn:oasis:names:tc:SAML:2.0:nameid-format:persistent" },
		"identity.saml.slo.enabled":                           func() any { return defaultSLOEnabled },
		"identity.saml.slo.front_channel_enabled":             func() any { return defaultSLOFrontChannel },
		"identity.saml.slo.back_channel_enabled":              func() any { return defaultSLOBackChannel },
		"identity.saml.slo.request_timeout":                   func() any { return defaultSLORequestTimeout },
		"identity.saml.slo.max_participants":                  func() any { return defaultSLOMaxParticipants },
		"identity.saml.slo.back_channel_max_retries":          func() any { return defaultSLOBackChannelRetries },
	}
}

func configDumpBruteForceDefaults() map[string]configDumpValueProvider {
	return map[string]configDumpValueProvider{
		"auth.controls.brute_force.rwp_window":                func() any { return 15 * time.Minute },
		"auth.controls.brute_force.rwp_allowed_unique_hashes": func() any { return uint(3) },
		"auth.controls.brute_force.tolerate_percent":          func() any { return uint8(10) },
		"auth.controls.brute_force.min_tolerate_percent":      func() any { return uint8(10) },
		"auth.controls.brute_force.max_tolerate_percent":      func() any { return uint8(50) },
		"auth.controls.brute_force.scale_factor":              func() any { return 1.0 },
	}
}

func configDumpLDAPDefaults() map[string]configDumpValueProvider {
	return map[string]configDumpValueProvider{
		"auth.backends.ldap.default.number_of_workers":     func() any { return definitions.DefaultNumberOfWorkers },
		"auth.backends.ldap.default.retry_max":             func() any { return 2 },
		"auth.backends.ldap.default.retry_base":            func() any { return 200 * time.Millisecond },
		"auth.backends.ldap.default.retry_max_backoff":     func() any { return 2 * time.Second },
		"auth.backends.ldap.default.cb_failure_threshold":  func() any { return 5 },
		"auth.backends.ldap.default.cb_cooldown":           func() any { return 30 * time.Second },
		"auth.backends.ldap.default.cb_half_open_max":      func() any { return 1 },
		"auth.backends.ldap.default.health_check_interval": func() any { return 10 * time.Second },
		"auth.backends.ldap.default.health_check_timeout":  func() any { return 1500 * time.Millisecond },
		"auth.backends.ldap.default.negative_cache_ttl":    func() any { return 20 * time.Second },
		"auth.backends.ldap.default.membership_cache_ttl":  func() any { return 2 * time.Minute },
		"auth.backends.ldap.default.cache_max_entries":     func() any { return 5000 },
		"auth.backends.ldap.default.cache_impl":            func() any { return "ttl" },
	}
}
