// Copyright (C) 2026 Christian Rößner
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <https://www.gnu.org/licenses/>.

package config

import (
	"encoding/json"
	"strings"
	"testing"

	"github.com/pelletier/go-toml/v2"
	"gopkg.in/yaml.v3"
)

func TestRenderDefaultConfigDump_IncludesKnownDefaults(t *testing.T) {
	SetConfigDumpVersion("3.0.0-test")
	t.Cleanup(func() {
		SetConfigDumpVersion("")
	})

	output, err := RenderDefaultConfigDump()
	if err != nil {
		t.Fatalf("RenderDefaultConfigDump() error = %v", err)
	}

	expectedHeader := "# Nauthilus canonical default configuration\n# Generated by `nauthilus -d`.\n# Version: 3.0.0-test\n"
	if !strings.HasPrefix(output, expectedHeader) {
		t.Fatalf("RenderDefaultConfigDump() missing header %q in output %q", expectedHeader, output)
	}

	expectedLines := []string{
		`runtime.http.middlewares.logging = true`,
		`runtime.listen.tls.min_tls_version = "TLS1.2"`,
		`runtime.http.timeouts.lua_script = "30s"`,
		`identity.oidc.tokens.revoke_refresh_token = true`,
	}

	for _, expected := range expectedLines {
		if !strings.Contains(output, expected) {
			t.Fatalf("RenderDefaultConfigDump() missing line %q", expected)
		}
	}
}

func TestRenderNonDefaultConfigDump_SuppressesDefaultsAndKeepsChanges(t *testing.T) {
	SetConfigDumpVersion("3.0.0-test")
	t.Cleanup(func() {
		SetConfigDumpVersion("")
	})

	settings := map[string]any{
		"developer_mode": false,
		"runtime": map[string]any{
			"http": map[string]any{
				"middlewares": map[string]any{
					"logging": true,
					"limit":   false,
				},
			},
			"listen": map[string]any{
				"tls": map[string]any{
					"min_tls_version": "TLS1.3",
				},
			},
		},
	}

	output, err := RenderNonDefaultConfigDump(settings)
	if err != nil {
		t.Fatalf("RenderNonDefaultConfigDump() error = %v", err)
	}

	expectedHeader := "# Nauthilus canonical non-default configuration\n# Generated by `nauthilus -n`.\n# Version: 3.0.0-test\n"
	if !strings.HasPrefix(output, expectedHeader) {
		t.Fatalf("RenderNonDefaultConfigDump() missing header %q in output %q", expectedHeader, output)
	}

	if strings.Contains(output, `runtime.http.middlewares.logging = true`) {
		t.Fatalf("RenderNonDefaultConfigDump() unexpectedly kept default-valued line: %q", output)
	}

	if strings.Contains(output, `developer_mode = false`) {
		t.Fatalf("RenderNonDefaultConfigDump() unexpectedly kept default developer_mode: %q", output)
	}

	expectedLines := []string{
		`runtime.http.middlewares.limit = false`,
		`runtime.listen.tls.min_tls_version = "TLS1.3"`,
	}

	for _, expected := range expectedLines {
		if !strings.Contains(output, expected) {
			t.Fatalf("RenderNonDefaultConfigDump() missing line %q", expected)
		}
	}
}

func TestRenderNonDefaultConfigDump_KeepsSupportedDynamicCustomScopeKeys(t *testing.T) {
	settings := map[string]any{
		"identity": map[string]any{
			"oidc": map[string]any{
				"custom_scopes": []any{
					map[string]any{
						"name":           "profile",
						"description":    "Profile",
						"description_de": "Profil",
						"claims": []any{
							map[string]any{"name": "name", "type": "string"},
						},
					},
				},
			},
		},
	}

	output, err := RenderNonDefaultConfigDump(settings)
	if err != nil {
		t.Fatalf("RenderNonDefaultConfigDump() error = %v", err)
	}

	expected := `identity.oidc.custom_scopes[0].description_de = "Profil"`
	if !strings.Contains(output, expected) {
		t.Fatalf("RenderNonDefaultConfigDump() missing dynamic line %q", expected)
	}
}

func TestRenderNonDefaultConfigDump_RedactsSensitiveValuesByDefault(t *testing.T) {
	SetConfigDumpPrintSensitiveValues(false)

	settings := map[string]any{
		"auth": map[string]any{
			"request": map[string]any{
				"headers": map[string]any{
					"password":         "super-secret",
					"password_encoded": "c3VwZXItc2VjcmV0",
				},
			},
		},
		"identity": map[string]any{
			"saml": map[string]any{
				"key": "private-key",
			},
		},
	}

	output, err := RenderNonDefaultConfigDump(settings)
	if err != nil {
		t.Fatalf("RenderNonDefaultConfigDump() error = %v", err)
	}

	expectedLines := []string{
		`auth.request.headers.password = "***REDACTED***"`,
		`auth.request.headers.password_encoded = "***REDACTED***"`,
		`identity.saml.key = "***REDACTED***"`,
	}

	for _, expected := range expectedLines {
		if !strings.Contains(output, expected) {
			t.Fatalf("RenderNonDefaultConfigDump() missing redacted line %q", expected)
		}
	}

	if strings.Contains(output, "super-secret") || strings.Contains(output, "private-key") {
		t.Fatalf("RenderNonDefaultConfigDump() unexpectedly exposed sensitive output: %q", output)
	}
}

func TestRenderNonDefaultConfigDump_PrintsSensitiveValuesWhenEnabled(t *testing.T) {
	SetConfigDumpPrintSensitiveValues(true)
	t.Cleanup(func() {
		SetConfigDumpPrintSensitiveValues(false)
	})

	settings := map[string]any{
		"auth": map[string]any{
			"request": map[string]any{
				"headers": map[string]any{
					"password": "super-secret",
				},
			},
		},
	}

	output, err := RenderNonDefaultConfigDump(settings)
	if err != nil {
		t.Fatalf("RenderNonDefaultConfigDump() error = %v", err)
	}

	expected := `auth.request.headers.password = "super-secret"`
	if !strings.Contains(output, expected) {
		t.Fatalf("RenderNonDefaultConfigDump() missing sensitive line %q", expected)
	}

	if strings.Contains(output, redactedConfigValue) {
		t.Fatalf("RenderNonDefaultConfigDump() unexpectedly redacted output: %q", output)
	}
}

func TestParseDumpFormat(t *testing.T) {
	testCases := []struct {
		name    string
		input   string
		want    DumpFormat
		wantErr bool
	}{
		{name: "default empty", input: "", want: DumpFormatCanonical},
		{name: "canonical", input: "canonical", want: DumpFormatCanonical},
		{name: "yaml uppercase", input: "YAML", want: DumpFormatYAML},
		{name: "json padded", input: " json ", want: DumpFormatJSON},
		{name: "toml", input: "toml", want: DumpFormatTOML},
		{name: "invalid", input: "ini", wantErr: true},
	}

	for _, testCase := range testCases {
		t.Run(testCase.name, func(t *testing.T) {
			got, err := ParseDumpFormat(testCase.input)
			if testCase.wantErr {
				if err == nil {
					t.Fatal("ParseDumpFormat() error = nil, want error")
				}

				return
			}

			if err != nil {
				t.Fatalf("ParseDumpFormat() error = %v", err)
			}

			if got != testCase.want {
				t.Fatalf("ParseDumpFormat() = %q, want %q", got, testCase.want)
			}
		})
	}
}

func TestRenderNonDefaultConfigDumpWithStructuredFormats_RoundTrips(t *testing.T) {
	SetConfigDumpVersion("3.0.0-test")
	t.Cleanup(func() {
		SetConfigDumpVersion("")
		SetConfigDumpPrintSensitiveValues(false)
	})
	SetConfigDumpPrintSensitiveValues(true)

	settings := map[string]any{
		"runtime": map[string]any{
			"instance_name": "mini",
			"http": map[string]any{
				"middlewares": map[string]any{
					"limit": false,
				},
			},
		},
		"storage": map[string]any{
			"redis": map[string]any{
				"primary": map[string]any{
					"address": "localhost:6379",
				},
				"password_nonce":    "nonce-secret-1234",
				"encryption_secret": "redis-secret-1234",
			},
		},
		"identity": map[string]any{
			"session": map[string]any{
				"remember_me_ttl": "24h",
			},
		},
	}

	for _, format := range []DumpFormat{DumpFormatYAML, DumpFormatJSON, DumpFormatTOML} {
		runStructuredRoundTripCase(t, format, settings)
	}
}

func TestRenderDefaultConfigDumpWithStructuredFormats_ProducesLoadableDocuments(t *testing.T) {
	SetConfigDumpVersion("3.0.0-test")
	t.Cleanup(func() {
		SetConfigDumpVersion("")
	})

	for _, format := range []DumpFormat{
		DumpFormatYAML,
		DumpFormatJSON,
		DumpFormatTOML,
	} {
		t.Run(string(format), func(t *testing.T) {
			output, err := RenderDefaultConfigDumpWithFormat(format)
			if err != nil {
				t.Fatalf("RenderDefaultConfigDumpWithFormat() error = %v", err)
			}

			parsed := parseStructuredConfigDumpOutput(t, format, output)
			assertStructuredDumpValue(t, parsed, []string{"runtime", "http", "middlewares", "logging"}, true)
			assertStructuredDumpValue(t, parsed, []string{"runtime", "listen", "tls", "min_tls_version"}, "TLS1.2")
		})
	}
}

func runStructuredRoundTripCase(t *testing.T, format DumpFormat, settings map[string]any) {
	t.Helper()

	t.Run(string(format), func(t *testing.T) {
		output, err := RenderNonDefaultConfigDumpWithFormat(settings, format)
		if err != nil {
			t.Fatalf("RenderNonDefaultConfigDumpWithFormat() error = %v", err)
		}

		parsed := parseStructuredConfigDumpOutput(t, format, output)
		assertStructuredDumpRoundTripValues(t, parsed)
		assertStructuredDumpVersionHeader(t, format, output)
	})
}

func assertStructuredDumpRoundTripValues(t *testing.T, parsed map[string]any) {
	t.Helper()

	assertStructuredDumpValue(t, parsed, []string{"runtime", "instance_name"}, "mini")
	assertStructuredDumpValue(t, parsed, []string{"runtime", "http", "middlewares", "limit"}, false)
	assertStructuredDumpValue(t, parsed, []string{"storage", "redis", "primary", "address"}, "localhost:6379")
	assertStructuredDumpValue(t, parsed, []string{"storage", "redis", "password_nonce"}, "nonce-secret-1234")
	assertStructuredDumpValue(t, parsed, []string{"identity", "session", "remember_me_ttl"}, "24h")
}

func assertStructuredDumpVersionHeader(t *testing.T, format DumpFormat, output string) {
	t.Helper()

	switch format {
	case DumpFormatYAML, DumpFormatTOML:
		if !strings.Contains(output, "# Version: 3.0.0-test") {
			t.Fatalf("structured output missing version header: %q", output)
		}
	case DumpFormatJSON:
		if strings.Contains(output, "# Version: 3.0.0-test") {
			t.Fatalf("json output must not contain comment header: %q", output)
		}
	}
}

func parseStructuredConfigDumpOutput(t *testing.T, format DumpFormat, output string) map[string]any {
	t.Helper()

	document := stripStructuredConfigDumpHeader(output)
	parsed := make(map[string]any)

	switch format {
	case DumpFormatYAML:
		if err := yaml.Unmarshal([]byte(document), &parsed); err != nil {
			t.Fatalf("yaml unmarshal failed: %v\noutput=%s", err, output)
		}
	case DumpFormatJSON:
		if err := json.Unmarshal([]byte(document), &parsed); err != nil {
			t.Fatalf("json unmarshal failed: %v\noutput=%s", err, output)
		}
	case DumpFormatTOML:
		if err := toml.Unmarshal([]byte(document), &parsed); err != nil {
			t.Fatalf("toml unmarshal failed: %v\noutput=%s", err, output)
		}
	default:
		t.Fatalf("unsupported format %q", format)
	}

	return parsed
}

func stripStructuredConfigDumpHeader(output string) string {
	lines := strings.Split(output, "\n")
	start := 0

	for start < len(lines) {
		line := strings.TrimSpace(lines[start])
		if line == "" || strings.HasPrefix(line, "#") {
			start++

			continue
		}

		break
	}

	return strings.Join(lines[start:], "\n")
}

func assertStructuredDumpValue(t *testing.T, root map[string]any, path []string, expected any) {
	t.Helper()

	current := any(root)
	for _, segment := range path {
		mapped, ok := current.(map[string]any)
		if !ok {
			t.Fatalf("path %v does not resolve to a map at segment %q (got %T)", path, segment, current)
		}

		next, ok := mapped[segment]
		if !ok {
			t.Fatalf("path %v missing segment %q", path, segment)
		}

		current = next
	}

	switch want := expected.(type) {
	case bool:
		got, ok := current.(bool)
		if !ok || got != want {
			t.Fatalf("path %v = %#v (%T), want %v", path, current, current, want)
		}
	case string:
		got, ok := current.(string)
		if !ok || got != want {
			t.Fatalf("path %v = %#v (%T), want %q", path, current, current, want)
		}
	default:
		if current != expected {
			t.Fatalf("path %v = %#v, want %#v", path, current, expected)
		}
	}
}
