---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by croessner.
--- DateTime: 02.07.24 13:26
---

local crypto = require("crypto")
local json = require("json")

------@return void
function nauthilus_run_callback()
    ---@type table headers
    local headers = nauthilus.get_all_http_request_headers()

    ---@type table request
    local body = nauthilus.get_http_request_body()

    ---@type boolean match_ct
    local match_ct = false

    ---@param header_name string
    ---@param header_values table
    for header_name, header_values in pairs(headers) do
        if header_name == "content-type" then
            if header_values[1] ~= "application/json" then
                return
            end

            match_ct = true
        end
    end

    if match_ct then
        ---@type table body_table
        ---@type string err_jdec
        local body_table, err_jdec = json.decode(body)
        if err_jdec ~= nil then
            return
        end

        if type(body_table) ~= "table" then
            return
        end

        ---@type table result
        local result = {}

        result.state = "client disconnected"
        result.dovecot_session = "unknown"

        ---@param k table
        ---@param v any
        for k, v in pairs(body_table) do
            if k == "categories" then
                if type(v) == "table" then
                    ---@param category table
                    for _, category in ipairs(v) do
                        if category == "service:imap" or category == "service:lmtp" then
                            result.category = category
                        end
                    end
                end
            elseif k == "start_time" then
                if type(v) == "string" then
                    result.start_time = v
                end
            elseif k == "end_time" then
                if type(v) == "string" then
                    result.end_time = v
                end
            elseif k == "fields" then
                if type(v) == "table" then
                    ---@param field_name string
                    ---@param field_value string
                    for field_name, field_value in pairs(v) do
                        if field_name == "user" then
                            result.user = field_value
                        elseif field_name == "session" then
                            result.dovecot_session = field_value
                        elseif field_name == "remote_ip" then
                            result.remote_ip = field_value
                        elseif field_name == "remote_port" then
                            result.remote_port = field_value
                        end
                    end
                end
            end
        end

        if result.category == "service:imap" or result.category == "service:lmtp" then
            if result.dovecot_session ~= "unknown" then
                -- Cleanup dovecot session
                ---@type string deleted
                ---@type string err_redis_hdel
                local deleted, err_redis_hdel = nauthilus.redis_hdel("ntc:DS:" .. crypto.md5(result.user), result.dovecot_session)
                if err_redis_hdel ~= nil then
                    result.removed_session_failure = err_redis_hdel
                else
                    result.removed_session = deleted
                end
            end

            ---@type string result_json
            ---@type string err_jenc
            local result_json, err_jenc = json.encode(result)
            if err_jenc ~= nil then
                return
            end

            print(result_json)
        end
    end
end
