// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.36.0
// source: api/policy/v1/policy.proto

package policyv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Effect is the closed evaluated Policy result set.
type Effect int32

const (
	Effect_EFFECT_UNSPECIFIED    Effect = 0
	Effect_EFFECT_PERMIT         Effect = 1
	Effect_EFFECT_DENY           Effect = 2
	Effect_EFFECT_NOT_APPLICABLE Effect = 3
	Effect_EFFECT_INDETERMINATE  Effect = 4
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "EFFECT_UNSPECIFIED",
		1: "EFFECT_PERMIT",
		2: "EFFECT_DENY",
		3: "EFFECT_NOT_APPLICABLE",
		4: "EFFECT_INDETERMINATE",
	}
	Effect_value = map[string]int32{
		"EFFECT_UNSPECIFIED":    0,
		"EFFECT_PERMIT":         1,
		"EFFECT_DENY":           2,
		"EFFECT_NOT_APPLICABLE": 3,
		"EFFECT_INDETERMINATE":  4,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_api_policy_v1_policy_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_api_policy_v1_policy_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

// DecisionRequest is the public unary Policy evaluation request.
type DecisionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       string                 `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	RequestId     string                 `protobuf:"bytes,2,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Target        *Target                `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
	Subject       *Entity                `protobuf:"bytes,4,opt,name=subject,proto3" json:"subject,omitempty"`
	Resource      *Entity                `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	Environment   *Environment           `protobuf:"bytes,6,opt,name=environment,proto3" json:"environment,omitempty"`
	Attributes    map[string]*Value      `protobuf:"bytes,7,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Options       *EvaluationOptions     `protobuf:"bytes,8,opt,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionRequest) Reset() {
	*x = DecisionRequest{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionRequest) ProtoMessage() {}

func (x *DecisionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionRequest.ProtoReflect.Descriptor instead.
func (*DecisionRequest) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{0}
}

func (x *DecisionRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *DecisionRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *DecisionRequest) GetTarget() *Target {
	if x != nil {
		return x.Target
	}
	return nil
}

func (x *DecisionRequest) GetSubject() *Entity {
	if x != nil {
		return x.Subject
	}
	return nil
}

func (x *DecisionRequest) GetResource() *Entity {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *DecisionRequest) GetEnvironment() *Environment {
	if x != nil {
		return x.Environment
	}
	return nil
}

func (x *DecisionRequest) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *DecisionRequest) GetOptions() *EvaluationOptions {
	if x != nil {
		return x.Options
	}
	return nil
}

// Target identifies the namespace and action selected for evaluation.
type Target struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Target) Reset() {
	*x = Target{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Target) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Target) ProtoMessage() {}

func (x *Target) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Target.ProtoReflect.Descriptor instead.
func (*Target) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{1}
}

func (x *Target) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Target) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// Entity carries caller-asserted subject or resource fields.
type Entity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	Attributes    map[string]*Value      `protobuf:"bytes,3,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entity) Reset() {
	*x = Entity{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entity) ProtoMessage() {}

func (x *Entity) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entity.ProtoReflect.Descriptor instead.
func (*Entity) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{2}
}

func (x *Entity) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Entity) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Entity) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// Environment carries caller-asserted request environment fields.
type Environment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Service       string                 `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Instance      string                 `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Protocol      string                 `protobuf:"bytes,3,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Attributes    map[string]*Value      `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Environment) Reset() {
	*x = Environment{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Environment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Environment) ProtoMessage() {}

func (x *Environment) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Environment.ProtoReflect.Descriptor instead.
func (*Environment) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{3}
}

func (x *Environment) GetService() string {
	if x != nil {
		return x.Service
	}
	return ""
}

func (x *Environment) GetInstance() string {
	if x != nil {
		return x.Instance
	}
	return ""
}

func (x *Environment) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *Environment) GetAttributes() map[string]*Value {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// EvaluationOptions contains the sole public evaluation option.
type EvaluationOptions struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	IncludeDiagnostics bool                   `protobuf:"varint,1,opt,name=include_diagnostics,json=includeDiagnostics,proto3" json:"include_diagnostics,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *EvaluationOptions) Reset() {
	*x = EvaluationOptions{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EvaluationOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EvaluationOptions) ProtoMessage() {}

func (x *EvaluationOptions) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EvaluationOptions.ProtoReflect.Descriptor instead.
func (*EvaluationOptions) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{4}
}

func (x *EvaluationOptions) GetIncludeDiagnostics() bool {
	if x != nil {
		return x.IncludeDiagnostics
	}
	return false
}

// StringList owns the string-list branch of Value's closed oneof.
type StringList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StringList) Reset() {
	*x = StringList{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{5}
}

func (x *StringList) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// RecordList owns one ordered, schema-bound correlated resource collection.
type RecordList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Records       []*Record              `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordList) Reset() {
	*x = RecordList{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordList) ProtoMessage() {}

func (x *RecordList) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordList.ProtoReflect.Descriptor instead.
func (*RecordList) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{6}
}

func (x *RecordList) GetRecords() []*Record {
	if x != nil {
		return x.Records
	}
	return nil
}

// Record owns ordered fields without map-induced duplicate-name ambiguity.
type Record struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*RecordField         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Record) Reset() {
	*x = Record{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Record) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Record) ProtoMessage() {}

func (x *Record) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Record.ProtoReflect.Descriptor instead.
func (*Record) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{7}
}

func (x *Record) GetFields() []*RecordField {
	if x != nil {
		return x.Fields
	}
	return nil
}

// RecordField binds one exact local name to one non-recursive leaf value.
type RecordField struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         *RecordFieldValue      `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordField) Reset() {
	*x = RecordField{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordField) ProtoMessage() {}

func (x *RecordField) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordField.ProtoReflect.Descriptor instead.
func (*RecordField) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{8}
}

func (x *RecordField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RecordField) GetValue() *RecordFieldValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// RecordFieldValue carries one scalar, string-list, bytes, or timestamp member.
type RecordFieldValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*RecordFieldValue_String_
	//	*RecordFieldValue_Boolean
	//	*RecordFieldValue_Integer
	//	*RecordFieldValue_Double
	//	*RecordFieldValue_Strings
	//	*RecordFieldValue_Bytes
	//	*RecordFieldValue_Timestamp
	Kind          isRecordFieldValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordFieldValue) Reset() {
	*x = RecordFieldValue{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordFieldValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordFieldValue) ProtoMessage() {}

func (x *RecordFieldValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordFieldValue.ProtoReflect.Descriptor instead.
func (*RecordFieldValue) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{9}
}

func (x *RecordFieldValue) GetKind() isRecordFieldValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *RecordFieldValue) GetString_() string {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *RecordFieldValue) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *RecordFieldValue) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *RecordFieldValue) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *RecordFieldValue) GetStrings() *StringList {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Strings); ok {
			return x.Strings
		}
	}
	return nil
}

func (x *RecordFieldValue) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *RecordFieldValue) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*RecordFieldValue_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isRecordFieldValue_Kind interface {
	isRecordFieldValue_Kind()
}

type RecordFieldValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type RecordFieldValue_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type RecordFieldValue_Integer struct {
	Integer int64 `protobuf:"zigzag64,3,opt,name=integer,proto3,oneof"`
}

type RecordFieldValue_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof"`
}

type RecordFieldValue_Strings struct {
	Strings *StringList `protobuf:"bytes,5,opt,name=strings,proto3,oneof"`
}

type RecordFieldValue_Bytes struct {
	Bytes []byte `protobuf:"bytes,6,opt,name=bytes,proto3,oneof"`
}

type RecordFieldValue_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof"`
}

func (*RecordFieldValue_String_) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Boolean) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Integer) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Double) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Strings) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Bytes) isRecordFieldValue_Kind() {}

func (*RecordFieldValue_Timestamp) isRecordFieldValue_Kind() {}

// Value carries exactly one typed public value member after protobuf normalization.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_String_
	//	*Value_Boolean
	//	*Value_Integer
	//	*Value_Double
	//	*Value_Strings
	//	*Value_Bytes
	//	*Value_Timestamp
	//	*Value_Records
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{10}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetString_() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *Value) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *Value) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *Value) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *Value) GetStrings() *StringList {
	if x != nil {
		if x, ok := x.Kind.(*Value_Strings); ok {
			return x.Strings
		}
	}
	return nil
}

func (x *Value) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *Value) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Value_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

func (x *Value) GetRecords() *RecordList {
	if x != nil {
		if x, ok := x.Kind.(*Value_Records); ok {
			return x.Records
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type Value_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type Value_Integer struct {
	Integer int64 `protobuf:"zigzag64,3,opt,name=integer,proto3,oneof"`
}

type Value_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof"`
}

type Value_Strings struct {
	Strings *StringList `protobuf:"bytes,5,opt,name=strings,proto3,oneof"`
}

type Value_Bytes struct {
	Bytes []byte `protobuf:"bytes,6,opt,name=bytes,proto3,oneof"`
}

type Value_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof"`
}

type Value_Records struct {
	Records *RecordList `protobuf:"bytes,8,opt,name=records,proto3,oneof"`
}

func (*Value_String_) isValue_Kind() {}

func (*Value_Boolean) isValue_Kind() {}

func (*Value_Integer) isValue_Kind() {}

func (*Value_Double) isValue_Kind() {}

func (*Value_Strings) isValue_Kind() {}

func (*Value_Bytes) isValue_Kind() {}

func (*Value_Timestamp) isValue_Kind() {}

func (*Value_Records) isValue_Kind() {}

// ResponseValue carries one non-record value in diagnostics and return-only effects.
type ResponseValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*ResponseValue_String_
	//	*ResponseValue_Boolean
	//	*ResponseValue_Integer
	//	*ResponseValue_Double
	//	*ResponseValue_Strings
	//	*ResponseValue_Bytes
	//	*ResponseValue_Timestamp
	Kind          isResponseValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResponseValue) Reset() {
	*x = ResponseValue{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResponseValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResponseValue) ProtoMessage() {}

func (x *ResponseValue) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResponseValue.ProtoReflect.Descriptor instead.
func (*ResponseValue) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{11}
}

func (x *ResponseValue) GetKind() isResponseValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *ResponseValue) GetString_() string {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_String_); ok {
			return x.String_
		}
	}
	return ""
}

func (x *ResponseValue) GetBoolean() bool {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Boolean); ok {
			return x.Boolean
		}
	}
	return false
}

func (x *ResponseValue) GetInteger() int64 {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Integer); ok {
			return x.Integer
		}
	}
	return 0
}

func (x *ResponseValue) GetDouble() float64 {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Double); ok {
			return x.Double
		}
	}
	return 0
}

func (x *ResponseValue) GetStrings() *StringList {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Strings); ok {
			return x.Strings
		}
	}
	return nil
}

func (x *ResponseValue) GetBytes() []byte {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Bytes); ok {
			return x.Bytes
		}
	}
	return nil
}

func (x *ResponseValue) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*ResponseValue_Timestamp); ok {
			return x.Timestamp
		}
	}
	return nil
}

type isResponseValue_Kind interface {
	isResponseValue_Kind()
}

type ResponseValue_String_ struct {
	String_ string `protobuf:"bytes,1,opt,name=string,proto3,oneof"`
}

type ResponseValue_Boolean struct {
	Boolean bool `protobuf:"varint,2,opt,name=boolean,proto3,oneof"`
}

type ResponseValue_Integer struct {
	Integer int64 `protobuf:"zigzag64,3,opt,name=integer,proto3,oneof"`
}

type ResponseValue_Double struct {
	Double float64 `protobuf:"fixed64,4,opt,name=double,proto3,oneof"`
}

type ResponseValue_Strings struct {
	Strings *StringList `protobuf:"bytes,5,opt,name=strings,proto3,oneof"`
}

type ResponseValue_Bytes struct {
	Bytes []byte `protobuf:"bytes,6,opt,name=bytes,proto3,oneof"`
}

type ResponseValue_Timestamp struct {
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp,proto3,oneof"`
}

func (*ResponseValue_String_) isResponseValue_Kind() {}

func (*ResponseValue_Boolean) isResponseValue_Kind() {}

func (*ResponseValue_Integer) isResponseValue_Kind() {}

func (*ResponseValue_Double) isResponseValue_Kind() {}

func (*ResponseValue_Strings) isResponseValue_Kind() {}

func (*ResponseValue_Bytes) isResponseValue_Kind() {}

func (*ResponseValue_Timestamp) isResponseValue_Kind() {}

// DecisionResponse is the complete successful application decision result.
type DecisionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DecisionId    string                 `protobuf:"bytes,1,opt,name=decision_id,json=decisionId,proto3" json:"decision_id,omitempty"`
	Effect        Effect                 `protobuf:"varint,2,opt,name=effect,proto3,enum=nauthilus.policy.v1.Effect" json:"effect,omitempty"`
	Status        *Status                `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Obligations   []*Obligation          `protobuf:"bytes,4,rep,name=obligations,proto3" json:"obligations,omitempty"`
	Advice        []*Advice              `protobuf:"bytes,5,rep,name=advice,proto3" json:"advice,omitempty"`
	Diagnostics   *Diagnostics           `protobuf:"bytes,6,opt,name=diagnostics,proto3" json:"diagnostics,omitempty"`
	RequestId     string                 `protobuf:"bytes,7,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecisionResponse) Reset() {
	*x = DecisionResponse{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecisionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecisionResponse) ProtoMessage() {}

func (x *DecisionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecisionResponse.ProtoReflect.Descriptor instead.
func (*DecisionResponse) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{12}
}

func (x *DecisionResponse) GetDecisionId() string {
	if x != nil {
		return x.DecisionId
	}
	return ""
}

func (x *DecisionResponse) GetEffect() Effect {
	if x != nil {
		return x.Effect
	}
	return Effect_EFFECT_UNSPECIFIED
}

func (x *DecisionResponse) GetStatus() *Status {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *DecisionResponse) GetObligations() []*Obligation {
	if x != nil {
		return x.Obligations
	}
	return nil
}

func (x *DecisionResponse) GetAdvice() []*Advice {
	if x != nil {
		return x.Advice
	}
	return nil
}

func (x *DecisionResponse) GetDiagnostics() *Diagnostics {
	if x != nil {
		return x.Diagnostics
	}
	return nil
}

func (x *DecisionResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

// Status carries public result metadata for an evaluated decision.
type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          string                 `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Details       []*ValidationDetail    `protobuf:"bytes,3,rep,name=details,proto3" json:"details,omitempty"`
	Retryable     bool                   `protobuf:"varint,4,opt,name=retryable,proto3" json:"retryable,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{13}
}

func (x *Status) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *Status) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *Status) GetDetails() []*ValidationDetail {
	if x != nil {
		return x.Details
	}
	return nil
}

func (x *Status) GetRetryable() bool {
	if x != nil {
		return x.Retryable
	}
	return false
}

// ValidationDetail identifies one safe validation detail.
type ValidationDetail struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Field         string                 `protobuf:"bytes,1,opt,name=field,proto3" json:"field,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationDetail) Reset() {
	*x = ValidationDetail{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationDetail) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationDetail) ProtoMessage() {}

func (x *ValidationDetail) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationDetail.ProtoReflect.Descriptor instead.
func (*ValidationDetail) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{14}
}

func (x *ValidationDetail) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *ValidationDetail) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

// Obligation is one return-only selected Policy obligation.
type Obligation struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parameters    map[string]*ResponseValue `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Obligation) Reset() {
	*x = Obligation{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Obligation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Obligation) ProtoMessage() {}

func (x *Obligation) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Obligation.ProtoReflect.Descriptor instead.
func (*Obligation) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{15}
}

func (x *Obligation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Obligation) GetParameters() map[string]*ResponseValue {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Advice is one return-only selected Policy advice.
type Advice struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Parameters    map[string]*ResponseValue `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Advice) Reset() {
	*x = Advice{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Advice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Advice) ProtoMessage() {}

func (x *Advice) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Advice.ProtoReflect.Descriptor instead.
func (*Advice) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{16}
}

func (x *Advice) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Advice) GetParameters() map[string]*ResponseValue {
	if x != nil {
		return x.Parameters
	}
	return nil
}

// Diagnostics contains admitted bounded diagnostic entries.
type Diagnostics struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Entries       map[string]*ResponseValue `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Diagnostics) Reset() {
	*x = Diagnostics{}
	mi := &file_api_policy_v1_policy_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Diagnostics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Diagnostics) ProtoMessage() {}

func (x *Diagnostics) ProtoReflect() protoreflect.Message {
	mi := &file_api_policy_v1_policy_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Diagnostics.ProtoReflect.Descriptor instead.
func (*Diagnostics) Descriptor() ([]byte, []int) {
	return file_api_policy_v1_policy_proto_rawDescGZIP(), []int{17}
}

func (x *Diagnostics) GetEntries() map[string]*ResponseValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

var File_api_policy_v1_policy_proto protoreflect.FileDescriptor

const file_api_policy_v1_policy_proto_rawDesc = "" +
	"\n" +
	"\x1aapi/policy/v1/policy.proto\x12\x13nauthilus.policy.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xa6\x04\n" +
	"\x0fDecisionRequest\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\x12\x1d\n" +
	"\n" +
	"request_id\x18\x02 \x01(\tR\trequestId\x123\n" +
	"\x06target\x18\x03 \x01(\v2\x1b.nauthilus.policy.v1.TargetR\x06target\x125\n" +
	"\asubject\x18\x04 \x01(\v2\x1b.nauthilus.policy.v1.EntityR\asubject\x127\n" +
	"\bresource\x18\x05 \x01(\v2\x1b.nauthilus.policy.v1.EntityR\bresource\x12B\n" +
	"\venvironment\x18\x06 \x01(\v2 .nauthilus.policy.v1.EnvironmentR\venvironment\x12T\n" +
	"\n" +
	"attributes\x18\a \x03(\v24.nauthilus.policy.v1.DecisionRequest.AttributesEntryR\n" +
	"attributes\x12@\n" +
	"\aoptions\x18\b \x01(\v2&.nauthilus.policy.v1.EvaluationOptionsR\aoptions\x1aY\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.nauthilus.policy.v1.ValueR\x05value:\x028\x01\">\n" +
	"\x06Target\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xd4\x01\n" +
	"\x06Entity\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12K\n" +
	"\n" +
	"attributes\x18\x03 \x03(\v2+.nauthilus.policy.v1.Entity.AttributesEntryR\n" +
	"attributes\x1aY\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.nauthilus.policy.v1.ValueR\x05value:\x028\x01\"\x8c\x02\n" +
	"\vEnvironment\x12\x18\n" +
	"\aservice\x18\x01 \x01(\tR\aservice\x12\x1a\n" +
	"\binstance\x18\x02 \x01(\tR\binstance\x12\x1a\n" +
	"\bprotocol\x18\x03 \x01(\tR\bprotocol\x12P\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v20.nauthilus.policy.v1.Environment.AttributesEntryR\n" +
	"attributes\x1aY\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x120\n" +
	"\x05value\x18\x02 \x01(\v2\x1a.nauthilus.policy.v1.ValueR\x05value:\x028\x01\"D\n" +
	"\x11EvaluationOptions\x12/\n" +
	"\x13include_diagnostics\x18\x01 \x01(\bR\x12includeDiagnostics\"$\n" +
	"\n" +
	"StringList\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"C\n" +
	"\n" +
	"RecordList\x125\n" +
	"\arecords\x18\x01 \x03(\v2\x1b.nauthilus.policy.v1.RecordR\arecords\"B\n" +
	"\x06Record\x128\n" +
	"\x06fields\x18\x01 \x03(\v2 .nauthilus.policy.v1.RecordFieldR\x06fields\"^\n" +
	"\vRecordField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12;\n" +
	"\x05value\x18\x02 \x01(\v2%.nauthilus.policy.v1.RecordFieldValueR\x05value\"\x97\x02\n" +
	"\x10RecordFieldValue\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x12H\x00R\ainteger\x12\x18\n" +
	"\x06double\x18\x04 \x01(\x01H\x00R\x06double\x12;\n" +
	"\astrings\x18\x05 \x01(\v2\x1f.nauthilus.policy.v1.StringListH\x00R\astrings\x12\x16\n" +
	"\x05bytes\x18\x06 \x01(\fH\x00R\x05bytes\x12:\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestampB\x06\n" +
	"\x04kind\"\xc9\x02\n" +
	"\x05Value\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x12H\x00R\ainteger\x12\x18\n" +
	"\x06double\x18\x04 \x01(\x01H\x00R\x06double\x12;\n" +
	"\astrings\x18\x05 \x01(\v2\x1f.nauthilus.policy.v1.StringListH\x00R\astrings\x12\x16\n" +
	"\x05bytes\x18\x06 \x01(\fH\x00R\x05bytes\x12:\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestamp\x12;\n" +
	"\arecords\x18\b \x01(\v2\x1f.nauthilus.policy.v1.RecordListH\x00R\arecordsB\x06\n" +
	"\x04kind\"\x94\x02\n" +
	"\rResponseValue\x12\x18\n" +
	"\x06string\x18\x01 \x01(\tH\x00R\x06string\x12\x1a\n" +
	"\aboolean\x18\x02 \x01(\bH\x00R\aboolean\x12\x1a\n" +
	"\ainteger\x18\x03 \x01(\x12H\x00R\ainteger\x12\x18\n" +
	"\x06double\x18\x04 \x01(\x01H\x00R\x06double\x12;\n" +
	"\astrings\x18\x05 \x01(\v2\x1f.nauthilus.policy.v1.StringListH\x00R\astrings\x12\x16\n" +
	"\x05bytes\x18\x06 \x01(\fH\x00R\x05bytes\x12:\n" +
	"\ttimestamp\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\ttimestampB\x06\n" +
	"\x04kind\"\xf8\x02\n" +
	"\x10DecisionResponse\x12\x1f\n" +
	"\vdecision_id\x18\x01 \x01(\tR\n" +
	"decisionId\x123\n" +
	"\x06effect\x18\x02 \x01(\x0e2\x1b.nauthilus.policy.v1.EffectR\x06effect\x123\n" +
	"\x06status\x18\x03 \x01(\v2\x1b.nauthilus.policy.v1.StatusR\x06status\x12A\n" +
	"\vobligations\x18\x04 \x03(\v2\x1f.nauthilus.policy.v1.ObligationR\vobligations\x123\n" +
	"\x06advice\x18\x05 \x03(\v2\x1b.nauthilus.policy.v1.AdviceR\x06advice\x12B\n" +
	"\vdiagnostics\x18\x06 \x01(\v2 .nauthilus.policy.v1.DiagnosticsR\vdiagnostics\x12\x1d\n" +
	"\n" +
	"request_id\x18\a \x01(\tR\trequestId\"\x95\x01\n" +
	"\x06Status\x12\x12\n" +
	"\x04code\x18\x01 \x01(\tR\x04code\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12?\n" +
	"\adetails\x18\x03 \x03(\v2%.nauthilus.policy.v1.ValidationDetailR\adetails\x12\x1c\n" +
	"\tretryable\x18\x04 \x01(\bR\tretryable\"@\n" +
	"\x10ValidationDetail\x12\x14\n" +
	"\x05field\x18\x01 \x01(\tR\x05field\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\xd0\x01\n" +
	"\n" +
	"Obligation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12O\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2/.nauthilus.policy.v1.Obligation.ParametersEntryR\n" +
	"parameters\x1aa\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".nauthilus.policy.v1.ResponseValueR\x05value:\x028\x01\"\xc8\x01\n" +
	"\x06Advice\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12K\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2+.nauthilus.policy.v1.Advice.ParametersEntryR\n" +
	"parameters\x1aa\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".nauthilus.policy.v1.ResponseValueR\x05value:\x028\x01\"\xb6\x01\n" +
	"\vDiagnostics\x12G\n" +
	"\aentries\x18\x01 \x03(\v2-.nauthilus.policy.v1.Diagnostics.EntriesEntryR\aentries\x1a^\n" +
	"\fEntriesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x128\n" +
	"\x05value\x18\x02 \x01(\v2\".nauthilus.policy.v1.ResponseValueR\x05value:\x028\x01*y\n" +
	"\x06Effect\x12\x16\n" +
	"\x12EFFECT_UNSPECIFIED\x10\x00\x12\x11\n" +
	"\rEFFECT_PERMIT\x10\x01\x12\x0f\n" +
	"\vEFFECT_DENY\x10\x02\x12\x19\n" +
	"\x15EFFECT_NOT_APPLICABLE\x10\x03\x12\x18\n" +
	"\x14EFFECT_INDETERMINATE\x10\x042p\n" +
	"\x15PolicyDecisionService\x12W\n" +
	"\bEvaluate\x12$.nauthilus.policy.v1.DecisionRequest\x1a%.nauthilus.policy.v1.DecisionResponseB:Z8github.com/croessner/nauthilus/v4/api/policy/v1;policyv1b\x06proto3"

var (
	file_api_policy_v1_policy_proto_rawDescOnce sync.Once
	file_api_policy_v1_policy_proto_rawDescData []byte
)

func file_api_policy_v1_policy_proto_rawDescGZIP() []byte {
	file_api_policy_v1_policy_proto_rawDescOnce.Do(func() {
		file_api_policy_v1_policy_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_policy_v1_policy_proto_rawDesc), len(file_api_policy_v1_policy_proto_rawDesc)))
	})
	return file_api_policy_v1_policy_proto_rawDescData
}

var file_api_policy_v1_policy_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_policy_v1_policy_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_api_policy_v1_policy_proto_goTypes = []any{
	(Effect)(0),                   // 0: nauthilus.policy.v1.Effect
	(*DecisionRequest)(nil),       // 1: nauthilus.policy.v1.DecisionRequest
	(*Target)(nil),                // 2: nauthilus.policy.v1.Target
	(*Entity)(nil),                // 3: nauthilus.policy.v1.Entity
	(*Environment)(nil),           // 4: nauthilus.policy.v1.Environment
	(*EvaluationOptions)(nil),     // 5: nauthilus.policy.v1.EvaluationOptions
	(*StringList)(nil),            // 6: nauthilus.policy.v1.StringList
	(*RecordList)(nil),            // 7: nauthilus.policy.v1.RecordList
	(*Record)(nil),                // 8: nauthilus.policy.v1.Record
	(*RecordField)(nil),           // 9: nauthilus.policy.v1.RecordField
	(*RecordFieldValue)(nil),      // 10: nauthilus.policy.v1.RecordFieldValue
	(*Value)(nil),                 // 11: nauthilus.policy.v1.Value
	(*ResponseValue)(nil),         // 12: nauthilus.policy.v1.ResponseValue
	(*DecisionResponse)(nil),      // 13: nauthilus.policy.v1.DecisionResponse
	(*Status)(nil),                // 14: nauthilus.policy.v1.Status
	(*ValidationDetail)(nil),      // 15: nauthilus.policy.v1.ValidationDetail
	(*Obligation)(nil),            // 16: nauthilus.policy.v1.Obligation
	(*Advice)(nil),                // 17: nauthilus.policy.v1.Advice
	(*Diagnostics)(nil),           // 18: nauthilus.policy.v1.Diagnostics
	nil,                           // 19: nauthilus.policy.v1.DecisionRequest.AttributesEntry
	nil,                           // 20: nauthilus.policy.v1.Entity.AttributesEntry
	nil,                           // 21: nauthilus.policy.v1.Environment.AttributesEntry
	nil,                           // 22: nauthilus.policy.v1.Obligation.ParametersEntry
	nil,                           // 23: nauthilus.policy.v1.Advice.ParametersEntry
	nil,                           // 24: nauthilus.policy.v1.Diagnostics.EntriesEntry
	(*timestamppb.Timestamp)(nil), // 25: google.protobuf.Timestamp
}
var file_api_policy_v1_policy_proto_depIdxs = []int32{
	2,  // 0: nauthilus.policy.v1.DecisionRequest.target:type_name -> nauthilus.policy.v1.Target
	3,  // 1: nauthilus.policy.v1.DecisionRequest.subject:type_name -> nauthilus.policy.v1.Entity
	3,  // 2: nauthilus.policy.v1.DecisionRequest.resource:type_name -> nauthilus.policy.v1.Entity
	4,  // 3: nauthilus.policy.v1.DecisionRequest.environment:type_name -> nauthilus.policy.v1.Environment
	19, // 4: nauthilus.policy.v1.DecisionRequest.attributes:type_name -> nauthilus.policy.v1.DecisionRequest.AttributesEntry
	5,  // 5: nauthilus.policy.v1.DecisionRequest.options:type_name -> nauthilus.policy.v1.EvaluationOptions
	20, // 6: nauthilus.policy.v1.Entity.attributes:type_name -> nauthilus.policy.v1.Entity.AttributesEntry
	21, // 7: nauthilus.policy.v1.Environment.attributes:type_name -> nauthilus.policy.v1.Environment.AttributesEntry
	8,  // 8: nauthilus.policy.v1.RecordList.records:type_name -> nauthilus.policy.v1.Record
	9,  // 9: nauthilus.policy.v1.Record.fields:type_name -> nauthilus.policy.v1.RecordField
	10, // 10: nauthilus.policy.v1.RecordField.value:type_name -> nauthilus.policy.v1.RecordFieldValue
	6,  // 11: nauthilus.policy.v1.RecordFieldValue.strings:type_name -> nauthilus.policy.v1.StringList
	25, // 12: nauthilus.policy.v1.RecordFieldValue.timestamp:type_name -> google.protobuf.Timestamp
	6,  // 13: nauthilus.policy.v1.Value.strings:type_name -> nauthilus.policy.v1.StringList
	25, // 14: nauthilus.policy.v1.Value.timestamp:type_name -> google.protobuf.Timestamp
	7,  // 15: nauthilus.policy.v1.Value.records:type_name -> nauthilus.policy.v1.RecordList
	6,  // 16: nauthilus.policy.v1.ResponseValue.strings:type_name -> nauthilus.policy.v1.StringList
	25, // 17: nauthilus.policy.v1.ResponseValue.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 18: nauthilus.policy.v1.DecisionResponse.effect:type_name -> nauthilus.policy.v1.Effect
	14, // 19: nauthilus.policy.v1.DecisionResponse.status:type_name -> nauthilus.policy.v1.Status
	16, // 20: nauthilus.policy.v1.DecisionResponse.obligations:type_name -> nauthilus.policy.v1.Obligation
	17, // 21: nauthilus.policy.v1.DecisionResponse.advice:type_name -> nauthilus.policy.v1.Advice
	18, // 22: nauthilus.policy.v1.DecisionResponse.diagnostics:type_name -> nauthilus.policy.v1.Diagnostics
	15, // 23: nauthilus.policy.v1.Status.details:type_name -> nauthilus.policy.v1.ValidationDetail
	22, // 24: nauthilus.policy.v1.Obligation.parameters:type_name -> nauthilus.policy.v1.Obligation.ParametersEntry
	23, // 25: nauthilus.policy.v1.Advice.parameters:type_name -> nauthilus.policy.v1.Advice.ParametersEntry
	24, // 26: nauthilus.policy.v1.Diagnostics.entries:type_name -> nauthilus.policy.v1.Diagnostics.EntriesEntry
	11, // 27: nauthilus.policy.v1.DecisionRequest.AttributesEntry.value:type_name -> nauthilus.policy.v1.Value
	11, // 28: nauthilus.policy.v1.Entity.AttributesEntry.value:type_name -> nauthilus.policy.v1.Value
	11, // 29: nauthilus.policy.v1.Environment.AttributesEntry.value:type_name -> nauthilus.policy.v1.Value
	12, // 30: nauthilus.policy.v1.Obligation.ParametersEntry.value:type_name -> nauthilus.policy.v1.ResponseValue
	12, // 31: nauthilus.policy.v1.Advice.ParametersEntry.value:type_name -> nauthilus.policy.v1.ResponseValue
	12, // 32: nauthilus.policy.v1.Diagnostics.EntriesEntry.value:type_name -> nauthilus.policy.v1.ResponseValue
	1,  // 33: nauthilus.policy.v1.PolicyDecisionService.Evaluate:input_type -> nauthilus.policy.v1.DecisionRequest
	13, // 34: nauthilus.policy.v1.PolicyDecisionService.Evaluate:output_type -> nauthilus.policy.v1.DecisionResponse
	34, // [34:35] is the sub-list for method output_type
	33, // [33:34] is the sub-list for method input_type
	33, // [33:33] is the sub-list for extension type_name
	33, // [33:33] is the sub-list for extension extendee
	0,  // [0:33] is the sub-list for field type_name
}

func init() { file_api_policy_v1_policy_proto_init() }
func file_api_policy_v1_policy_proto_init() {
	if File_api_policy_v1_policy_proto != nil {
		return
	}
	file_api_policy_v1_policy_proto_msgTypes[9].OneofWrappers = []any{
		(*RecordFieldValue_String_)(nil),
		(*RecordFieldValue_Boolean)(nil),
		(*RecordFieldValue_Integer)(nil),
		(*RecordFieldValue_Double)(nil),
		(*RecordFieldValue_Strings)(nil),
		(*RecordFieldValue_Bytes)(nil),
		(*RecordFieldValue_Timestamp)(nil),
	}
	file_api_policy_v1_policy_proto_msgTypes[10].OneofWrappers = []any{
		(*Value_String_)(nil),
		(*Value_Boolean)(nil),
		(*Value_Integer)(nil),
		(*Value_Double)(nil),
		(*Value_Strings)(nil),
		(*Value_Bytes)(nil),
		(*Value_Timestamp)(nil),
		(*Value_Records)(nil),
	}
	file_api_policy_v1_policy_proto_msgTypes[11].OneofWrappers = []any{
		(*ResponseValue_String_)(nil),
		(*ResponseValue_Boolean)(nil),
		(*ResponseValue_Integer)(nil),
		(*ResponseValue_Double)(nil),
		(*ResponseValue_Strings)(nil),
		(*ResponseValue_Bytes)(nil),
		(*ResponseValue_Timestamp)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_policy_v1_policy_proto_rawDesc), len(file_api_policy_v1_policy_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_policy_v1_policy_proto_goTypes,
		DependencyIndexes: file_api_policy_v1_policy_proto_depIdxs,
		EnumInfos:         file_api_policy_v1_policy_proto_enumTypes,
		MessageInfos:      file_api_policy_v1_policy_proto_msgTypes,
	}.Build()
	File_api_policy_v1_policy_proto = out.File
	file_api_policy_v1_policy_proto_goTypes = nil
	file_api_policy_v1_policy_proto_depIdxs = nil
}
