// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.36.0
// source: api/policy/v1/policy.proto

package policyv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PolicyDecisionService_Evaluate_FullMethodName = "/nauthilus.policy.v1.PolicyDecisionService/Evaluate"
)

// PolicyDecisionServiceClient is the client API for PolicyDecisionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PolicyDecisionService evaluates one admitted Policy request per unary call.
type PolicyDecisionServiceClient interface {
	Evaluate(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error)
}

type policyDecisionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyDecisionServiceClient(cc grpc.ClientConnInterface) PolicyDecisionServiceClient {
	return &policyDecisionServiceClient{cc}
}

func (c *policyDecisionServiceClient) Evaluate(ctx context.Context, in *DecisionRequest, opts ...grpc.CallOption) (*DecisionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecisionResponse)
	err := c.cc.Invoke(ctx, PolicyDecisionService_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyDecisionServiceServer is the server API for PolicyDecisionService service.
// All implementations must embed UnimplementedPolicyDecisionServiceServer
// for forward compatibility.
//
// PolicyDecisionService evaluates one admitted Policy request per unary call.
type PolicyDecisionServiceServer interface {
	Evaluate(context.Context, *DecisionRequest) (*DecisionResponse, error)
	mustEmbedUnimplementedPolicyDecisionServiceServer()
}

// UnimplementedPolicyDecisionServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyDecisionServiceServer struct{}

func (UnimplementedPolicyDecisionServiceServer) Evaluate(context.Context, *DecisionRequest) (*DecisionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedPolicyDecisionServiceServer) mustEmbedUnimplementedPolicyDecisionServiceServer() {}
func (UnimplementedPolicyDecisionServiceServer) testEmbeddedByValue()                               {}

// UnsafePolicyDecisionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyDecisionServiceServer will
// result in compilation errors.
type UnsafePolicyDecisionServiceServer interface {
	mustEmbedUnimplementedPolicyDecisionServiceServer()
}

func RegisterPolicyDecisionServiceServer(s grpc.ServiceRegistrar, srv PolicyDecisionServiceServer) {
	// If the following call pancis, it indicates UnimplementedPolicyDecisionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PolicyDecisionService_ServiceDesc, srv)
}

func _PolicyDecisionService_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecisionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyDecisionServiceServer).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PolicyDecisionService_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyDecisionServiceServer).Evaluate(ctx, req.(*DecisionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PolicyDecisionService_ServiceDesc is the grpc.ServiceDesc for PolicyDecisionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PolicyDecisionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nauthilus.policy.v1.PolicyDecisionService",
	HandlerType: (*PolicyDecisionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _PolicyDecisionService_Evaluate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/policy/v1/policy.proto",
}
