// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v7.34.1
// source: server/grpcapi/identity/v1/identity_backend.proto

package identityv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	IdentityBackendService_ResolveUser_FullMethodName              = "/nauthilus.identity.v1.IdentityBackendService/ResolveUser"
	IdentityBackendService_GetMFAState_FullMethodName              = "/nauthilus.identity.v1.IdentityBackendService/GetMFAState"
	IdentityBackendService_BeginTOTPRegistration_FullMethodName    = "/nauthilus.identity.v1.IdentityBackendService/BeginTOTPRegistration"
	IdentityBackendService_FinishTOTPRegistration_FullMethodName   = "/nauthilus.identity.v1.IdentityBackendService/FinishTOTPRegistration"
	IdentityBackendService_VerifyTOTP_FullMethodName               = "/nauthilus.identity.v1.IdentityBackendService/VerifyTOTP"
	IdentityBackendService_DeleteTOTP_FullMethodName               = "/nauthilus.identity.v1.IdentityBackendService/DeleteTOTP"
	IdentityBackendService_GenerateRecoveryCodes_FullMethodName    = "/nauthilus.identity.v1.IdentityBackendService/GenerateRecoveryCodes"
	IdentityBackendService_UseRecoveryCode_FullMethodName          = "/nauthilus.identity.v1.IdentityBackendService/UseRecoveryCode"
	IdentityBackendService_DeleteRecoveryCodes_FullMethodName      = "/nauthilus.identity.v1.IdentityBackendService/DeleteRecoveryCodes"
	IdentityBackendService_GetWebAuthnCredentials_FullMethodName   = "/nauthilus.identity.v1.IdentityBackendService/GetWebAuthnCredentials"
	IdentityBackendService_SaveWebAuthnCredential_FullMethodName   = "/nauthilus.identity.v1.IdentityBackendService/SaveWebAuthnCredential"
	IdentityBackendService_UpdateWebAuthnCredential_FullMethodName = "/nauthilus.identity.v1.IdentityBackendService/UpdateWebAuthnCredential"
	IdentityBackendService_DeleteWebAuthnCredential_FullMethodName = "/nauthilus.identity.v1.IdentityBackendService/DeleteWebAuthnCredential"
)

// IdentityBackendServiceClient is the client API for IdentityBackendService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// IdentityBackendService exposes persistent identity and MFA data operations.
type IdentityBackendServiceClient interface {
	ResolveUser(ctx context.Context, in *ResolveUserRequest, opts ...grpc.CallOption) (*UserSnapshotResponse, error)
	GetMFAState(ctx context.Context, in *GetMFAStateRequest, opts ...grpc.CallOption) (*MFAStateResponse, error)
	BeginTOTPRegistration(ctx context.Context, in *BeginTOTPRegistrationRequest, opts ...grpc.CallOption) (*BeginTOTPRegistrationResponse, error)
	FinishTOTPRegistration(ctx context.Context, in *FinishTOTPRegistrationRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
	VerifyTOTP(ctx context.Context, in *VerifyTOTPRequest, opts ...grpc.CallOption) (*VerifyTOTPResponse, error)
	DeleteTOTP(ctx context.Context, in *DeleteTOTPRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
	GenerateRecoveryCodes(ctx context.Context, in *GenerateRecoveryCodesRequest, opts ...grpc.CallOption) (*GenerateRecoveryCodesResponse, error)
	UseRecoveryCode(ctx context.Context, in *UseRecoveryCodeRequest, opts ...grpc.CallOption) (*UseRecoveryCodeResponse, error)
	DeleteRecoveryCodes(ctx context.Context, in *DeleteRecoveryCodesRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
	GetWebAuthnCredentials(ctx context.Context, in *GetWebAuthnCredentialsRequest, opts ...grpc.CallOption) (*WebAuthnCredentialsResponse, error)
	SaveWebAuthnCredential(ctx context.Context, in *SaveWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
	UpdateWebAuthnCredential(ctx context.Context, in *UpdateWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
	DeleteWebAuthnCredential(ctx context.Context, in *DeleteWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error)
}

type identityBackendServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIdentityBackendServiceClient(cc grpc.ClientConnInterface) IdentityBackendServiceClient {
	return &identityBackendServiceClient{cc}
}

func (c *identityBackendServiceClient) ResolveUser(ctx context.Context, in *ResolveUserRequest, opts ...grpc.CallOption) (*UserSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UserSnapshotResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_ResolveUser_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) GetMFAState(ctx context.Context, in *GetMFAStateRequest, opts ...grpc.CallOption) (*MFAStateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAStateResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_GetMFAState_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) BeginTOTPRegistration(ctx context.Context, in *BeginTOTPRegistrationRequest, opts ...grpc.CallOption) (*BeginTOTPRegistrationResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTOTPRegistrationResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_BeginTOTPRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) FinishTOTPRegistration(ctx context.Context, in *FinishTOTPRegistrationRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_FinishTOTPRegistration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) VerifyTOTP(ctx context.Context, in *VerifyTOTPRequest, opts ...grpc.CallOption) (*VerifyTOTPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VerifyTOTPResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_VerifyTOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) DeleteTOTP(ctx context.Context, in *DeleteTOTPRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_DeleteTOTP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) GenerateRecoveryCodes(ctx context.Context, in *GenerateRecoveryCodesRequest, opts ...grpc.CallOption) (*GenerateRecoveryCodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRecoveryCodesResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_GenerateRecoveryCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) UseRecoveryCode(ctx context.Context, in *UseRecoveryCodeRequest, opts ...grpc.CallOption) (*UseRecoveryCodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseRecoveryCodeResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_UseRecoveryCode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) DeleteRecoveryCodes(ctx context.Context, in *DeleteRecoveryCodesRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_DeleteRecoveryCodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) GetWebAuthnCredentials(ctx context.Context, in *GetWebAuthnCredentialsRequest, opts ...grpc.CallOption) (*WebAuthnCredentialsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WebAuthnCredentialsResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_GetWebAuthnCredentials_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) SaveWebAuthnCredential(ctx context.Context, in *SaveWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_SaveWebAuthnCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) UpdateWebAuthnCredential(ctx context.Context, in *UpdateWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_UpdateWebAuthnCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *identityBackendServiceClient) DeleteWebAuthnCredential(ctx context.Context, in *DeleteWebAuthnCredentialRequest, opts ...grpc.CallOption) (*MFAWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MFAWriteResponse)
	err := c.cc.Invoke(ctx, IdentityBackendService_DeleteWebAuthnCredential_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IdentityBackendServiceServer is the server API for IdentityBackendService service.
// All implementations must embed UnimplementedIdentityBackendServiceServer
// for forward compatibility.
//
// IdentityBackendService exposes persistent identity and MFA data operations.
type IdentityBackendServiceServer interface {
	ResolveUser(context.Context, *ResolveUserRequest) (*UserSnapshotResponse, error)
	GetMFAState(context.Context, *GetMFAStateRequest) (*MFAStateResponse, error)
	BeginTOTPRegistration(context.Context, *BeginTOTPRegistrationRequest) (*BeginTOTPRegistrationResponse, error)
	FinishTOTPRegistration(context.Context, *FinishTOTPRegistrationRequest) (*MFAWriteResponse, error)
	VerifyTOTP(context.Context, *VerifyTOTPRequest) (*VerifyTOTPResponse, error)
	DeleteTOTP(context.Context, *DeleteTOTPRequest) (*MFAWriteResponse, error)
	GenerateRecoveryCodes(context.Context, *GenerateRecoveryCodesRequest) (*GenerateRecoveryCodesResponse, error)
	UseRecoveryCode(context.Context, *UseRecoveryCodeRequest) (*UseRecoveryCodeResponse, error)
	DeleteRecoveryCodes(context.Context, *DeleteRecoveryCodesRequest) (*MFAWriteResponse, error)
	GetWebAuthnCredentials(context.Context, *GetWebAuthnCredentialsRequest) (*WebAuthnCredentialsResponse, error)
	SaveWebAuthnCredential(context.Context, *SaveWebAuthnCredentialRequest) (*MFAWriteResponse, error)
	UpdateWebAuthnCredential(context.Context, *UpdateWebAuthnCredentialRequest) (*MFAWriteResponse, error)
	DeleteWebAuthnCredential(context.Context, *DeleteWebAuthnCredentialRequest) (*MFAWriteResponse, error)
	mustEmbedUnimplementedIdentityBackendServiceServer()
}

// UnimplementedIdentityBackendServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedIdentityBackendServiceServer struct{}

func (UnimplementedIdentityBackendServiceServer) ResolveUser(context.Context, *ResolveUserRequest) (*UserSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ResolveUser not implemented")
}
func (UnimplementedIdentityBackendServiceServer) GetMFAState(context.Context, *GetMFAStateRequest) (*MFAStateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMFAState not implemented")
}
func (UnimplementedIdentityBackendServiceServer) BeginTOTPRegistration(context.Context, *BeginTOTPRegistrationRequest) (*BeginTOTPRegistrationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTOTPRegistration not implemented")
}
func (UnimplementedIdentityBackendServiceServer) FinishTOTPRegistration(context.Context, *FinishTOTPRegistrationRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FinishTOTPRegistration not implemented")
}
func (UnimplementedIdentityBackendServiceServer) VerifyTOTP(context.Context, *VerifyTOTPRequest) (*VerifyTOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyTOTP not implemented")
}
func (UnimplementedIdentityBackendServiceServer) DeleteTOTP(context.Context, *DeleteTOTPRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTOTP not implemented")
}
func (UnimplementedIdentityBackendServiceServer) GenerateRecoveryCodes(context.Context, *GenerateRecoveryCodesRequest) (*GenerateRecoveryCodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateRecoveryCodes not implemented")
}
func (UnimplementedIdentityBackendServiceServer) UseRecoveryCode(context.Context, *UseRecoveryCodeRequest) (*UseRecoveryCodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UseRecoveryCode not implemented")
}
func (UnimplementedIdentityBackendServiceServer) DeleteRecoveryCodes(context.Context, *DeleteRecoveryCodesRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRecoveryCodes not implemented")
}
func (UnimplementedIdentityBackendServiceServer) GetWebAuthnCredentials(context.Context, *GetWebAuthnCredentialsRequest) (*WebAuthnCredentialsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetWebAuthnCredentials not implemented")
}
func (UnimplementedIdentityBackendServiceServer) SaveWebAuthnCredential(context.Context, *SaveWebAuthnCredentialRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SaveWebAuthnCredential not implemented")
}
func (UnimplementedIdentityBackendServiceServer) UpdateWebAuthnCredential(context.Context, *UpdateWebAuthnCredentialRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateWebAuthnCredential not implemented")
}
func (UnimplementedIdentityBackendServiceServer) DeleteWebAuthnCredential(context.Context, *DeleteWebAuthnCredentialRequest) (*MFAWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteWebAuthnCredential not implemented")
}
func (UnimplementedIdentityBackendServiceServer) mustEmbedUnimplementedIdentityBackendServiceServer() {
}
func (UnimplementedIdentityBackendServiceServer) testEmbeddedByValue() {}

// UnsafeIdentityBackendServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to IdentityBackendServiceServer will
// result in compilation errors.
type UnsafeIdentityBackendServiceServer interface {
	mustEmbedUnimplementedIdentityBackendServiceServer()
}

func RegisterIdentityBackendServiceServer(s grpc.ServiceRegistrar, srv IdentityBackendServiceServer) {
	// If the following call pancis, it indicates UnimplementedIdentityBackendServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&IdentityBackendService_ServiceDesc, srv)
}

func _IdentityBackendService_ResolveUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).ResolveUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_ResolveUser_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).ResolveUser(ctx, req.(*ResolveUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_GetMFAState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMFAStateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).GetMFAState(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_GetMFAState_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).GetMFAState(ctx, req.(*GetMFAStateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_BeginTOTPRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTOTPRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).BeginTOTPRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_BeginTOTPRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).BeginTOTPRegistration(ctx, req.(*BeginTOTPRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_FinishTOTPRegistration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinishTOTPRegistrationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).FinishTOTPRegistration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_FinishTOTPRegistration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).FinishTOTPRegistration(ctx, req.(*FinishTOTPRegistrationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_VerifyTOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyTOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).VerifyTOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_VerifyTOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).VerifyTOTP(ctx, req.(*VerifyTOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_DeleteTOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteTOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).DeleteTOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_DeleteTOTP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).DeleteTOTP(ctx, req.(*DeleteTOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_GenerateRecoveryCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRecoveryCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).GenerateRecoveryCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_GenerateRecoveryCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).GenerateRecoveryCodes(ctx, req.(*GenerateRecoveryCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_UseRecoveryCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseRecoveryCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).UseRecoveryCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_UseRecoveryCode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).UseRecoveryCode(ctx, req.(*UseRecoveryCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_DeleteRecoveryCodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRecoveryCodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).DeleteRecoveryCodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_DeleteRecoveryCodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).DeleteRecoveryCodes(ctx, req.(*DeleteRecoveryCodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_GetWebAuthnCredentials_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWebAuthnCredentialsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).GetWebAuthnCredentials(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_GetWebAuthnCredentials_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).GetWebAuthnCredentials(ctx, req.(*GetWebAuthnCredentialsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_SaveWebAuthnCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveWebAuthnCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).SaveWebAuthnCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_SaveWebAuthnCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).SaveWebAuthnCredential(ctx, req.(*SaveWebAuthnCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_UpdateWebAuthnCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateWebAuthnCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).UpdateWebAuthnCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_UpdateWebAuthnCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).UpdateWebAuthnCredential(ctx, req.(*UpdateWebAuthnCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IdentityBackendService_DeleteWebAuthnCredential_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteWebAuthnCredentialRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IdentityBackendServiceServer).DeleteWebAuthnCredential(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IdentityBackendService_DeleteWebAuthnCredential_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IdentityBackendServiceServer).DeleteWebAuthnCredential(ctx, req.(*DeleteWebAuthnCredentialRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IdentityBackendService_ServiceDesc is the grpc.ServiceDesc for IdentityBackendService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var IdentityBackendService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "nauthilus.identity.v1.IdentityBackendService",
	HandlerType: (*IdentityBackendServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ResolveUser",
			Handler:    _IdentityBackendService_ResolveUser_Handler,
		},
		{
			MethodName: "GetMFAState",
			Handler:    _IdentityBackendService_GetMFAState_Handler,
		},
		{
			MethodName: "BeginTOTPRegistration",
			Handler:    _IdentityBackendService_BeginTOTPRegistration_Handler,
		},
		{
			MethodName: "FinishTOTPRegistration",
			Handler:    _IdentityBackendService_FinishTOTPRegistration_Handler,
		},
		{
			MethodName: "VerifyTOTP",
			Handler:    _IdentityBackendService_VerifyTOTP_Handler,
		},
		{
			MethodName: "DeleteTOTP",
			Handler:    _IdentityBackendService_DeleteTOTP_Handler,
		},
		{
			MethodName: "GenerateRecoveryCodes",
			Handler:    _IdentityBackendService_GenerateRecoveryCodes_Handler,
		},
		{
			MethodName: "UseRecoveryCode",
			Handler:    _IdentityBackendService_UseRecoveryCode_Handler,
		},
		{
			MethodName: "DeleteRecoveryCodes",
			Handler:    _IdentityBackendService_DeleteRecoveryCodes_Handler,
		},
		{
			MethodName: "GetWebAuthnCredentials",
			Handler:    _IdentityBackendService_GetWebAuthnCredentials_Handler,
		},
		{
			MethodName: "SaveWebAuthnCredential",
			Handler:    _IdentityBackendService_SaveWebAuthnCredential_Handler,
		},
		{
			MethodName: "UpdateWebAuthnCredential",
			Handler:    _IdentityBackendService_UpdateWebAuthnCredential_Handler,
		},
		{
			MethodName: "DeleteWebAuthnCredential",
			Handler:    _IdentityBackendService_DeleteWebAuthnCredential_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server/grpcapi/identity/v1/identity_backend.proto",
}
