// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: server/grpcapi/identity/v1/identity_backend.proto

package identityv1

import (
	v1 "github.com/croessner/nauthilus/v3/server/grpcapi/common/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RequestContext carries transport-neutral request metadata from the edge.
type RequestContext struct {
	state              protoimpl.MessageState         `protogen:"open.v1"`
	Username           string                         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	ClientIp           string                         `protobuf:"bytes,2,opt,name=client_ip,json=clientIp,proto3" json:"client_ip,omitempty"`
	ClientPort         string                         `protobuf:"bytes,3,opt,name=client_port,json=clientPort,proto3" json:"client_port,omitempty"`
	ClientHostname     string                         `protobuf:"bytes,4,opt,name=client_hostname,json=clientHostname,proto3" json:"client_hostname,omitempty"`
	ClientId           string                         `protobuf:"bytes,5,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	ExternalSessionId  string                         `protobuf:"bytes,6,opt,name=external_session_id,json=externalSessionId,proto3" json:"external_session_id,omitempty"`
	UserAgent          string                         `protobuf:"bytes,7,opt,name=user_agent,json=userAgent,proto3" json:"user_agent,omitempty"`
	LocalIp            string                         `protobuf:"bytes,8,opt,name=local_ip,json=localIp,proto3" json:"local_ip,omitempty"`
	LocalPort          string                         `protobuf:"bytes,9,opt,name=local_port,json=localPort,proto3" json:"local_port,omitempty"`
	Protocol           string                         `protobuf:"bytes,10,opt,name=protocol,proto3" json:"protocol,omitempty"`
	Method             string                         `protobuf:"bytes,11,opt,name=method,proto3" json:"method,omitempty"`
	Ssl                string                         `protobuf:"bytes,12,opt,name=ssl,proto3" json:"ssl,omitempty"`
	SslSessionId       string                         `protobuf:"bytes,13,opt,name=ssl_session_id,json=sslSessionId,proto3" json:"ssl_session_id,omitempty"`
	SslClientVerify    string                         `protobuf:"bytes,14,opt,name=ssl_client_verify,json=sslClientVerify,proto3" json:"ssl_client_verify,omitempty"`
	SslClientDn        string                         `protobuf:"bytes,15,opt,name=ssl_client_dn,json=sslClientDn,proto3" json:"ssl_client_dn,omitempty"`
	SslClientCn        string                         `protobuf:"bytes,16,opt,name=ssl_client_cn,json=sslClientCn,proto3" json:"ssl_client_cn,omitempty"`
	SslIssuer          string                         `protobuf:"bytes,17,opt,name=ssl_issuer,json=sslIssuer,proto3" json:"ssl_issuer,omitempty"`
	SslClientNotbefore string                         `protobuf:"bytes,18,opt,name=ssl_client_notbefore,json=sslClientNotbefore,proto3" json:"ssl_client_notbefore,omitempty"`
	SslClientNotafter  string                         `protobuf:"bytes,19,opt,name=ssl_client_notafter,json=sslClientNotafter,proto3" json:"ssl_client_notafter,omitempty"`
	SslSubjectDn       string                         `protobuf:"bytes,20,opt,name=ssl_subject_dn,json=sslSubjectDn,proto3" json:"ssl_subject_dn,omitempty"`
	SslIssuerDn        string                         `protobuf:"bytes,21,opt,name=ssl_issuer_dn,json=sslIssuerDn,proto3" json:"ssl_issuer_dn,omitempty"`
	SslClientSubjectDn string                         `protobuf:"bytes,22,opt,name=ssl_client_subject_dn,json=sslClientSubjectDn,proto3" json:"ssl_client_subject_dn,omitempty"`
	SslClientIssuerDn  string                         `protobuf:"bytes,23,opt,name=ssl_client_issuer_dn,json=sslClientIssuerDn,proto3" json:"ssl_client_issuer_dn,omitempty"`
	SslProtocol        string                         `protobuf:"bytes,24,opt,name=ssl_protocol,json=sslProtocol,proto3" json:"ssl_protocol,omitempty"`
	SslCipher          string                         `protobuf:"bytes,25,opt,name=ssl_cipher,json=sslCipher,proto3" json:"ssl_cipher,omitempty"`
	SslSerial          string                         `protobuf:"bytes,26,opt,name=ssl_serial,json=sslSerial,proto3" json:"ssl_serial,omitempty"`
	SslFingerprint     string                         `protobuf:"bytes,27,opt,name=ssl_fingerprint,json=sslFingerprint,proto3" json:"ssl_fingerprint,omitempty"`
	OidcCid            string                         `protobuf:"bytes,28,opt,name=oidc_cid,json=oidcCid,proto3" json:"oidc_cid,omitempty"`
	SamlEntityId       string                         `protobuf:"bytes,29,opt,name=saml_entity_id,json=samlEntityId,proto3" json:"saml_entity_id,omitempty"`
	AuthLoginAttempt   uint32                         `protobuf:"varint,30,opt,name=auth_login_attempt,json=authLoginAttempt,proto3" json:"auth_login_attempt,omitempty"`
	Metadata           map[string]*v1.AttributeValues `protobuf:"bytes,31,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	EdgeInstance       string                         `protobuf:"bytes,32,opt,name=edge_instance,json=edgeInstance,proto3" json:"edge_instance,omitempty"`
	EdgeRequestId      string                         `protobuf:"bytes,33,opt,name=edge_request_id,json=edgeRequestId,proto3" json:"edge_request_id,omitempty"`
	RequestedLanguage  string                         `protobuf:"bytes,34,opt,name=requested_language,json=requestedLanguage,proto3" json:"requested_language,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RequestContext) Reset() {
	*x = RequestContext{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestContext) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestContext) ProtoMessage() {}

func (x *RequestContext) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestContext.ProtoReflect.Descriptor instead.
func (*RequestContext) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{0}
}

func (x *RequestContext) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *RequestContext) GetClientIp() string {
	if x != nil {
		return x.ClientIp
	}
	return ""
}

func (x *RequestContext) GetClientPort() string {
	if x != nil {
		return x.ClientPort
	}
	return ""
}

func (x *RequestContext) GetClientHostname() string {
	if x != nil {
		return x.ClientHostname
	}
	return ""
}

func (x *RequestContext) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *RequestContext) GetExternalSessionId() string {
	if x != nil {
		return x.ExternalSessionId
	}
	return ""
}

func (x *RequestContext) GetUserAgent() string {
	if x != nil {
		return x.UserAgent
	}
	return ""
}

func (x *RequestContext) GetLocalIp() string {
	if x != nil {
		return x.LocalIp
	}
	return ""
}

func (x *RequestContext) GetLocalPort() string {
	if x != nil {
		return x.LocalPort
	}
	return ""
}

func (x *RequestContext) GetProtocol() string {
	if x != nil {
		return x.Protocol
	}
	return ""
}

func (x *RequestContext) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RequestContext) GetSsl() string {
	if x != nil {
		return x.Ssl
	}
	return ""
}

func (x *RequestContext) GetSslSessionId() string {
	if x != nil {
		return x.SslSessionId
	}
	return ""
}

func (x *RequestContext) GetSslClientVerify() string {
	if x != nil {
		return x.SslClientVerify
	}
	return ""
}

func (x *RequestContext) GetSslClientDn() string {
	if x != nil {
		return x.SslClientDn
	}
	return ""
}

func (x *RequestContext) GetSslClientCn() string {
	if x != nil {
		return x.SslClientCn
	}
	return ""
}

func (x *RequestContext) GetSslIssuer() string {
	if x != nil {
		return x.SslIssuer
	}
	return ""
}

func (x *RequestContext) GetSslClientNotbefore() string {
	if x != nil {
		return x.SslClientNotbefore
	}
	return ""
}

func (x *RequestContext) GetSslClientNotafter() string {
	if x != nil {
		return x.SslClientNotafter
	}
	return ""
}

func (x *RequestContext) GetSslSubjectDn() string {
	if x != nil {
		return x.SslSubjectDn
	}
	return ""
}

func (x *RequestContext) GetSslIssuerDn() string {
	if x != nil {
		return x.SslIssuerDn
	}
	return ""
}

func (x *RequestContext) GetSslClientSubjectDn() string {
	if x != nil {
		return x.SslClientSubjectDn
	}
	return ""
}

func (x *RequestContext) GetSslClientIssuerDn() string {
	if x != nil {
		return x.SslClientIssuerDn
	}
	return ""
}

func (x *RequestContext) GetSslProtocol() string {
	if x != nil {
		return x.SslProtocol
	}
	return ""
}

func (x *RequestContext) GetSslCipher() string {
	if x != nil {
		return x.SslCipher
	}
	return ""
}

func (x *RequestContext) GetSslSerial() string {
	if x != nil {
		return x.SslSerial
	}
	return ""
}

func (x *RequestContext) GetSslFingerprint() string {
	if x != nil {
		return x.SslFingerprint
	}
	return ""
}

func (x *RequestContext) GetOidcCid() string {
	if x != nil {
		return x.OidcCid
	}
	return ""
}

func (x *RequestContext) GetSamlEntityId() string {
	if x != nil {
		return x.SamlEntityId
	}
	return ""
}

func (x *RequestContext) GetAuthLoginAttempt() uint32 {
	if x != nil {
		return x.AuthLoginAttempt
	}
	return 0
}

func (x *RequestContext) GetMetadata() map[string]*v1.AttributeValues {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *RequestContext) GetEdgeInstance() string {
	if x != nil {
		return x.EdgeInstance
	}
	return ""
}

func (x *RequestContext) GetEdgeRequestId() string {
	if x != nil {
		return x.EdgeRequestId
	}
	return ""
}

func (x *RequestContext) GetRequestedLanguage() string {
	if x != nil {
		return x.RequestedLanguage
	}
	return ""
}

// AttributeRequest selects which identity attributes the authority may release.
type AttributeRequest struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Names                   []string               `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	IncludeStandardIdentity bool                   `protobuf:"varint,2,opt,name=include_standard_identity,json=includeStandardIdentity,proto3" json:"include_standard_identity,omitempty"`
	IncludeGroups           bool                   `protobuf:"varint,3,opt,name=include_groups,json=includeGroups,proto3" json:"include_groups,omitempty"`
	IncludeGroupDns         bool                   `protobuf:"varint,4,opt,name=include_group_dns,json=includeGroupDns,proto3" json:"include_group_dns,omitempty"`
	ReportMissing           bool                   `protobuf:"varint,5,opt,name=report_missing,json=reportMissing,proto3" json:"report_missing,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *AttributeRequest) Reset() {
	*x = AttributeRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AttributeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeRequest) ProtoMessage() {}

func (x *AttributeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeRequest.ProtoReflect.Descriptor instead.
func (*AttributeRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{1}
}

func (x *AttributeRequest) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

func (x *AttributeRequest) GetIncludeStandardIdentity() bool {
	if x != nil {
		return x.IncludeStandardIdentity
	}
	return false
}

func (x *AttributeRequest) GetIncludeGroups() bool {
	if x != nil {
		return x.IncludeGroups
	}
	return false
}

func (x *AttributeRequest) GetIncludeGroupDns() bool {
	if x != nil {
		return x.IncludeGroupDns
	}
	return false
}

func (x *AttributeRequest) GetReportMissing() bool {
	if x != nil {
		return x.ReportMissing
	}
	return false
}

// UserSnapshot contains released identity data for edge-side IdP materialization.
type UserSnapshot struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Username      string                         `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Account       string                         `protobuf:"bytes,2,opt,name=account,proto3" json:"account,omitempty"`
	UniqueUserId  string                         `protobuf:"bytes,3,opt,name=unique_user_id,json=uniqueUserId,proto3" json:"unique_user_id,omitempty"`
	DisplayName   string                         `protobuf:"bytes,4,opt,name=display_name,json=displayName,proto3" json:"display_name,omitempty"`
	Attributes    map[string]*v1.AttributeValues `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Groups        []string                       `protobuf:"bytes,6,rep,name=groups,proto3" json:"groups,omitempty"`
	GroupDns      []string                       `protobuf:"bytes,7,rep,name=group_dns,json=groupDns,proto3" json:"group_dns,omitempty"`
	Backend       *v1.BackendRef                 `protobuf:"bytes,8,opt,name=backend,proto3" json:"backend,omitempty"`
	Mfa           *MFAState                      `protobuf:"bytes,9,opt,name=mfa,proto3" json:"mfa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSnapshot) Reset() {
	*x = UserSnapshot{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSnapshot) ProtoMessage() {}

func (x *UserSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSnapshot.ProtoReflect.Descriptor instead.
func (*UserSnapshot) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{2}
}

func (x *UserSnapshot) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSnapshot) GetAccount() string {
	if x != nil {
		return x.Account
	}
	return ""
}

func (x *UserSnapshot) GetUniqueUserId() string {
	if x != nil {
		return x.UniqueUserId
	}
	return ""
}

func (x *UserSnapshot) GetDisplayName() string {
	if x != nil {
		return x.DisplayName
	}
	return ""
}

func (x *UserSnapshot) GetAttributes() map[string]*v1.AttributeValues {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UserSnapshot) GetGroups() []string {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *UserSnapshot) GetGroupDns() []string {
	if x != nil {
		return x.GroupDns
	}
	return nil
}

func (x *UserSnapshot) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *UserSnapshot) GetMfa() *MFAState {
	if x != nil {
		return x.Mfa
	}
	return nil
}

// MFAState contains public MFA state only; it never carries TOTP secrets or recovery-code values.
type MFAState struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	HasTotp             bool                   `protobuf:"varint,1,opt,name=has_totp,json=hasTotp,proto3" json:"has_totp,omitempty"`
	RecoveryCodeCount   uint32                 `protobuf:"varint,2,opt,name=recovery_code_count,json=recoveryCodeCount,proto3" json:"recovery_code_count,omitempty"`
	HasWebauthn         bool                   `protobuf:"varint,3,opt,name=has_webauthn,json=hasWebauthn,proto3" json:"has_webauthn,omitempty"`
	WebauthnCredentials []*WebAuthnCredential  `protobuf:"bytes,4,rep,name=webauthn_credentials,json=webauthnCredentials,proto3" json:"webauthn_credentials,omitempty"`
	PreferredMethod     string                 `protobuf:"bytes,5,opt,name=preferred_method,json=preferredMethod,proto3" json:"preferred_method,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *MFAState) Reset() {
	*x = MFAState{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAState) ProtoMessage() {}

func (x *MFAState) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAState.ProtoReflect.Descriptor instead.
func (*MFAState) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{3}
}

func (x *MFAState) GetHasTotp() bool {
	if x != nil {
		return x.HasTotp
	}
	return false
}

func (x *MFAState) GetRecoveryCodeCount() uint32 {
	if x != nil {
		return x.RecoveryCodeCount
	}
	return 0
}

func (x *MFAState) GetHasWebauthn() bool {
	if x != nil {
		return x.HasWebauthn
	}
	return false
}

func (x *MFAState) GetWebauthnCredentials() []*WebAuthnCredential {
	if x != nil {
		return x.WebauthnCredentials
	}
	return nil
}

func (x *MFAState) GetPreferredMethod() string {
	if x != nil {
		return x.PreferredMethod
	}
	return ""
}

// WebAuthnCredential carries persisted public WebAuthn credential material.
type WebAuthnCredential struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	CredentialId    []byte                 `protobuf:"bytes,1,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	PublicKey       []byte                 `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	SignCount       uint32                 `protobuf:"varint,3,opt,name=sign_count,json=signCount,proto3" json:"sign_count,omitempty"`
	Transports      []string               `protobuf:"bytes,4,rep,name=transports,proto3" json:"transports,omitempty"`
	BackupEligible  bool                   `protobuf:"varint,5,opt,name=backup_eligible,json=backupEligible,proto3" json:"backup_eligible,omitempty"`
	BackupState     bool                   `protobuf:"varint,6,opt,name=backup_state,json=backupState,proto3" json:"backup_state,omitempty"`
	AttestationType string                 `protobuf:"bytes,7,opt,name=attestation_type,json=attestationType,proto3" json:"attestation_type,omitempty"`
	Name            string                 `protobuf:"bytes,8,opt,name=name,proto3" json:"name,omitempty"`
	LastUsed        *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=last_used,json=lastUsed,proto3" json:"last_used,omitempty"`
	RawJson         string                 `protobuf:"bytes,10,opt,name=raw_json,json=rawJson,proto3" json:"raw_json,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WebAuthnCredential) Reset() {
	*x = WebAuthnCredential{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredential) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredential) ProtoMessage() {}

func (x *WebAuthnCredential) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredential.ProtoReflect.Descriptor instead.
func (*WebAuthnCredential) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{4}
}

func (x *WebAuthnCredential) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *WebAuthnCredential) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *WebAuthnCredential) GetSignCount() uint32 {
	if x != nil {
		return x.SignCount
	}
	return 0
}

func (x *WebAuthnCredential) GetTransports() []string {
	if x != nil {
		return x.Transports
	}
	return nil
}

func (x *WebAuthnCredential) GetBackupEligible() bool {
	if x != nil {
		return x.BackupEligible
	}
	return false
}

func (x *WebAuthnCredential) GetBackupState() bool {
	if x != nil {
		return x.BackupState
	}
	return false
}

func (x *WebAuthnCredential) GetAttestationType() string {
	if x != nil {
		return x.AttestationType
	}
	return ""
}

func (x *WebAuthnCredential) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WebAuthnCredential) GetLastUsed() *timestamppb.Timestamp {
	if x != nil {
		return x.LastUsed
	}
	return nil
}

func (x *WebAuthnCredential) GetRawJson() string {
	if x != nil {
		return x.RawJson
	}
	return ""
}

// ResolveUserRequest resolves a user and optionally released attributes and MFA state.
type ResolveUserRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Context                    *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username                   string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend                    *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Attributes                 *AttributeRequest      `protobuf:"bytes,4,opt,name=attributes,proto3" json:"attributes,omitempty"`
	IncludeMfaState            bool                   `protobuf:"varint,5,opt,name=include_mfa_state,json=includeMfaState,proto3" json:"include_mfa_state,omitempty"`
	IncludeWebauthnCredentials bool                   `protobuf:"varint,6,opt,name=include_webauthn_credentials,json=includeWebauthnCredentials,proto3" json:"include_webauthn_credentials,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *ResolveUserRequest) Reset() {
	*x = ResolveUserRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveUserRequest) ProtoMessage() {}

func (x *ResolveUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveUserRequest.ProtoReflect.Descriptor instead.
func (*ResolveUserRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{5}
}

func (x *ResolveUserRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *ResolveUserRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ResolveUserRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *ResolveUserRequest) GetAttributes() *AttributeRequest {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *ResolveUserRequest) GetIncludeMfaState() bool {
	if x != nil {
		return x.IncludeMfaState
	}
	return false
}

func (x *ResolveUserRequest) GetIncludeWebauthnCredentials() bool {
	if x != nil {
		return x.IncludeWebauthnCredentials
	}
	return false
}

// UserSnapshotResponse returns a released user snapshot and attribute release diagnostics.
type UserSnapshotResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	User              *UserSnapshot          `protobuf:"bytes,2,opt,name=user,proto3" json:"user,omitempty"`
	MissingAttributes []string               `protobuf:"bytes,3,rep,name=missing_attributes,json=missingAttributes,proto3" json:"missing_attributes,omitempty"`
	DeniedAttributes  []string               `protobuf:"bytes,4,rep,name=denied_attributes,json=deniedAttributes,proto3" json:"denied_attributes,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UserSnapshotResponse) Reset() {
	*x = UserSnapshotResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSnapshotResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSnapshotResponse) ProtoMessage() {}

func (x *UserSnapshotResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSnapshotResponse.ProtoReflect.Descriptor instead.
func (*UserSnapshotResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{6}
}

func (x *UserSnapshotResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UserSnapshotResponse) GetUser() *UserSnapshot {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *UserSnapshotResponse) GetMissingAttributes() []string {
	if x != nil {
		return x.MissingAttributes
	}
	return nil
}

func (x *UserSnapshotResponse) GetDeniedAttributes() []string {
	if x != nil {
		return x.DeniedAttributes
	}
	return nil
}

// GetMFAStateRequest loads public MFA state for a user.
type GetMFAStateRequest struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Context                    *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username                   string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend                    *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	IncludeWebauthnCredentials bool                   `protobuf:"varint,4,opt,name=include_webauthn_credentials,json=includeWebauthnCredentials,proto3" json:"include_webauthn_credentials,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *GetMFAStateRequest) Reset() {
	*x = GetMFAStateRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMFAStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMFAStateRequest) ProtoMessage() {}

func (x *GetMFAStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMFAStateRequest.ProtoReflect.Descriptor instead.
func (*GetMFAStateRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{7}
}

func (x *GetMFAStateRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetMFAStateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetMFAStateRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *GetMFAStateRequest) GetIncludeWebauthnCredentials() bool {
	if x != nil {
		return x.IncludeWebauthnCredentials
	}
	return false
}

// MFAStateResponse returns public MFA state and the effective backend reference.
type MFAStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Mfa           *MFAState              `protobuf:"bytes,2,opt,name=mfa,proto3" json:"mfa,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFAStateResponse) Reset() {
	*x = MFAStateResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAStateResponse) ProtoMessage() {}

func (x *MFAStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAStateResponse.ProtoReflect.Descriptor instead.
func (*MFAStateResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{8}
}

func (x *MFAStateResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MFAStateResponse) GetMfa() *MFAState {
	if x != nil {
		return x.Mfa
	}
	return nil
}

func (x *MFAStateResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// BeginTOTPRegistrationRequest starts a TOTP registration operation.
type BeginTOTPRegistrationRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BeginTOTPRegistrationRequest) Reset() {
	*x = BeginTOTPRegistrationRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTOTPRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTOTPRegistrationRequest) ProtoMessage() {}

func (x *BeginTOTPRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTOTPRegistrationRequest.ProtoReflect.Descriptor instead.
func (*BeginTOTPRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{9}
}

func (x *BeginTOTPRegistrationRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *BeginTOTPRegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *BeginTOTPRegistrationRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *BeginTOTPRegistrationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// BeginTOTPRegistrationResponse returns the one-time TOTP setup material.
type BeginTOTPRegistrationResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Status                *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	PendingRegistrationId string                 `protobuf:"bytes,2,opt,name=pending_registration_id,json=pendingRegistrationId,proto3" json:"pending_registration_id,omitempty"`
	TotpSecret            string                 `protobuf:"bytes,3,opt,name=totp_secret,json=totpSecret,proto3" json:"totp_secret,omitempty"`
	OtpauthUrl            string                 `protobuf:"bytes,4,opt,name=otpauth_url,json=otpauthUrl,proto3" json:"otpauth_url,omitempty"`
	ExpiresAt             *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Backend               *v1.BackendRef         `protobuf:"bytes,6,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *BeginTOTPRegistrationResponse) Reset() {
	*x = BeginTOTPRegistrationResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BeginTOTPRegistrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BeginTOTPRegistrationResponse) ProtoMessage() {}

func (x *BeginTOTPRegistrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BeginTOTPRegistrationResponse.ProtoReflect.Descriptor instead.
func (*BeginTOTPRegistrationResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{10}
}

func (x *BeginTOTPRegistrationResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *BeginTOTPRegistrationResponse) GetPendingRegistrationId() string {
	if x != nil {
		return x.PendingRegistrationId
	}
	return ""
}

func (x *BeginTOTPRegistrationResponse) GetTotpSecret() string {
	if x != nil {
		return x.TotpSecret
	}
	return ""
}

func (x *BeginTOTPRegistrationResponse) GetOtpauthUrl() string {
	if x != nil {
		return x.OtpauthUrl
	}
	return ""
}

func (x *BeginTOTPRegistrationResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *BeginTOTPRegistrationResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// FinishTOTPRegistrationRequest completes a pending TOTP registration.
type FinishTOTPRegistrationRequest struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Context               *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username              string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend               *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	PendingRegistrationId string                 `protobuf:"bytes,4,opt,name=pending_registration_id,json=pendingRegistrationId,proto3" json:"pending_registration_id,omitempty"`
	Code                  string                 `protobuf:"bytes,5,opt,name=code,proto3" json:"code,omitempty"`
	IdempotencyKey        string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *FinishTOTPRegistrationRequest) Reset() {
	*x = FinishTOTPRegistrationRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinishTOTPRegistrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinishTOTPRegistrationRequest) ProtoMessage() {}

func (x *FinishTOTPRegistrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinishTOTPRegistrationRequest.ProtoReflect.Descriptor instead.
func (*FinishTOTPRegistrationRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{11}
}

func (x *FinishTOTPRegistrationRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *FinishTOTPRegistrationRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *FinishTOTPRegistrationRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *FinishTOTPRegistrationRequest) GetPendingRegistrationId() string {
	if x != nil {
		return x.PendingRegistrationId
	}
	return ""
}

func (x *FinishTOTPRegistrationRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *FinishTOTPRegistrationRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// VerifyTOTPRequest verifies a TOTP code.
type VerifyTOTPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Code          string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTOTPRequest) Reset() {
	*x = VerifyTOTPRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTOTPRequest) ProtoMessage() {}

func (x *VerifyTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyTOTPRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{12}
}

func (x *VerifyTOTPRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *VerifyTOTPRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *VerifyTOTPRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *VerifyTOTPRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

// VerifyTOTPResponse reports whether the supplied TOTP code is valid.
type VerifyTOTPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Valid         bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyTOTPResponse) Reset() {
	*x = VerifyTOTPResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyTOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyTOTPResponse) ProtoMessage() {}

func (x *VerifyTOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyTOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyTOTPResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyTOTPResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *VerifyTOTPResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyTOTPResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// DeleteTOTPRequest deletes a user's TOTP state.
type DeleteTOTPRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteTOTPRequest) Reset() {
	*x = DeleteTOTPRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteTOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteTOTPRequest) ProtoMessage() {}

func (x *DeleteTOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteTOTPRequest.ProtoReflect.Descriptor instead.
func (*DeleteTOTPRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteTOTPRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteTOTPRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteTOTPRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *DeleteTOTPRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// GenerateRecoveryCodesRequest creates a fresh recovery-code set.
type GenerateRecoveryCodesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Count          uint32                 `protobuf:"varint,4,opt,name=count,proto3" json:"count,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateRecoveryCodesRequest) Reset() {
	*x = GenerateRecoveryCodesRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecoveryCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecoveryCodesRequest) ProtoMessage() {}

func (x *GenerateRecoveryCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecoveryCodesRequest.ProtoReflect.Descriptor instead.
func (*GenerateRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{15}
}

func (x *GenerateRecoveryCodesRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GenerateRecoveryCodesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GenerateRecoveryCodesRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *GenerateRecoveryCodesRequest) GetCount() uint32 {
	if x != nil {
		return x.Count
	}
	return 0
}

func (x *GenerateRecoveryCodesRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// GenerateRecoveryCodesResponse returns recovery codes exactly once.
type GenerateRecoveryCodesResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Status            *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Codes             []string               `protobuf:"bytes,2,rep,name=codes,proto3" json:"codes,omitempty"`
	RecoveryCodeCount uint32                 `protobuf:"varint,3,opt,name=recovery_code_count,json=recoveryCodeCount,proto3" json:"recovery_code_count,omitempty"`
	Backend           *v1.BackendRef         `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GenerateRecoveryCodesResponse) Reset() {
	*x = GenerateRecoveryCodesResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRecoveryCodesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRecoveryCodesResponse) ProtoMessage() {}

func (x *GenerateRecoveryCodesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRecoveryCodesResponse.ProtoReflect.Descriptor instead.
func (*GenerateRecoveryCodesResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{16}
}

func (x *GenerateRecoveryCodesResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *GenerateRecoveryCodesResponse) GetCodes() []string {
	if x != nil {
		return x.Codes
	}
	return nil
}

func (x *GenerateRecoveryCodesResponse) GetRecoveryCodeCount() uint32 {
	if x != nil {
		return x.RecoveryCodeCount
	}
	return 0
}

func (x *GenerateRecoveryCodesResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// UseRecoveryCodeRequest consumes one recovery code.
type UseRecoveryCodeRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Code           string                 `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UseRecoveryCodeRequest) Reset() {
	*x = UseRecoveryCodeRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseRecoveryCodeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseRecoveryCodeRequest) ProtoMessage() {}

func (x *UseRecoveryCodeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseRecoveryCodeRequest.ProtoReflect.Descriptor instead.
func (*UseRecoveryCodeRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{17}
}

func (x *UseRecoveryCodeRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UseRecoveryCodeRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UseRecoveryCodeRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *UseRecoveryCodeRequest) GetCode() string {
	if x != nil {
		return x.Code
	}
	return ""
}

func (x *UseRecoveryCodeRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// UseRecoveryCodeResponse reports recovery-code verification state.
type UseRecoveryCodeResponse struct {
	state                      protoimpl.MessageState `protogen:"open.v1"`
	Status                     *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Valid                      bool                   `protobuf:"varint,2,opt,name=valid,proto3" json:"valid,omitempty"`
	RemainingRecoveryCodeCount uint32                 `protobuf:"varint,3,opt,name=remaining_recovery_code_count,json=remainingRecoveryCodeCount,proto3" json:"remaining_recovery_code_count,omitempty"`
	Backend                    *v1.BackendRef         `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields              protoimpl.UnknownFields
	sizeCache                  protoimpl.SizeCache
}

func (x *UseRecoveryCodeResponse) Reset() {
	*x = UseRecoveryCodeResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseRecoveryCodeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseRecoveryCodeResponse) ProtoMessage() {}

func (x *UseRecoveryCodeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseRecoveryCodeResponse.ProtoReflect.Descriptor instead.
func (*UseRecoveryCodeResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{18}
}

func (x *UseRecoveryCodeResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *UseRecoveryCodeResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *UseRecoveryCodeResponse) GetRemainingRecoveryCodeCount() uint32 {
	if x != nil {
		return x.RemainingRecoveryCodeCount
	}
	return 0
}

func (x *UseRecoveryCodeResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// DeleteRecoveryCodesRequest deletes all recovery codes for a user.
type DeleteRecoveryCodesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteRecoveryCodesRequest) Reset() {
	*x = DeleteRecoveryCodesRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRecoveryCodesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRecoveryCodesRequest) ProtoMessage() {}

func (x *DeleteRecoveryCodesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRecoveryCodesRequest.ProtoReflect.Descriptor instead.
func (*DeleteRecoveryCodesRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{19}
}

func (x *DeleteRecoveryCodesRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteRecoveryCodesRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteRecoveryCodesRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *DeleteRecoveryCodesRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// GetWebAuthnCredentialsRequest loads public WebAuthn credentials for ceremony setup.
type GetWebAuthnCredentialsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Context       *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWebAuthnCredentialsRequest) Reset() {
	*x = GetWebAuthnCredentialsRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWebAuthnCredentialsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWebAuthnCredentialsRequest) ProtoMessage() {}

func (x *GetWebAuthnCredentialsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWebAuthnCredentialsRequest.ProtoReflect.Descriptor instead.
func (*GetWebAuthnCredentialsRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{20}
}

func (x *GetWebAuthnCredentialsRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *GetWebAuthnCredentialsRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetWebAuthnCredentialsRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// WebAuthnCredentialsResponse returns public WebAuthn credentials.
type WebAuthnCredentialsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Credentials   []*WebAuthnCredential  `protobuf:"bytes,2,rep,name=credentials,proto3" json:"credentials,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WebAuthnCredentialsResponse) Reset() {
	*x = WebAuthnCredentialsResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WebAuthnCredentialsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WebAuthnCredentialsResponse) ProtoMessage() {}

func (x *WebAuthnCredentialsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WebAuthnCredentialsResponse.ProtoReflect.Descriptor instead.
func (*WebAuthnCredentialsResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{21}
}

func (x *WebAuthnCredentialsResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *WebAuthnCredentialsResponse) GetCredentials() []*WebAuthnCredential {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *WebAuthnCredentialsResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

// SaveWebAuthnCredentialRequest persists a newly registered WebAuthn credential.
type SaveWebAuthnCredentialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	Credential     *WebAuthnCredential    `protobuf:"bytes,4,opt,name=credential,proto3" json:"credential,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SaveWebAuthnCredentialRequest) Reset() {
	*x = SaveWebAuthnCredentialRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveWebAuthnCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveWebAuthnCredentialRequest) ProtoMessage() {}

func (x *SaveWebAuthnCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveWebAuthnCredentialRequest.ProtoReflect.Descriptor instead.
func (*SaveWebAuthnCredentialRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{22}
}

func (x *SaveWebAuthnCredentialRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *SaveWebAuthnCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *SaveWebAuthnCredentialRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *SaveWebAuthnCredentialRequest) GetCredential() *WebAuthnCredential {
	if x != nil {
		return x.Credential
	}
	return nil
}

func (x *SaveWebAuthnCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// UpdateWebAuthnCredentialRequest compares and updates a persisted WebAuthn credential.
type UpdateWebAuthnCredentialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	OldCredential  *WebAuthnCredential    `protobuf:"bytes,4,opt,name=old_credential,json=oldCredential,proto3" json:"old_credential,omitempty"`
	NewCredential  *WebAuthnCredential    `protobuf:"bytes,5,opt,name=new_credential,json=newCredential,proto3" json:"new_credential,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateWebAuthnCredentialRequest) Reset() {
	*x = UpdateWebAuthnCredentialRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateWebAuthnCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateWebAuthnCredentialRequest) ProtoMessage() {}

func (x *UpdateWebAuthnCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateWebAuthnCredentialRequest.ProtoReflect.Descriptor instead.
func (*UpdateWebAuthnCredentialRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{23}
}

func (x *UpdateWebAuthnCredentialRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *UpdateWebAuthnCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateWebAuthnCredentialRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *UpdateWebAuthnCredentialRequest) GetOldCredential() *WebAuthnCredential {
	if x != nil {
		return x.OldCredential
	}
	return nil
}

func (x *UpdateWebAuthnCredentialRequest) GetNewCredential() *WebAuthnCredential {
	if x != nil {
		return x.NewCredential
	}
	return nil
}

func (x *UpdateWebAuthnCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// DeleteWebAuthnCredentialRequest deletes a WebAuthn credential by credential ID.
type DeleteWebAuthnCredentialRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Context        *RequestContext        `protobuf:"bytes,1,opt,name=context,proto3" json:"context,omitempty"`
	Username       string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	Backend        *v1.BackendRef         `protobuf:"bytes,3,opt,name=backend,proto3" json:"backend,omitempty"`
	CredentialId   []byte                 `protobuf:"bytes,4,opt,name=credential_id,json=credentialId,proto3" json:"credential_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,5,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeleteWebAuthnCredentialRequest) Reset() {
	*x = DeleteWebAuthnCredentialRequest{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteWebAuthnCredentialRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteWebAuthnCredentialRequest) ProtoMessage() {}

func (x *DeleteWebAuthnCredentialRequest) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteWebAuthnCredentialRequest.ProtoReflect.Descriptor instead.
func (*DeleteWebAuthnCredentialRequest) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{24}
}

func (x *DeleteWebAuthnCredentialRequest) GetContext() *RequestContext {
	if x != nil {
		return x.Context
	}
	return nil
}

func (x *DeleteWebAuthnCredentialRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *DeleteWebAuthnCredentialRequest) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

func (x *DeleteWebAuthnCredentialRequest) GetCredentialId() []byte {
	if x != nil {
		return x.CredentialId
	}
	return nil
}

func (x *DeleteWebAuthnCredentialRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

// MFAWriteResponse returns the outcome for a mutating MFA operation.
type MFAWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        *v1.OperationStatus    `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Changed       bool                   `protobuf:"varint,2,opt,name=changed,proto3" json:"changed,omitempty"`
	Mfa           *MFAState              `protobuf:"bytes,3,opt,name=mfa,proto3" json:"mfa,omitempty"`
	Backend       *v1.BackendRef         `protobuf:"bytes,4,opt,name=backend,proto3" json:"backend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MFAWriteResponse) Reset() {
	*x = MFAWriteResponse{}
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MFAWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MFAWriteResponse) ProtoMessage() {}

func (x *MFAWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MFAWriteResponse.ProtoReflect.Descriptor instead.
func (*MFAWriteResponse) Descriptor() ([]byte, []int) {
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP(), []int{25}
}

func (x *MFAWriteResponse) GetStatus() *v1.OperationStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

func (x *MFAWriteResponse) GetChanged() bool {
	if x != nil {
		return x.Changed
	}
	return false
}

func (x *MFAWriteResponse) GetMfa() *MFAState {
	if x != nil {
		return x.Mfa
	}
	return nil
}

func (x *MFAWriteResponse) GetBackend() *v1.BackendRef {
	if x != nil {
		return x.Backend
	}
	return nil
}

var File_server_grpcapi_identity_v1_identity_backend_proto protoreflect.FileDescriptor

const file_server_grpcapi_identity_v1_identity_backend_proto_rawDesc = "" +
	"\n" +
	"1server/grpcapi/identity/v1/identity_backend.proto\x12\x15nauthilus.identity.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a%server/grpcapi/common/v1/common.proto\"\xf1\n" +
	"\n" +
	"\x0eRequestContext\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1b\n" +
	"\tclient_ip\x18\x02 \x01(\tR\bclientIp\x12\x1f\n" +
	"\vclient_port\x18\x03 \x01(\tR\n" +
	"clientPort\x12'\n" +
	"\x0fclient_hostname\x18\x04 \x01(\tR\x0eclientHostname\x12\x1b\n" +
	"\tclient_id\x18\x05 \x01(\tR\bclientId\x12.\n" +
	"\x13external_session_id\x18\x06 \x01(\tR\x11externalSessionId\x12\x1d\n" +
	"\n" +
	"user_agent\x18\a \x01(\tR\tuserAgent\x12\x19\n" +
	"\blocal_ip\x18\b \x01(\tR\alocalIp\x12\x1d\n" +
	"\n" +
	"local_port\x18\t \x01(\tR\tlocalPort\x12\x1a\n" +
	"\bprotocol\x18\n" +
	" \x01(\tR\bprotocol\x12\x16\n" +
	"\x06method\x18\v \x01(\tR\x06method\x12\x10\n" +
	"\x03ssl\x18\f \x01(\tR\x03ssl\x12$\n" +
	"\x0essl_session_id\x18\r \x01(\tR\fsslSessionId\x12*\n" +
	"\x11ssl_client_verify\x18\x0e \x01(\tR\x0fsslClientVerify\x12\"\n" +
	"\rssl_client_dn\x18\x0f \x01(\tR\vsslClientDn\x12\"\n" +
	"\rssl_client_cn\x18\x10 \x01(\tR\vsslClientCn\x12\x1d\n" +
	"\n" +
	"ssl_issuer\x18\x11 \x01(\tR\tsslIssuer\x120\n" +
	"\x14ssl_client_notbefore\x18\x12 \x01(\tR\x12sslClientNotbefore\x12.\n" +
	"\x13ssl_client_notafter\x18\x13 \x01(\tR\x11sslClientNotafter\x12$\n" +
	"\x0essl_subject_dn\x18\x14 \x01(\tR\fsslSubjectDn\x12\"\n" +
	"\rssl_issuer_dn\x18\x15 \x01(\tR\vsslIssuerDn\x121\n" +
	"\x15ssl_client_subject_dn\x18\x16 \x01(\tR\x12sslClientSubjectDn\x12/\n" +
	"\x14ssl_client_issuer_dn\x18\x17 \x01(\tR\x11sslClientIssuerDn\x12!\n" +
	"\fssl_protocol\x18\x18 \x01(\tR\vsslProtocol\x12\x1d\n" +
	"\n" +
	"ssl_cipher\x18\x19 \x01(\tR\tsslCipher\x12\x1d\n" +
	"\n" +
	"ssl_serial\x18\x1a \x01(\tR\tsslSerial\x12'\n" +
	"\x0fssl_fingerprint\x18\x1b \x01(\tR\x0esslFingerprint\x12\x19\n" +
	"\boidc_cid\x18\x1c \x01(\tR\aoidcCid\x12$\n" +
	"\x0esaml_entity_id\x18\x1d \x01(\tR\fsamlEntityId\x12,\n" +
	"\x12auth_login_attempt\x18\x1e \x01(\rR\x10authLoginAttempt\x12O\n" +
	"\bmetadata\x18\x1f \x03(\v23.nauthilus.identity.v1.RequestContext.MetadataEntryR\bmetadata\x12#\n" +
	"\redge_instance\x18  \x01(\tR\fedgeInstance\x12&\n" +
	"\x0fedge_request_id\x18! \x01(\tR\redgeRequestId\x12-\n" +
	"\x12requested_language\x18\" \x01(\tR\x11requestedLanguage\x1aa\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.nauthilus.common.v1.AttributeValuesR\x05value:\x028\x01\"\xde\x01\n" +
	"\x10AttributeRequest\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\x12:\n" +
	"\x19include_standard_identity\x18\x02 \x01(\bR\x17includeStandardIdentity\x12%\n" +
	"\x0einclude_groups\x18\x03 \x01(\bR\rincludeGroups\x12*\n" +
	"\x11include_group_dns\x18\x04 \x01(\bR\x0fincludeGroupDns\x12%\n" +
	"\x0ereport_missing\x18\x05 \x01(\bR\rreportMissing\"\xea\x03\n" +
	"\fUserSnapshot\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x18\n" +
	"\aaccount\x18\x02 \x01(\tR\aaccount\x12$\n" +
	"\x0eunique_user_id\x18\x03 \x01(\tR\funiqueUserId\x12!\n" +
	"\fdisplay_name\x18\x04 \x01(\tR\vdisplayName\x12S\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v23.nauthilus.identity.v1.UserSnapshot.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06groups\x18\x06 \x03(\tR\x06groups\x12\x1b\n" +
	"\tgroup_dns\x18\a \x03(\tR\bgroupDns\x129\n" +
	"\abackend\x18\b \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x121\n" +
	"\x03mfa\x18\t \x01(\v2\x1f.nauthilus.identity.v1.MFAStateR\x03mfa\x1ac\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.nauthilus.common.v1.AttributeValuesR\x05value:\x028\x01\"\x81\x02\n" +
	"\bMFAState\x12\x19\n" +
	"\bhas_totp\x18\x01 \x01(\bR\ahasTotp\x12.\n" +
	"\x13recovery_code_count\x18\x02 \x01(\rR\x11recoveryCodeCount\x12!\n" +
	"\fhas_webauthn\x18\x03 \x01(\bR\vhasWebauthn\x12\\\n" +
	"\x14webauthn_credentials\x18\x04 \x03(\v2).nauthilus.identity.v1.WebAuthnCredentialR\x13webauthnCredentials\x12)\n" +
	"\x10preferred_method\x18\x05 \x01(\tR\x0fpreferredMethod\"\xf6\x02\n" +
	"\x12WebAuthnCredential\x12#\n" +
	"\rcredential_id\x18\x01 \x01(\fR\fcredentialId\x12\x1d\n" +
	"\n" +
	"public_key\x18\x02 \x01(\fR\tpublicKey\x12\x1d\n" +
	"\n" +
	"sign_count\x18\x03 \x01(\rR\tsignCount\x12\x1e\n" +
	"\n" +
	"transports\x18\x04 \x03(\tR\n" +
	"transports\x12'\n" +
	"\x0fbackup_eligible\x18\x05 \x01(\bR\x0ebackupEligible\x12!\n" +
	"\fbackup_state\x18\x06 \x01(\bR\vbackupState\x12)\n" +
	"\x10attestation_type\x18\a \x01(\tR\x0fattestationType\x12\x12\n" +
	"\x04name\x18\b \x01(\tR\x04name\x127\n" +
	"\tlast_used\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\blastUsed\x12\x19\n" +
	"\braw_json\x18\n" +
	" \x01(\tR\arawJson\"\xe3\x02\n" +
	"\x12ResolveUserRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12G\n" +
	"\n" +
	"attributes\x18\x04 \x01(\v2'.nauthilus.identity.v1.AttributeRequestR\n" +
	"attributes\x12*\n" +
	"\x11include_mfa_state\x18\x05 \x01(\bR\x0fincludeMfaState\x12@\n" +
	"\x1cinclude_webauthn_credentials\x18\x06 \x01(\bR\x1aincludeWebauthnCredentials\"\xe9\x01\n" +
	"\x14UserSnapshotResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x127\n" +
	"\x04user\x18\x02 \x01(\v2#.nauthilus.identity.v1.UserSnapshotR\x04user\x12-\n" +
	"\x12missing_attributes\x18\x03 \x03(\tR\x11missingAttributes\x12+\n" +
	"\x11denied_attributes\x18\x04 \x03(\tR\x10deniedAttributes\"\xee\x01\n" +
	"\x12GetMFAStateRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12@\n" +
	"\x1cinclude_webauthn_credentials\x18\x04 \x01(\bR\x1aincludeWebauthnCredentials\"\xbe\x01\n" +
	"\x10MFAStateResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x121\n" +
	"\x03mfa\x18\x02 \x01(\v2\x1f.nauthilus.identity.v1.MFAStateR\x03mfa\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xdf\x01\n" +
	"\x1cBeginTOTPRegistrationRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xcd\x02\n" +
	"\x1dBeginTOTPRegistrationResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x126\n" +
	"\x17pending_registration_id\x18\x02 \x01(\tR\x15pendingRegistrationId\x12\x1f\n" +
	"\vtotp_secret\x18\x03 \x01(\tR\n" +
	"totpSecret\x12\x1f\n" +
	"\votpauth_url\x18\x04 \x01(\tR\n" +
	"otpauthUrl\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x129\n" +
	"\abackend\x18\x06 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xac\x02\n" +
	"\x1dFinishTOTPRegistrationRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x126\n" +
	"\x17pending_registration_id\x18\x04 \x01(\tR\x15pendingRegistrationId\x12\x12\n" +
	"\x04code\x18\x05 \x01(\tR\x04code\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\xbf\x01\n" +
	"\x11VerifyTOTPRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\"\xa3\x01\n" +
	"\x12VerifyTOTPResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xd4\x01\n" +
	"\x11DeleteTOTPRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xf5\x01\n" +
	"\x1cGenerateRecoveryCodesRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12\x14\n" +
	"\x05count\x18\x04 \x01(\rR\x05count\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xde\x01\n" +
	"\x1dGenerateRecoveryCodesResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x12\x14\n" +
	"\x05codes\x18\x02 \x03(\tR\x05codes\x12.\n" +
	"\x13recovery_code_count\x18\x03 \x01(\rR\x11recoveryCodeCount\x129\n" +
	"\abackend\x18\x04 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xed\x01\n" +
	"\x16UseRecoveryCodeRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12\x12\n" +
	"\x04code\x18\x04 \x01(\tR\x04code\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xeb\x01\n" +
	"\x17UseRecoveryCodeResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x12\x14\n" +
	"\x05valid\x18\x02 \x01(\bR\x05valid\x12A\n" +
	"\x1dremaining_recovery_code_count\x18\x03 \x01(\rR\x1aremainingRecoveryCodeCount\x129\n" +
	"\abackend\x18\x04 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xdd\x01\n" +
	"\x1aDeleteRecoveryCodesRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\"\xb7\x01\n" +
	"\x1dGetWebAuthnCredentialsRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xe3\x01\n" +
	"\x1bWebAuthnCredentialsResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x12K\n" +
	"\vcredentials\x18\x02 \x03(\v2).nauthilus.identity.v1.WebAuthnCredentialR\vcredentials\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\"\xab\x02\n" +
	"\x1dSaveWebAuthnCredentialRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12I\n" +
	"\n" +
	"credential\x18\x04 \x01(\v2).nauthilus.identity.v1.WebAuthnCredentialR\n" +
	"credential\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\x86\x03\n" +
	"\x1fUpdateWebAuthnCredentialRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12P\n" +
	"\x0eold_credential\x18\x04 \x01(\v2).nauthilus.identity.v1.WebAuthnCredentialR\roldCredential\x12P\n" +
	"\x0enew_credential\x18\x05 \x01(\v2).nauthilus.identity.v1.WebAuthnCredentialR\rnewCredential\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"\x87\x02\n" +
	"\x1fDeleteWebAuthnCredentialRequest\x12?\n" +
	"\acontext\x18\x01 \x01(\v2%.nauthilus.identity.v1.RequestContextR\acontext\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x129\n" +
	"\abackend\x18\x03 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend\x12#\n" +
	"\rcredential_id\x18\x04 \x01(\fR\fcredentialId\x12'\n" +
	"\x0fidempotency_key\x18\x05 \x01(\tR\x0eidempotencyKey\"\xd8\x01\n" +
	"\x10MFAWriteResponse\x12<\n" +
	"\x06status\x18\x01 \x01(\v2$.nauthilus.common.v1.OperationStatusR\x06status\x12\x18\n" +
	"\achanged\x18\x02 \x01(\bR\achanged\x121\n" +
	"\x03mfa\x18\x03 \x01(\v2\x1f.nauthilus.identity.v1.MFAStateR\x03mfa\x129\n" +
	"\abackend\x18\x04 \x01(\v2\x1f.nauthilus.common.v1.BackendRefR\abackend2\x86\f\n" +
	"\x16IdentityBackendService\x12e\n" +
	"\vResolveUser\x12).nauthilus.identity.v1.ResolveUserRequest\x1a+.nauthilus.identity.v1.UserSnapshotResponse\x12a\n" +
	"\vGetMFAState\x12).nauthilus.identity.v1.GetMFAStateRequest\x1a'.nauthilus.identity.v1.MFAStateResponse\x12\x82\x01\n" +
	"\x15BeginTOTPRegistration\x123.nauthilus.identity.v1.BeginTOTPRegistrationRequest\x1a4.nauthilus.identity.v1.BeginTOTPRegistrationResponse\x12w\n" +
	"\x16FinishTOTPRegistration\x124.nauthilus.identity.v1.FinishTOTPRegistrationRequest\x1a'.nauthilus.identity.v1.MFAWriteResponse\x12a\n" +
	"\n" +
	"VerifyTOTP\x12(.nauthilus.identity.v1.VerifyTOTPRequest\x1a).nauthilus.identity.v1.VerifyTOTPResponse\x12_\n" +
	"\n" +
	"DeleteTOTP\x12(.nauthilus.identity.v1.DeleteTOTPRequest\x1a'.nauthilus.identity.v1.MFAWriteResponse\x12\x82\x01\n" +
	"\x15GenerateRecoveryCodes\x123.nauthilus.identity.v1.GenerateRecoveryCodesRequest\x1a4.nauthilus.identity.v1.GenerateRecoveryCodesResponse\x12p\n" +
	"\x0fUseRecoveryCode\x12-.nauthilus.identity.v1.UseRecoveryCodeRequest\x1a..nauthilus.identity.v1.UseRecoveryCodeResponse\x12q\n" +
	"\x13DeleteRecoveryCodes\x121.nauthilus.identity.v1.DeleteRecoveryCodesRequest\x1a'.nauthilus.identity.v1.MFAWriteResponse\x12\x82\x01\n" +
	"\x16GetWebAuthnCredentials\x124.nauthilus.identity.v1.GetWebAuthnCredentialsRequest\x1a2.nauthilus.identity.v1.WebAuthnCredentialsResponse\x12w\n" +
	"\x16SaveWebAuthnCredential\x124.nauthilus.identity.v1.SaveWebAuthnCredentialRequest\x1a'.nauthilus.identity.v1.MFAWriteResponse\x12{\n" +
	"\x18UpdateWebAuthnCredential\x126.nauthilus.identity.v1.UpdateWebAuthnCredentialRequest\x1a'.nauthilus.identity.v1.MFAWriteResponse\x12{\n" +
	"\x18DeleteWebAuthnCredential\x126.nauthilus.identity.v1.DeleteWebAuthnCredentialRequest\x1a'.nauthilus.identity.v1.MFAWriteResponseBIZGgithub.com/croessner/nauthilus/v3/server/grpcapi/identity/v1;identityv1b\x06proto3"

var (
	file_server_grpcapi_identity_v1_identity_backend_proto_rawDescOnce sync.Once
	file_server_grpcapi_identity_v1_identity_backend_proto_rawDescData []byte
)

func file_server_grpcapi_identity_v1_identity_backend_proto_rawDescGZIP() []byte {
	file_server_grpcapi_identity_v1_identity_backend_proto_rawDescOnce.Do(func() {
		file_server_grpcapi_identity_v1_identity_backend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_server_grpcapi_identity_v1_identity_backend_proto_rawDesc), len(file_server_grpcapi_identity_v1_identity_backend_proto_rawDesc)))
	})
	return file_server_grpcapi_identity_v1_identity_backend_proto_rawDescData
}

var file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes = make([]protoimpl.MessageInfo, 28)
var file_server_grpcapi_identity_v1_identity_backend_proto_goTypes = []any{
	(*RequestContext)(nil),                  // 0: nauthilus.identity.v1.RequestContext
	(*AttributeRequest)(nil),                // 1: nauthilus.identity.v1.AttributeRequest
	(*UserSnapshot)(nil),                    // 2: nauthilus.identity.v1.UserSnapshot
	(*MFAState)(nil),                        // 3: nauthilus.identity.v1.MFAState
	(*WebAuthnCredential)(nil),              // 4: nauthilus.identity.v1.WebAuthnCredential
	(*ResolveUserRequest)(nil),              // 5: nauthilus.identity.v1.ResolveUserRequest
	(*UserSnapshotResponse)(nil),            // 6: nauthilus.identity.v1.UserSnapshotResponse
	(*GetMFAStateRequest)(nil),              // 7: nauthilus.identity.v1.GetMFAStateRequest
	(*MFAStateResponse)(nil),                // 8: nauthilus.identity.v1.MFAStateResponse
	(*BeginTOTPRegistrationRequest)(nil),    // 9: nauthilus.identity.v1.BeginTOTPRegistrationRequest
	(*BeginTOTPRegistrationResponse)(nil),   // 10: nauthilus.identity.v1.BeginTOTPRegistrationResponse
	(*FinishTOTPRegistrationRequest)(nil),   // 11: nauthilus.identity.v1.FinishTOTPRegistrationRequest
	(*VerifyTOTPRequest)(nil),               // 12: nauthilus.identity.v1.VerifyTOTPRequest
	(*VerifyTOTPResponse)(nil),              // 13: nauthilus.identity.v1.VerifyTOTPResponse
	(*DeleteTOTPRequest)(nil),               // 14: nauthilus.identity.v1.DeleteTOTPRequest
	(*GenerateRecoveryCodesRequest)(nil),    // 15: nauthilus.identity.v1.GenerateRecoveryCodesRequest
	(*GenerateRecoveryCodesResponse)(nil),   // 16: nauthilus.identity.v1.GenerateRecoveryCodesResponse
	(*UseRecoveryCodeRequest)(nil),          // 17: nauthilus.identity.v1.UseRecoveryCodeRequest
	(*UseRecoveryCodeResponse)(nil),         // 18: nauthilus.identity.v1.UseRecoveryCodeResponse
	(*DeleteRecoveryCodesRequest)(nil),      // 19: nauthilus.identity.v1.DeleteRecoveryCodesRequest
	(*GetWebAuthnCredentialsRequest)(nil),   // 20: nauthilus.identity.v1.GetWebAuthnCredentialsRequest
	(*WebAuthnCredentialsResponse)(nil),     // 21: nauthilus.identity.v1.WebAuthnCredentialsResponse
	(*SaveWebAuthnCredentialRequest)(nil),   // 22: nauthilus.identity.v1.SaveWebAuthnCredentialRequest
	(*UpdateWebAuthnCredentialRequest)(nil), // 23: nauthilus.identity.v1.UpdateWebAuthnCredentialRequest
	(*DeleteWebAuthnCredentialRequest)(nil), // 24: nauthilus.identity.v1.DeleteWebAuthnCredentialRequest
	(*MFAWriteResponse)(nil),                // 25: nauthilus.identity.v1.MFAWriteResponse
	nil,                                     // 26: nauthilus.identity.v1.RequestContext.MetadataEntry
	nil,                                     // 27: nauthilus.identity.v1.UserSnapshot.AttributesEntry
	(*v1.BackendRef)(nil),                   // 28: nauthilus.common.v1.BackendRef
	(*timestamppb.Timestamp)(nil),           // 29: google.protobuf.Timestamp
	(*v1.OperationStatus)(nil),              // 30: nauthilus.common.v1.OperationStatus
	(*v1.AttributeValues)(nil),              // 31: nauthilus.common.v1.AttributeValues
}
var file_server_grpcapi_identity_v1_identity_backend_proto_depIdxs = []int32{
	26, // 0: nauthilus.identity.v1.RequestContext.metadata:type_name -> nauthilus.identity.v1.RequestContext.MetadataEntry
	27, // 1: nauthilus.identity.v1.UserSnapshot.attributes:type_name -> nauthilus.identity.v1.UserSnapshot.AttributesEntry
	28, // 2: nauthilus.identity.v1.UserSnapshot.backend:type_name -> nauthilus.common.v1.BackendRef
	3,  // 3: nauthilus.identity.v1.UserSnapshot.mfa:type_name -> nauthilus.identity.v1.MFAState
	4,  // 4: nauthilus.identity.v1.MFAState.webauthn_credentials:type_name -> nauthilus.identity.v1.WebAuthnCredential
	29, // 5: nauthilus.identity.v1.WebAuthnCredential.last_used:type_name -> google.protobuf.Timestamp
	0,  // 6: nauthilus.identity.v1.ResolveUserRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 7: nauthilus.identity.v1.ResolveUserRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	1,  // 8: nauthilus.identity.v1.ResolveUserRequest.attributes:type_name -> nauthilus.identity.v1.AttributeRequest
	30, // 9: nauthilus.identity.v1.UserSnapshotResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	2,  // 10: nauthilus.identity.v1.UserSnapshotResponse.user:type_name -> nauthilus.identity.v1.UserSnapshot
	0,  // 11: nauthilus.identity.v1.GetMFAStateRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 12: nauthilus.identity.v1.GetMFAStateRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 13: nauthilus.identity.v1.MFAStateResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	3,  // 14: nauthilus.identity.v1.MFAStateResponse.mfa:type_name -> nauthilus.identity.v1.MFAState
	28, // 15: nauthilus.identity.v1.MFAStateResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 16: nauthilus.identity.v1.BeginTOTPRegistrationRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 17: nauthilus.identity.v1.BeginTOTPRegistrationRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 18: nauthilus.identity.v1.BeginTOTPRegistrationResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	29, // 19: nauthilus.identity.v1.BeginTOTPRegistrationResponse.expires_at:type_name -> google.protobuf.Timestamp
	28, // 20: nauthilus.identity.v1.BeginTOTPRegistrationResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 21: nauthilus.identity.v1.FinishTOTPRegistrationRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 22: nauthilus.identity.v1.FinishTOTPRegistrationRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 23: nauthilus.identity.v1.VerifyTOTPRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 24: nauthilus.identity.v1.VerifyTOTPRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 25: nauthilus.identity.v1.VerifyTOTPResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	28, // 26: nauthilus.identity.v1.VerifyTOTPResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 27: nauthilus.identity.v1.DeleteTOTPRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 28: nauthilus.identity.v1.DeleteTOTPRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 29: nauthilus.identity.v1.GenerateRecoveryCodesRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 30: nauthilus.identity.v1.GenerateRecoveryCodesRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 31: nauthilus.identity.v1.GenerateRecoveryCodesResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	28, // 32: nauthilus.identity.v1.GenerateRecoveryCodesResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 33: nauthilus.identity.v1.UseRecoveryCodeRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 34: nauthilus.identity.v1.UseRecoveryCodeRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 35: nauthilus.identity.v1.UseRecoveryCodeResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	28, // 36: nauthilus.identity.v1.UseRecoveryCodeResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 37: nauthilus.identity.v1.DeleteRecoveryCodesRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 38: nauthilus.identity.v1.DeleteRecoveryCodesRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 39: nauthilus.identity.v1.GetWebAuthnCredentialsRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 40: nauthilus.identity.v1.GetWebAuthnCredentialsRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 41: nauthilus.identity.v1.WebAuthnCredentialsResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	4,  // 42: nauthilus.identity.v1.WebAuthnCredentialsResponse.credentials:type_name -> nauthilus.identity.v1.WebAuthnCredential
	28, // 43: nauthilus.identity.v1.WebAuthnCredentialsResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	0,  // 44: nauthilus.identity.v1.SaveWebAuthnCredentialRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 45: nauthilus.identity.v1.SaveWebAuthnCredentialRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	4,  // 46: nauthilus.identity.v1.SaveWebAuthnCredentialRequest.credential:type_name -> nauthilus.identity.v1.WebAuthnCredential
	0,  // 47: nauthilus.identity.v1.UpdateWebAuthnCredentialRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 48: nauthilus.identity.v1.UpdateWebAuthnCredentialRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	4,  // 49: nauthilus.identity.v1.UpdateWebAuthnCredentialRequest.old_credential:type_name -> nauthilus.identity.v1.WebAuthnCredential
	4,  // 50: nauthilus.identity.v1.UpdateWebAuthnCredentialRequest.new_credential:type_name -> nauthilus.identity.v1.WebAuthnCredential
	0,  // 51: nauthilus.identity.v1.DeleteWebAuthnCredentialRequest.context:type_name -> nauthilus.identity.v1.RequestContext
	28, // 52: nauthilus.identity.v1.DeleteWebAuthnCredentialRequest.backend:type_name -> nauthilus.common.v1.BackendRef
	30, // 53: nauthilus.identity.v1.MFAWriteResponse.status:type_name -> nauthilus.common.v1.OperationStatus
	3,  // 54: nauthilus.identity.v1.MFAWriteResponse.mfa:type_name -> nauthilus.identity.v1.MFAState
	28, // 55: nauthilus.identity.v1.MFAWriteResponse.backend:type_name -> nauthilus.common.v1.BackendRef
	31, // 56: nauthilus.identity.v1.RequestContext.MetadataEntry.value:type_name -> nauthilus.common.v1.AttributeValues
	31, // 57: nauthilus.identity.v1.UserSnapshot.AttributesEntry.value:type_name -> nauthilus.common.v1.AttributeValues
	5,  // 58: nauthilus.identity.v1.IdentityBackendService.ResolveUser:input_type -> nauthilus.identity.v1.ResolveUserRequest
	7,  // 59: nauthilus.identity.v1.IdentityBackendService.GetMFAState:input_type -> nauthilus.identity.v1.GetMFAStateRequest
	9,  // 60: nauthilus.identity.v1.IdentityBackendService.BeginTOTPRegistration:input_type -> nauthilus.identity.v1.BeginTOTPRegistrationRequest
	11, // 61: nauthilus.identity.v1.IdentityBackendService.FinishTOTPRegistration:input_type -> nauthilus.identity.v1.FinishTOTPRegistrationRequest
	12, // 62: nauthilus.identity.v1.IdentityBackendService.VerifyTOTP:input_type -> nauthilus.identity.v1.VerifyTOTPRequest
	14, // 63: nauthilus.identity.v1.IdentityBackendService.DeleteTOTP:input_type -> nauthilus.identity.v1.DeleteTOTPRequest
	15, // 64: nauthilus.identity.v1.IdentityBackendService.GenerateRecoveryCodes:input_type -> nauthilus.identity.v1.GenerateRecoveryCodesRequest
	17, // 65: nauthilus.identity.v1.IdentityBackendService.UseRecoveryCode:input_type -> nauthilus.identity.v1.UseRecoveryCodeRequest
	19, // 66: nauthilus.identity.v1.IdentityBackendService.DeleteRecoveryCodes:input_type -> nauthilus.identity.v1.DeleteRecoveryCodesRequest
	20, // 67: nauthilus.identity.v1.IdentityBackendService.GetWebAuthnCredentials:input_type -> nauthilus.identity.v1.GetWebAuthnCredentialsRequest
	22, // 68: nauthilus.identity.v1.IdentityBackendService.SaveWebAuthnCredential:input_type -> nauthilus.identity.v1.SaveWebAuthnCredentialRequest
	23, // 69: nauthilus.identity.v1.IdentityBackendService.UpdateWebAuthnCredential:input_type -> nauthilus.identity.v1.UpdateWebAuthnCredentialRequest
	24, // 70: nauthilus.identity.v1.IdentityBackendService.DeleteWebAuthnCredential:input_type -> nauthilus.identity.v1.DeleteWebAuthnCredentialRequest
	6,  // 71: nauthilus.identity.v1.IdentityBackendService.ResolveUser:output_type -> nauthilus.identity.v1.UserSnapshotResponse
	8,  // 72: nauthilus.identity.v1.IdentityBackendService.GetMFAState:output_type -> nauthilus.identity.v1.MFAStateResponse
	10, // 73: nauthilus.identity.v1.IdentityBackendService.BeginTOTPRegistration:output_type -> nauthilus.identity.v1.BeginTOTPRegistrationResponse
	25, // 74: nauthilus.identity.v1.IdentityBackendService.FinishTOTPRegistration:output_type -> nauthilus.identity.v1.MFAWriteResponse
	13, // 75: nauthilus.identity.v1.IdentityBackendService.VerifyTOTP:output_type -> nauthilus.identity.v1.VerifyTOTPResponse
	25, // 76: nauthilus.identity.v1.IdentityBackendService.DeleteTOTP:output_type -> nauthilus.identity.v1.MFAWriteResponse
	16, // 77: nauthilus.identity.v1.IdentityBackendService.GenerateRecoveryCodes:output_type -> nauthilus.identity.v1.GenerateRecoveryCodesResponse
	18, // 78: nauthilus.identity.v1.IdentityBackendService.UseRecoveryCode:output_type -> nauthilus.identity.v1.UseRecoveryCodeResponse
	25, // 79: nauthilus.identity.v1.IdentityBackendService.DeleteRecoveryCodes:output_type -> nauthilus.identity.v1.MFAWriteResponse
	21, // 80: nauthilus.identity.v1.IdentityBackendService.GetWebAuthnCredentials:output_type -> nauthilus.identity.v1.WebAuthnCredentialsResponse
	25, // 81: nauthilus.identity.v1.IdentityBackendService.SaveWebAuthnCredential:output_type -> nauthilus.identity.v1.MFAWriteResponse
	25, // 82: nauthilus.identity.v1.IdentityBackendService.UpdateWebAuthnCredential:output_type -> nauthilus.identity.v1.MFAWriteResponse
	25, // 83: nauthilus.identity.v1.IdentityBackendService.DeleteWebAuthnCredential:output_type -> nauthilus.identity.v1.MFAWriteResponse
	71, // [71:84] is the sub-list for method output_type
	58, // [58:71] is the sub-list for method input_type
	58, // [58:58] is the sub-list for extension type_name
	58, // [58:58] is the sub-list for extension extendee
	0,  // [0:58] is the sub-list for field type_name
}

func init() { file_server_grpcapi_identity_v1_identity_backend_proto_init() }
func file_server_grpcapi_identity_v1_identity_backend_proto_init() {
	if File_server_grpcapi_identity_v1_identity_backend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_server_grpcapi_identity_v1_identity_backend_proto_rawDesc), len(file_server_grpcapi_identity_v1_identity_backend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   28,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_server_grpcapi_identity_v1_identity_backend_proto_goTypes,
		DependencyIndexes: file_server_grpcapi_identity_v1_identity_backend_proto_depIdxs,
		MessageInfos:      file_server_grpcapi_identity_v1_identity_backend_proto_msgTypes,
	}.Build()
	File_server_grpcapi_identity_v1_identity_backend_proto = out.File
	file_server_grpcapi_identity_v1_identity_backend_proto_goTypes = nil
	file_server_grpcapi_identity_v1_identity_backend_proto_depIdxs = nil
}
