---
name: Production Docker Build

"on":
  push:
    tags:
      - 'v*'

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/docker-stable-build.yaml
    with:
      release_tag: ${{ github.ref_name }}
      build_reason: tag-push
    secrets: inherit
