name: Run Unit Tests

on:
  push:
    branches:
      - features
  pull_request:
    branches:
      - features

env:
  GOEXPERIMENT: runtimesecret

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        build_variant: [ default, auth_basic_endpoint ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.26.x

      - name: Enable Go Modules
        run: go env -w GO111MODULE=on

      - name: Use Vendored Dependencies
        run: go env -w GOFLAGS=-mod=vendor

      - name: Run Unit Tests
        run: |
          if [ "${{ matrix.build_variant }}" = "auth_basic_endpoint" ]; then
            go test -tags auth_basic_endpoint $(go list ./... | grep -v /vendor/)
          else
            go test $(go list ./... | grep -v /vendor/)
          fi
